from util import topic, diagram, callout


def _case(cid, title, search, users, fr, nfr, scale, render, arch, state, api, cache, perf, fail, sec, a11y, obs, trade, talk):
    return topic(cid, title, search, "Case study", f'''
  <p class="stat-sub">Practice case (45–60 min). Not a claimed official company question. Draw first, then read.</p>
  <p><b>Users and job.</b> {users}</p>
  <p><b>Functional.</b> {fr}</p>
  <p><b>Non-functional.</b> {nfr}</p>
  <p><b>Client-scale guesses (say them).</b> {scale}</p>
  <p><b>Rendering.</b> {render}</p>
  <p><b>Architecture.</b> {arch}</p>
  <p><b>State map.</b> {state}</p>
  <p><b>API / events.</b> {api}</p>
  <p><b>Cache and races.</b> {cache}</p>
  <p><b>Performance.</b> {perf}</p>
  <p><b>Failures and degrade.</b> {fail}</p>
  <p><b>Security.</b> {sec}</p>
  <p><b>Accessibility.</b> {a11y}</p>
  <p><b>Observe.</b> {obs}</p>
  <p><b>Trade-offs (name what you rejected).</b> {trade}</p>
  <p><b>How you talk it.</b> {talk}</p>
  ''', "reactTopics")


def cases() -> str:
    items = [
        _case("cs-feed", "News feed / social home", "news feed instagram home case",
              "Logged-in user catching up on a personalized stream on phone and desktop.",
              "Infinite home feed, like/comment, composer, stories/rail optional in v2, deep link to a post.",
              "LCP on first post media; INP on like and scroll; CLS from images; not SEO for the home stream.",
              "p95: 20 posts in first paint, 2k in session, 1.5MB images if you are careless, 3 tabs.",
              "CSR after login. Public permalink pages can be SSR. Home is not SSG.",
              "Shell + FeedRoute. Virtualized list. PostCard cheap. Media lazy except first one or two. Composer lazy. Comments as overlay route.",
              "URL: / and /p/:id. Server cache: feed page cursors, post, like-state. Local: composer draft. Ephemeral: like burst animation.",
              "GET /feed?cursor; POST /posts/:id/like (idempotent); GET /posts/:id. Optional WS for new-post badge only.",
              "Key ['feed', cursor]. Don’t refetch the whole home on one like — patch the post key. Abort if they jump to a hashtag feed.",
              "Virtualize; priority on LCP image; srcset; don’t hydrate a video player for every row.",
              "Empty, muted, error per card. If like fails, revert. If feed 500, retry + cached last page.",
              "Encode captions. Authz on every post. No token in image URLs that leak private media.",
              "List + article semantics; keyboard like; don’t trap scroll; alt on images.",
              "LCP first media, INP like, feed error rate, time-to-first-byte of /feed.",
              "Rejected: fetching 2k posts; WS for every like; SSR of the personalized home.",
              "Start with first paint of post 1, then cursor + virtualize, then like as optimistic patch. Don’t draw Kafka."),
        _case("cs-board", "Jira-like issue board", "jira kanban board frontend case",
              "Engineers and PMs moving work on a scrum/kanban board. Desktop-first, keyboard required.",
              "Columns, cards, drag, filter/JQL, issue overlay, comments, permissions, optional plugins.",
              "INP on drag p75 &lt; 200ms; permission-safe transitions; a11y move without drag.",
              "400 visible cards, 10k in filter, 50 collaborators, 0–20 plugin iframes.",
              "CSR. Logged-in tool. Don’t SSR the board body.",
              "features/board, issue-view, search. Virtualized columns. Issue as route overlay. Plugin host iframe.",
              "URL: board, jql, selected. Cache: board snapshot, issues. Local: filter input. Ephemeral: drag overlay.",
              "GET /board?jql; PATCH /issues/:id; GET /issues/:id; WS or 15s poll for remote moves.",
              "SWR snapshot 10–30s; mutation invalidates issue + affected columns; abort stale JQL.",
              "Virtualize; cheap cards; extra fields only on overlay; transition the list when filter commits.",
              "409 on move: refetch card. WS drop: poll. Plugin throw: kill the slot.",
              "Server authz; encode titles; CSRF on cookie POST; sandbox plugins; CSP.",
              "Roving tabindex; live region on move; menu alternative to drag; no color-only status.",
              "Drag INP, transition errors, plugin init failures, correlation id = issue key.",
              "Rejected: one DOM node per filter hit; in-process untrusted plugins; CRDT for card moves.",
              "Users → numbers → URL+virtualize → optimistic PATCH → plugins as iframes → a11y move."),
        _case("cs-doc", "Confluence-like document", "confluence document editor case",
              "Knowledge workers reading and occasionally editing long pages in a space tree.",
              "Tree nav, read view, edit, comments, permissions, search, macros.",
              "LCP of page body; editor INP; conflict-safe saves; drafts offline.",
              "100k nodes in a space tree (virtualize); 200KB–2MB docs; concurrent editors uncommon but painful.",
              "Read: SSR or stream HTML. Edit: lazy CSR editor. Never ship editor JS on read.",
              "page-view, editor, tree, search. Macros isolated + error boundaries.",
              "URL: space/page/anchor. Draft in IDB. Cache: published page+version. Presence optional/ephemeral.",
              "GET page; PUT with If-Match version + clientMutationId; tree as paginated children.",
              "Immutable versions; SWR on read; never treat draft as published.",
              "Split read/edit; virtualize tree; lazy images; don’t hydrate 2MB on view.",
              "409: show conflict. Offline: draft stays. Macro crash: replace with error card.",
              "XSS in HTML/macros; sanitize; CSP; permission on write.",
              "Landmarks, skip link; editor a11y is a budget — say so.",
              "Save latency, conflict rate, macro crash, LCP body.",
              "Rejected: one rich surface for read and edit; inventing CRDT in 45 minutes.",
              "Lead with read/edit split and versioned PUT. Presence is a side channel."),
        _case("cs-chat", "Slack-like messaging", "slack chat frontend case",
              "Teams talking in channels; unread and catch-up matter more than pretty bubbles.",
              "Channel list, message list, composer, threads, search, unread, presence, uploads.",
              "INP on send; jump-to-bottom; reconnect without losing composer draft.",
              "p95 channel 50k messages historically; window ~50–100 in DOM; 20 channels in the sidebar.",
              "CSR. Deep links to /channel/:id/p/:ts may SSR a permalink.",
              "sidebar, message-window (virtualized, bidirectional load), composer, thread drawer.",
              "URL: channel, thread, search q. Cache: messages by channel+cursor. Local: drafts per channel in IDB. Ephemeral: typing indicators.",
              "GET messages?cursor; POST message idempotent; WS events; REST inbox for gap fill.",
              "Dedupe by message id. After WS reconnect, fetch since last seq. Abort if channel switches.",
              "Virtualize both directions; don’t rerender sidebar on each message; worker for large paste.",
              "WS down: poll + banner. Send fail: stay in composer. Gap: “X new messages” chip.",
              "Encode messages; authz per channel; signed upload URLs.",
              "Log semantics; composer label; jump links; don’t rely on color for unread.",
              "Send success, reconnect time, dropped events, INP composer.",
              "Rejected: mounting the whole history; treating WS as lossless; storing drafts only in memory.",
              "Window + cursor + REST reconcile. Typing is ephemeral. Drafts survive refresh."),
        _case("cs-yt", "YouTube-like watch page", "youtube watch page frontend case",
              "Viewer watches a video, maybe comments, maybe next-up. SEO on public watch URLs.",
              "Player, title, comments, related, autoplay next optional.",
              "LCP/hero is the player poster or first frame; INP on pause/seek; CLS from related.",
              "Comments 10k+; related 20; player is the money path.",
              "SSR watch shell + meta. Player is a controlled island. Comments CSR/lazy.",
              "WatchRoute: player module isolated so comment rerenders cannot drop frames.",
              "URL: v, t, list. Cache: video meta, comments pages. Local: volume, playback rate (careful with a11y).",
              "GET /videos/:id; GET /comments?cursor; POST comment.",
              "Don’t refetch video meta when paging comments. Abort comment fetch on video change.",
              "Don’t hydrate comments before player is ready; reserve player aspect-ratio.",
              "Autoplay policies; offline not required; 403 on private video.",
              "No XSS in descriptions; authz on private; captions as first-class.",
              "Player keyboard; captions; comments combobox for @mentions.",
              "Time-to-first-frame, rebuffer, comment post errors.",
              "Rejected: one React tree where likes rerender the &lt;video&gt;; fetching all comments.",
              "Isolate the player. SSR the URL. Lazy the conversation."),
        _case("cs-netflix", "Netflix-like browse", "netflix browse rows frontend case",
              "Member browsing catalogs; focus and row virtualization; logged-in, little SEO on /browse.",
              "Rows, titles, preview on focus, continue-watching, search.",
              "INP on arrowing; LCP first poster; CLS reserved cards.",
              "20 rows × 30 titles; only ~12 posters on screen.",
              "CSR. CDN images. Maybe SSR a tiny shell.",
              "Row virtualization (vertical) + windowed titles (horizontal). Preview player deferred.",
              "URL: /browse, /title/:id, search q. Cache: rows, title. Ephemeral: focused index.",
              "GET /browse/rows; GET /titles/:id; search endpoint.",
              "Prefetch next row near viewport. Don’t prefetch every trailer.",
              "Aspect-ratio boxes; decode only near focus; keyboard spatial nav.",
              "Row 500: isolate. Image 404: placeholder. Preview fail: static art.",
              "Authz on catalog per region; no leak of unreleased titles in prefetch.",
              "Grid/list keyboard; visible focus; no autoplay without control.",
              "LCP first poster, INP arrow, prefetch waste.",
              "Rejected: 600 &lt;img&gt; eager; mouse-only rails.",
              "Window both axes. Focus is a first-class state. Trailers are deferred."),
        _case("cs-dash", "Analytics dashboard (100 widgets)", "analytics dashboard widgets case",
              "Analysts with a saved layout and a shared time range.",
              "Configurable grid, date range, export, share link.",
              "First widgets &lt; 2s; no 100-request waterfall; CLS-stable grid.",
              "100 widgets; some queries pre-aggregated; 1M raw rows never in the browser.",
              "CSR. Layout from user prefs. Share URL includes range + dashboard id.",
              "Widget registry + layout. Each widget lazy + error boundary. Shared time-range in URL.",
              "URL: id, from, to, tz. Cache: per widget query key includes range. Local: edit-layout mode.",
              "GET /dashboards/:id; GET /widgets/data?ids=&amp;from=&amp;to (batch) or BFF view.",
              "ETag per widget query. Prefetch visible; idle below fold.",
              "Virtualize rows of the grid; web worker only if you chart huge client arrays (usually you should not).",
              "Slow widget: spinner in the cell, not the page. Export 403: explain.",
              "Tenant isolation; no tokens in widget image URLs.",
              "Text alternative for charts; keyboard to widget chrome.",
              "Widget error vs page error; p95 widget time; batch size.",
              "Rejected: 100 parallel GETs; custom JS plugins without a sandbox; charting raw 1M rows in React.",
              "Batch or BFF first. Isolate failure. Time range is URL."),
        _case("cs-ecom", "Ecommerce PDP + checkout", "ecommerce pdp checkout frontend case",
              "Shopper comparing a product, then paying. SEO on PDP. Reliability on checkout.",
              "PDP, gallery, cart, checkout, search.",
              "LCP on PDP image; checkout must not lose the cart; inventory freshness honest.",
              "Millions of PDPs; flash sale traffic; cart is small state.",
              "SSR/ISR PDP. CSR cart/checkout. Edge cache public HTML.",
              "PDP island for add-to-cart. Checkout is a short, boring wizard — tiny JS.",
              "URL: product slug, variant. Cart: server cart id in cookie + cache. Checkout step in URL.",
              "GET product; POST cart (idempotent); checkout session APIs.",
              "CDN for PDP; no-store on cart/checkout HTML; ETag product.",
              "Priority LCP image; defer reviews; don’t ship the admin CMS on PDP.",
              "Sold-out 409: refresh variant. Payment fail: stay on step, don’t clear cart.",
              "XSS in reviews; PCI — don’t invent a card iframe story you can’t defend; CSRF on cart.",
              "Name/price as real headings; keyboard gallery; checkout labels.",
              "PDP LCP, add-to-cart success, checkout completion, 409 rate.",
              "Rejected: CSR-only PDP; one SPA bundle for storefront + admin; optimistic pay.",
              "Split the marketing page from the money path. ISR the PDP. Boredom is a feature at checkout."),
        _case("cs-ac", "Autocomplete / command palette", "autocomplete command palette case",
              "Power user jumping to issues, docs, actions. Keyboard is the product.",
              "Typeahead, recents, groups (issues, people, actions), abort, empty.",
              "INP on each key; combobox a11y; &lt;200ms suggest p75.",
              "10M issues; 20 results; mobile has a smaller palette.",
              "CSR overlay. No SSR.",
              "Portal combobox. Query key [suggest, q, scope]. Recents in localStorage (not secrets).",
              "Local: query string. Cache: last 20 q. Ephemeral: highlighted index.",
              "GET /suggest?q=&amp;limit=20. Actions are client-side commands.",
              "Debounce 150ms; abort; drop stale gen. Authz filter on server.",
              "Cheap highlight; don’t rerender the board underneath (portal + isolated state).",
              "Slow: show recents. Empty: helpful. Error: retry. Private titles must never appear.",
              "No leak via suggest. Rate limit. Encode matches.",
              "APG combobox; aria-activedescendant; announce count.",
              "Suggest latency, abort rate, INP.",
              "Rejected: client-filter of 10M; fetching on every key without abort; mouse-only list.",
              "Say combobox + abort + debounce before any library name."),
        _case("cs-notif", "Notification center", "notification bell inbox case",
              "User returning to a tool, needing unread count and a list that deep-links.",
              "Bell, badge, toasts, inbox, mark read, filters.",
              "Badge freshness SLA you name (30s vs 1s); polite live region; at-least-once events.",
              "Burst at release time; 50 events/min rare; inbox retained 30–90 days on server.",
              "CSR. SW push optional later.",
              "Badge in shell. Inbox route/overlay. Toast host isolated.",
              "Cache: inbox pages, unread count. Local: last-seen. Ephemeral: toast queue.",
              "REST inbox + mark-read. WS/SSE hint. Push for closed tab.",
              "Dedupe id. Reconnect: GET since cursor. Don’t setState on the issue page for each toast.",
              "Badge can poll. Inbox virtualize. Toasts cap at N.",
              "WS dead: poll + ‘Live paused’. Mark-read fail: keep unread, retry.",
              "Authz per notification. No leaking issue titles in a toast on a shared screen if you have a privacy mode — mention it.",
              "Button + dialog; live polite; keyboard list.",
              "Unread freshness, drop rate, mark-read errors.",
              "Rejected: WS-only inbox; toasting every remote presence event.",
              "REST is source of truth. Socket is a hint. Degrade out loud."),
        _case("cs-upload", "Multi-GB file uploader", "large file upload resume worker case",
              "User attaching a video or dump to a ticket. Progress must not freeze the tab.",
              "Select, hash, chunk, resume, cancel, virus-scan status, attach to entity.",
              "Main thread stays interactive; resume after refresh; honest errors.",
              "2GB file; 8MB chunks; 3 concurrent files max.",
              "CSR dialog. Worker for hash. Direct-to-object-storage with signed URLs.",
              "UploadSession module. Progress in a small store. Do not put File in Redux.",
              "Local: session id in IDB (chunks done). Cache: attachment record after complete.",
              "POST session → signed URLs; PUT chunks; POST complete; GET scan status.",
              "Idempotent complete. Retry chunk on 5xx. Don’t refetch board each progress tick.",
              "rAF progress; worker hash; cap concurrency.",
              "403 signed URL expired: refresh session. Scan fail: keep file out of the issue.",
              "Authz on session; no public bucket list; XSS if you preview HTML files — don’t.",
              "Progressbar role; cancel button; don’t trap the whole app.",
              "Time-to-complete, chunk retry, main-thread long tasks during upload.",
              "Rejected: hashing on main; streaming 2GB through the BFF; progress setState every byte.",
              "Worker + chunks + IDB resume. Progress is ephemeral."),
        _case("cs-grid", "Admin data grid", "data grid table virtualize case",
              "Ops/admin filtering tens of thousands of rows with sort, selection, bulk actions.",
              "Filter, sort, column picker, row select, bulk, export, saved views.",
              "INP on scroll and select; don’t download the warehouse.",
              "p95 50k rows in the query; 30 columns; 40 rows visible.",
              "CSR. Saved view in URL.",
              "Headless table + virtualize rows (and columns if wide). Selection set by id.",
              "URL: filters, sort, view id. Cache: page/window query. Local: column widths.",
              "GET /rows?cursor&amp;sort; POST /bulk (idempotent). Export is async job + poll.",
              "Window queries, not offset 0–50000. Invalidate window after bulk.",
              "Virtualize; don’t render 30 heavy cells offscreen; debounce filter.",
              "Bulk partial fail: report per id. Export 403.",
              "Authz per row/field; export ACL; no PII in client logs.",
              "Grid pattern; header buttons; select-all meaning (page vs query) — say it.",
              "Scroll INP, bulk error rate, export time.",
              "Rejected: rendering 50k &lt;tr&gt;; select-all that silently means only this page.",
              "Window + virtualize + say what select-all means. Export is a job."),
        _case("cs-cal", "Calendar / scheduler", "calendar scheduling frontend case",
              "People booking and dragging events across a week view.",
              "Month/week/day, create, drag-resize, timezone, conflicts, invites.",
              "INP on drag; correct TZ; CLS reserved all-day row.",
              "200 events/week visible; 2k in month; recurring is a server expansion.",
              "CSR. Shareable URL for date + view.",
              "Time grid + positioned events (absolute in a relative grid). Don’t use 200 stacked block layouts.",
              "URL: date, view. Cache: events in range. Ephemeral: drag preview. Local: draft create.",
              "GET /events?from&amp;to; POST/PATCH event. Recurring: server expands.",
              "Prefetch prev/next week. Abort on range change.",
              "Only mount visible days; cheap event chips; timezone in the API, not guessed in CSS.",
              "Conflict 409: show overlap. TZ wrong: worse than jank — test it.",
              "Authz on calendar ACL; XSS in event title.",
              "Keyboard create; announce move; don’t use color-only for ‘busy’.",
              "Drag INP, TZ bugs (track as errors), conflict rate.",
              "Rejected: expanding 5 years of rrules in the browser; one component per minute cell.",
              "Range query + positioned chips + TZ as data. Recurrence stays on the server."),
        _case("cs-email", "Email client", "email client inbox frontend case",
              "Knowledge worker triaging mail. Unread and keyboard speed matter.",
              "Folders, list, thread, compose, search, undo send optional v2.",
              "INP on j/k navigation; restore draft; don’t lose unsaved compose.",
              "Inbox 100k; window 50; thread 200 messages.",
              "CSR. Deep link /inbox/:id.",
              "Three-pane. Virtualize list. Thread mount by id. Compose is a route or docked draft in IDB.",
              "URL: folder, thread, q. Cache: thread, list windows. Local: drafts.",
              "GET list cursor; GET thread; POST send idempotent.",
              "Mark-read debounce so you don’t stampede. Abort on folder switch.",
              "Don’t render HTML mail without sanitize. Isolate the iframe for message body.",
              "Send fail: stay in compose. Offline: queue.",
              "HTML email is an XSS festival — iframe sandbox + sanitize. Authz per mailbox.",
              "Listbox + thread article; labels on compose fields.",
              "Mark-read errors, send errors, INP next-message.",
              "Rejected: rendering raw HTML in the app origin; fetching the whole inbox.",
              "Three pane + window + sandboxed body. Drafts in IDB."),
        _case("cs-maps", "Maps / live tracking (Uber-like rider)", "maps live tracking frontend case",
              "Rider watching a car. Map is the product; React is the chrome.",
              "Map, ETA, driver marker, trip states, cancel, receipts later.",
              "Marker at 1–5Hz without React rerendering the world; battery; degrade if tiles fail.",
              "One trip; tiles from CDN; location stream.",
              "CSR. Map SDK is an island (refs). Chrome is React.",
              "Never put lat/lng at 5Hz into React state that rerenders the sheet.",
              "URL: trip id. Cache: trip snapshot. Ephemeral: marker in the map SDK.",
              "GET trip; WS or poll positions; POST cancel.",
              "Snapshot on reconnect. Don’t invalidate the whole app on each point.",
              "Throttle UI ETA text to 1Hz. Map owns the marker.",
              "GPS gap: last known + banner. Cancel 409: already started.",
              "Location is sensitive — retention, screen-share caution.",
              "ETA as text; cancel button; don’t rely on color of the car.",
              "Time-to-first-map, drop rate, cancel errors.",
              "Rejected: setState per GPS tick on a big React tree; custom WebGL in 45 minutes.",
              "Island the map. React for trip state. Throttle text. Degrade to last point."),
        _case("cs-figma", "Canvas / Figma-like (honest scope)", "figma canvas frontend case honest",
              "Designers moving nodes on a shared canvas. This is the trap prompt.",
              "v1 interview scope: pan/zoom, select, move rectangles, presence cursors. Not a production CRDT.",
              "60fps pan if you can; INP on select; don’t bluff multiplayer OT.",
              "1k nodes; 20 visible; 5 collaborators in v1 story.",
              "CSR. Canvas/WebGL or SVG for v1 rectangles — say which and why (SVG simpler, GL for 10k).",
              "Scene graph in a ref/store outside React. React for panels (layers, inspector).",
              "URL: file id, node selection. Ephemeral: camera, drag. Presence: side channel.",
              "GET file snapshot; PATCH nodes batched; WS for remote ops if they insist — or poll + locks for v1.",
              "Don’t rerender inspector at 60Hz. Camera in a ref.",
              "Hit-test in the canvas layer. React lists virtualize in the left panel only.",
              "If they want Figma multiplayer: ‘I’d integrate a known sync engine; the hour is camera, selection, and inspector isolation.’",
              "Authz on file; XSS if you import SVG — sanitize.",
              "Non-canvas controls must be keyboard accessible; canvas needs a list alternative for selection.",
              "FPS, op drop, panel INP.",
              "Rejected: storing the scene in React context; claiming you will implement CRDT in the remaining 20 minutes.",
              "Honesty is the design. Isolate the scene from React. Scope v1 out loud."),
        _case("cs-comments", "Threaded comments", "threaded comments discussion case",
              "Readers discussing a page or issue. Nesting and quote matter.",
              "List, reply, edit, delete, reactions, pagination, deep link to a comment.",
              "INP on reply; don’t jump the page (CLS); offline draft.",
              "2k comments; window 20; depth cap (e.g. 4) — say it.",
              "CSR on the entity page, lazy below fold.",
              "Tree rendered as flat list + indent (easier virtualize) or true tree with windowing.",
              "URL: comment id. Cache: pages. Local: drafts per parent id.",
              "GET comments?cursor; POST reply idempotent; PATCH edit.",
              "After POST, patch cache or prepend. Abort if entity changes.",
              "Virtualize the flat list; don’t mount 2k editors.",
              "409 edit: show server copy. Soft-delete vs hide.",
              "Encode; mention authz; no HTML in comments unless sanitized.",
              "Article + nested lists or tree APG; announce posted.",
              "Post errors, time-to-visible reply.",
              "Rejected: one component per comment with its own editor always mounted; unbounded depth.",
              "Cap depth. Flat+indent if you virtualize. Drafts per thread."),
        _case("cs-dsplat", "Design-system + theme platform", "design system platform theming case",
              "12 product teams consuming one kit. You are designing the system, not a button.",
              "Tokens, components, versioning, docs site, contribution RFC, theme packs.",
              "No breaking padding without semver; a11y in the kit; docs LCP fine.",
              "200 components; 12 apps; dark/light/high-contrast.",
              "Docs: SSG. Consumers: package.",
              "Token pipeline → CSS variables. Components use tokens only. Codemod for breaks.",
              "Version in package.json. Theme class on html. No per-feature hex.",
              "N/A as a product API — the API is the component props.",
              "Cache docs on CDN. Apps pin major versions.",
              "Tree-shake; per-icon imports; don’t ship all icons in the board.",
              "A bad release: rollback the package. Don’t runtime-federate the button ‘to ship faster’.",
              "A11y bugs are P0 in the kit. Contrast tokens.",
              "Every interactive component has a keyboard story in docs.",
              "Adoption, a11y defects escaped, bundle of @ds/button.",
              "Rejected: 40 booleans on Button; runtime MFE for the kit; themes as if (dark) in features.",
              "Tokens + semver + a11y ownership. Docs SSG. Features consume, they don’t fork hex."),
    ]

    return f'''
<section class="block" id="cases" data-search="Frontend system design case studies" data-stype="Section">
  <p class="kicker">{len(items)} cases</p>
  <h2 class="section-title">Practical case studies</h2>
  <p class="lede">Treat each as a 45–60 minute interview. Draw the 16 steps on paper. Then reveal. Mark complete only if you could teach the trade-offs without this file.</p>
  {callout("These are practice shapes (Jira-like, Confluence-like, YouTube-like). They are not claimed official questions from those companies.")}
  {diagram("Pick a case → timebox 45 → 16 steps → name two rejects → then read")}
  {''.join(items)}
</section>
'''
