from util import esc


def _sd(i, title, cat, stmt, clarify, fr, nfr, assume, arch, comps, flow, api, state, cache, perf, fail, sec, a11y, obs, scale, trade, follow, talk=None):
    if not talk:
        talk = (
            f"Lead with users, scale, and the critical path for {title}. "
            "Name two alternatives you rejected. Cover failure, accessibility, security, and how you would measure success."
        )
    hid = f"sd-{i}"
    return f'''
<article class="problem" id="{hid}" data-pid="{hid}" data-search="{esc(title)}" data-stype="System design" data-cat="{cat}" data-mock="1" data-filterable>
  <div class="meta-row"><span class="badge badge-pattern">Practice question</span><span class="chip">{cat}</span></div>
  <h3>{i}. {esc(title)}</h3>
  <p><b>1. Problem.</b> {stmt}</p>
  <p><b>2. Clarifying questions.</b> {clarify}</p>
  <p><button type="button" class="toggle-btn" data-toggle="{hid}-a">Reveal ideal discussion</button>
     <button type="button" class="toggle-btn" data-complete="designs" data-cid="{hid}">Mark complete</button></p>
  <div class="reveal" id="{hid}-a">
    <p><b>3. Functional.</b> {fr}</p>
    <p><b>4. Non-functional.</b> {nfr}</p>
    <p><b>5. Assumptions.</b> {assume}</p>
    <p><b>6–8. Architecture / components / data flow.</b> {arch} {comps} {flow}</p>
    <p><b>9. API.</b> {api}</p>
    <p><b>10. State.</b> {state}</p>
    <p><b>11. Caching.</b> {cache}</p>
    <p><b>12. Performance.</b> {perf}</p>
    <p><b>13. Failures.</b> {fail}</p>
    <p><b>14. Security.</b> {sec}</p>
    <p><b>15. Accessibility.</b> {a11y}</p>
    <p><b>16. Observability.</b> {obs}</p>
    <p><b>17. Scaling the client.</b> {scale}</p>
    <p><b>18. Trade-offs.</b> {trade}</p>
    <p><b>19. Follow-ups.</b> {follow}</p>
    <p><b>20. Ideal interview discussion.</b> {talk}</p>
  </div>
  <div class="status-btns">
    <button type="button" data-status="not-started">Not Started</button>
    <button type="button" data-status="attempted">Attempted</button>
    <button type="button" data-status="solved">Solved</button>
    <button type="button" data-status="review">Review</button>
    <button type="button" data-status="mastered">Mastered</button>
  </div>
</article>
'''


SD = [
    ("Design a news feed", "feed",
     "Home stream with posts, like, infinite scroll.",
     "SEO? Logged-in only? Media-heavy? Mobile?",
     "Feed, like, open post, cursor pagination.",
     "LCP first media, INP like, CLS images.",
     "20 posts first page, 2k/session, login required.",
     "CSR feed. Virtualized list. First image priority.",
     "FeedPage, PostCard, Composer lazy, PostOverlay.",
     "GET feed → render → optimistic like → PATCH → patch post key.",
     "GET /feed?cursor; POST /posts/:id/like idempotent.",
     "URL / and /p/:id. Cache feed pages + post. Draft local.",
     "Invalidate post, not the whole home, on like.",
     "Virtualize; srcset; don’t mount video on every row.",
     "Like fail rollback. Feed 500: last page + retry.",
     "Encode captions. Authz. Signed media.",
     "Alt text; keyboard like; list semantics.",
     "LCP, like errors, /feed p95.",
     "More posts → still windowed. Don’t fetch the universe.",
     "Rejected: WS for every like; SSR personalized home.",
     "How do ads / inserted cards affect keys and a11y?",
     "First paint of post 1, then cursor, then like as a patch."),
    ("Design a Jira-like board", "work",
     "Kanban with drag, filter, issue overlay.",
     "Realtime? Plugins? Card count? Mobile?",
     "Move, filter, open, optional presence.",
     "INP drag, keyboard move, authz.",
     "400 visible, 10k filter, cookie session.",
     "CSR. Virtualized columns. Overlay route.",
     "Board, Column, Card, IssueDrawer, useMoveIssue.",
     "Snapshot → optimistic move → PATCH → reconcile. Remote: poll or WS.",
     "GET /board?jql; PATCH /issues/:id; GET /issues/:id.",
     "URL jql+selected. Cache board/issues. Drag ephemeral.",
     "Abort stale JQL. Invalidate issue + columns.",
     "Cheap cards; extra fields on overlay.",
     "409 refetch. Plugin crash isolated. WS→poll.",
     "Server authz; XSS; CSRF; iframe plugins.",
     "Roving tab; live region; menu move.",
     "Drag INP, transition errors, plugin fails.",
     "Virtualize + paginate columns as filter grows.",
     "Rejected: in-process untrusted JS; CRDT moves.",
     "Custom fields on the card?",
     "Numbers → URL → virtualize → optimistic PATCH → a11y."),
    ("Design a document editor (Confluence-like)", "work",
     "Read and edit long pages with a tree.",
     "Multiplayer carets? Macros? Offline?",
     "Read, edit, save, tree, comments.",
     "LCP body; conflict-safe save; draft offline.",
     "2MB doc; virtualize tree; rare concurrent edit.",
     "SSR/stream read. Lazy editor CSR.",
     "ReadView, Editor lazy, Tree, macros isolated.",
     "GET page → read. Edit → PUT If-Match version.",
     "GET/PUT page; tree children paginated.",
     "URL page/anchor. Draft IDB. Cache published version.",
     "Never cache draft as published.",
     "No editor JS on read. Lazy images.",
     "409 conflict UI. Macro error card.",
     "Sanitize HTML; CSP; write authz.",
     "Landmarks; editor a11y budgeted.",
     "Save latency, conflicts, LCP.",
     "Split stays as doc grows. Don’t hydrate more.",
     "Rejected: CRDT in 45 min; one surface for read/edit.",
     "Who wins on conflict?",
     "Read/edit split + versioned PUT. Honest about CRDT."),
    ("Design autocomplete", "search",
     "Search-as-you-type for issues or people.",
     "Min chars? Mobile? Multi-entity?",
     "Suggest, keyboard, recents, abort.",
     "INP type; combobox; &lt;200ms p75.",
     "10M docs, 20 hits, prefix search on server.",
     "Portal combobox. Isolated from the page tree.",
     "useSuggest, Highlight, Recents.",
     "Keystroke → local → debounce → fetch → replace.",
     "GET /suggest?q=&amp;limit=20",
     "Input local; recents localStorage; results short TTL.",
     "Abort + gen. Cache last 20 q.",
     "Cheap highlight. Don’t rerender the app.",
     "Slow: recents. Empty: help. Authz miss: nothing leaked.",
     "Server filter. Encode. Rate limit.",
     "APG combobox; announce count.",
     "Latency, abort rate.",
     "Edge-cache popular prefixes.",
     "Rejected: client filter of millions.",
     "Typo tolerance?",
     "Combobox + abort + debounce before any library."),
    ("Design a command palette", "search",
     "Cmd-K to jump or run actions.",
     "Which actions? Create? Navigation only?",
     "Search entities + commands. Recent.",
     "Keyboard-first. INP. Combobox.",
     "Same as suggest + a static command list.",
     "Modal combobox. Commands local; entities via API.",
     "Palette, Group, Item, Preview optional.",
     "Open → recents → type → mixed results → enter runs.",
     "GET /suggest. Commands are client registry.",
     "Open state local. Query local. Results cache.",
     "Debounce entity queries only.",
     "Don’t block the app behind a slow suggest.",
     "Action fail: toast, stay open.",
     "Commands that mutate need authz on the API they call.",
     "Dialog + combobox; focus restore on close.",
     "Time-to-action, errors.",
     "Command list stays local as it grows; entities stay server.",
     "Rejected: mouse-only; fetching commands from network every open.",
     "How do plugins register commands?",
     "It’s typeahead plus a command registry. Same a11y."),
    ("Design notifications", "realtime",
     "Bell, badge, inbox, toasts.",
     "Push? Email? Freshness SLA?",
     "List, unread, deep link, mark read.",
     "At-least-once; polite live; degrade.",
     "Burst 50/min rare; inbox on server.",
     "Shell badge. Inbox overlay. Toast host.",
     "Badge, Inbox, Toast, event mapper.",
     "REST truth + WS hint. Dedupe id.",
     "GET /inbox?cursor; POST /read; WS optional.",
     "Cache inbox + count. Toast ephemeral.",
     "Reconnect since cursor.",
     "Cap toasts. Virtualize inbox.",
     "WS down → poll + banner.",
     "Authz per row. Privacy mode mention.",
     "Dialog + list + live polite.",
     "Freshness, drops, mark-read errors.",
     "Poll is OK if SLA is 30s.",
     "Rejected: WS-only; toasting presence.",
     "Digest vs realtime?",
     "REST + hint + degrade. Don’t start with Kafka."),
    ("Design a 100-widget dashboard", "data",
     "Configurable widgets and a shared time range.",
     "Custom JS widgets? Export?",
     "Layout, range, widget data, share URL.",
     "No 100 waterfalls; isolate errors; CLS grid.",
     "100 widgets; aggregates only in browser.",
     "Registry + lazy widgets + error boundaries.",
     "Dashboard, Grid, WidgetFrame, TimeRange.",
     "Bootstrap layout → batch data → paint visible.",
     "GET dashboard; batch GET widget data.",
     "URL range + id. Per-widget keys.",
     "ETag; idle load below fold.",
     "Virtualize grid rows.",
     "Slow widget local spinner. 403 export.",
     "Tenant. No tokens in URLs.",
     "Chart text alternative; keyboard chrome.",
     "Widget p95, page errors vs cell errors.",
     "Batch stays as widgets grow.",
     "Rejected: 100 GETs; raw 1M rows.",
     "How do you allow custom widgets?",
     "Batch/BFF + isolate. Range in URL."),
    ("Design an ecommerce PDP", "commerce",
     "Public product page + add to cart.",
     "Variants? Reviews? International?",
     "Gallery, price, add, reviews lazy.",
     "LCP image; SEO; inventory honesty.",
     "ISR/SSR PDP. Millions of URLs.",
     "SSR HTML + island add-to-cart.",
     "PDP, Gallery, BuyBox, Reviews lazy.",
     "HTML → hydrate island → POST cart.",
     "GET product; POST cart idempotent.",
     "URL slug+variant. Cart cookie+cache.",
     "CDN HTML; no-store cart.",
     "Priority LCP image; defer reviews.",
     "409 sold out. Don’t optimistic-pay.",
     "XSS reviews; CSRF cart.",
     "Headings; keyboard gallery.",
     "LCP, add success, 409 rate.",
     "ISR + revalidate on price change.",
     "Rejected: CSR-only PDP; admin in the bundle.",
     "Flash sale?",
     "ISR the page. Tiny JS for buy. Honest stock."),
    ("Design checkout", "commerce",
     "Multi-step pay after cart.",
     "Guest? Saved cards? Taxes?",
     "Address, method, review, pay.",
     "Reliability; no lost cart; a11y forms.",
     "Small state machine. Tiny JS.",
     "Boring wizard. Step in URL.",
     "Steps as routes. No dashboard kit.",
     "Each step POST. Payment via hosted fields / PSP.",
     "Checkout session APIs. Idempotent pay.",
     "URL step. Session server-side.",
     "no-store. Don’t cache PII HTML.",
     "Minimal JS. No virtualization needed.",
     "Pay fail stay. Don’t clear cart.",
     "PCI: don’t invent card handling. CSRF.",
     "Labels, errors, focus on invalid.",
     "Completion, pay errors.",
     "Keep it a short app as volume grows.",
     "Rejected: one SPA with the whole storefront.",
     "3-D Secure / redirect?",
     "Boredom is the architecture. Reliability > novelty."),
    ("Design a chat app", "realtime",
     "Channels and messages.",
     "Threads? Attachments? History size?",
     "List, send, unread, reconnect.",
     "INP send; drafts; gap fill.",
     "50–100 DOM messages; 50k history on server.",
     "Virtualized window + composer.",
     "Sidebar, Window, Composer, Thread.",
     "Snapshot + WS + REST since seq.",
     "GET messages; POST idempotent; WS.",
     "URL channel. Drafts IDB. Typing ephemeral.",
     "Dedupe id. Abort on channel switch.",
     "Both-direction virtualize.",
     "WS→poll. Send fail keeps text.",
     "Encode; channel authz; signed uploads.",
     "Log + labeled composer.",
     "Send, reconnect, drops.",
     "Window stays fixed as history grows.",
     "Rejected: mount all history; trust WS lossless.",
     "Search across channels?",
     "Window + REST reconcile. Drafts survive."),
    ("Design a notification-free presence stack", "realtime",
     "Avatars of who is on an issue.",
     "Cursors? How many people?",
     "List of viewers, join/leave.",
     "Must not rerender the description at 1Hz.",
     "50 people; heartbeat 10s.",
     "Presence store colocated. Throttle.",
     "PresenceStack, AvatarList.",
     "WS heartbeat → store → 1–2s UI tick.",
     "WS or poll /presence?issue=",
     "Ephemeral. Not in issue cache.",
     "Ignore stale after reconnect snapshot.",
     "Don’t touch document components.",
     "Drop → empty list + ‘presence paused’.",
     "Authz viewers. Don’t leak hidden users.",
     "List of names, not color-only dots.",
     "Update rate, dropped sockets.",
     "Cap visible avatars +N.",
     "Rejected: setState on IssuePage each heartbeat.",
     "Cursors in the editor?",
     "Colocate and throttle. Separate channel."),
    ("Design comments on an issue", "work",
     "Threaded discussion under a ticket.",
     "Depth? Markdown? Mentions?",
     "List, reply, edit, deep link.",
     "INP reply; drafts; encode.",
     "2k comments; depth cap 4; window 20.",
     "Flat+indent virtualize or windowed tree.",
     "CommentList, Editor on demand, Mention combobox.",
     "GET page → POST reply → patch cache.",
     "GET/POST/PATCH comments.",
     "URL comment id. Drafts local.",
     "Abort if issue changes.",
     "One editor mounted.",
     "409 edit. Soft delete.",
     "Encode/sanitize. Mention authz.",
     "Announce posted. Nested lists.",
     "Post errors.",
     "Cap depth as volume grows.",
     "Rejected: 2k mounted editors.",
     "Reactions?",
     "Cap depth. Lazy editor. Drafts."),
    ("Design a large file uploader", "media",
     "Attach a multi-GB file to a record.",
     "Resume? Virus scan? Concurrent?",
     "Chunk, resume, progress, complete.",
     "Tab stays interactive; honest errors.",
     "2GB; 8MB chunks; 3 concurrent.",
     "Worker hash. Signed URL to storage.",
     "Session, ChunkQueue, Progress.",
     "Create session → PUT chunks → complete.",
     "POST session; PUT; POST complete; GET scan.",
     "IDB chunk progress. File not in Redux.",
     "Idempotent complete. Retry 5xx chunks.",
     "rAF progress. Cap concurrency.",
     "Expired URL: refresh. Scan fail: don’t attach.",
     "Authz; no HTML preview of uploads.",
     "progressbar; cancel.",
     "Long tasks, retries, complete time.",
     "Same design at 10GB if chunked.",
     "Rejected: main-thread hash; BFF streams 2GB.",
     "Multipart vs resumable protocol?",
     "Worker + IDB + signed URLs."),
    ("Design an admin data grid", "data",
     "Filterable table of tens of thousands of rows.",
     "Export? Bulk? Column types?",
     "Sort, filter, select, bulk, saved view.",
     "INP scroll; don’t download the warehouse.",
     "50k hits; 40 visible; 30 columns.",
     "Virtualize rows. Window query.",
     "Grid, Filters, BulkBar.",
     "URL view → GET window → render.",
     "GET rows?cursor&amp;sort; POST bulk; export job.",
     "URL filters. Selection by id.",
     "Invalidate windows after bulk.",
     "Don’t render 50k tr. Debounce filter.",
     "Partial bulk fail per id. Export 403.",
     "Field-level authz. No PII in logs.",
     "Grid APG; say what select-all means.",
     "Scroll INP, bulk errors.",
     "Window + cursor as data grows.",
     "Rejected: offset 0–50000 in the DOM.",
     "Editable cells?",
     "Window + virtualize + honest select-all."),
    ("Design a calendar week view", "work",
     "See and drag events for a week.",
     "Timezones? Recurring? Resources?",
     "Views, create, drag, range query.",
     "INP drag; correct TZ; reserved all-day.",
     "200 events/week; rrules on server.",
     "Positioned chips on a time grid.",
     "Grid, EventChip, Inspector.",
     "GET range → layout → PATCH on drop.",
     "GET /events?from&amp;to; POST/PATCH.",
     "URL date+view. Drag ephemeral.",
     "Prefetch next week. Abort on range change.",
     "Don’t mount 1-min cells as components.",
     "409 overlap. TZ bugs tracked.",
     "ACL; encode titles.",
     "Keyboard create; announce move.",
     "Drag INP, TZ errors.",
     "Server expands recurrence.",
     "Rejected: 5 years of rrules in the client.",
     "Working hours / DST?",
     "Range query + chips + TZ as data."),
    ("Design an email client", "work",
     "Inbox, thread, compose.",
     "Multiple accounts? Offline?",
     "Folders, list, thread, send.",
     "INP j/k; drafts; sandboxed HTML.",
     "100k inbox; 50 window; 200 thread.",
     "Three pane. Virtualize list.",
     "List, Thread, Compose, BodyFrame.",
     "GET list/thread; POST send.",
     "Cursor list. Idempotent send.",
     "URL folder+thread. Drafts IDB.",
     "Debounce mark-read. Abort folder switch.",
     "Iframe sandbox the HTML body.",
     "Send fail keeps compose. Offline queue.",
     "HTML mail XSS. Mailbox authz.",
     "Listbox + labeled compose.",
     "Send, mark-read, INP next.",
     "Window stays; search is another surface.",
     "Rejected: raw HTML in-origin.",
     "Snooze / undo send?",
     "Three pane + sandbox + IDB drafts."),
    ("Design a watch page", "media",
     "Video + comments + related.",
     "SEO? Live? Autoplay?",
     "Player, meta, comments, related.",
     "First frame; isolated player; CLS reserved.",
     "Comments 10k; related 20.",
     "SSR shell. Player island. Comments lazy.",
     "Player, Meta, Comments, Related.",
     "HTML → player → idle comments.",
     "GET video; GET comments cursor; POST comment.",
     "URL v+t. Comments cache separate.",
     "Don’t refetch video when paging comments.",
     "No comment rerender of &lt;video&gt;.",
     "Private 403. Autoplay policy.",
     "Captions; description XSS.",
     "Player keyboard; mention combobox.",
     "Time-to-first-frame, rebuffer, comment errors.",
     "Related is prefetch-limited.",
     "Rejected: one tree that likes rerender the player.",
     "Live chat?",
     "Isolate player. SSR URL. Lazy conversation."),
    ("Design browse rails (Netflix-like)", "media",
     "Rows of titles with spatial keyboard.",
     "Previews? Kids profile?",
     "Rows, title, preview deferred.",
     "INP arrows; LCP first poster; reserved cards.",
     "20×30 titles; ~12 posters on screen.",
     "Window rows and columns. CSR.",
     "Row, Card, Preview lazy.",
     "GET rows → window → focus moves camera.",
     "GET /browse/rows; GET /titles/:id.",
     "URL title. Focus ephemeral.",
     "Prefetch next row only.",
     "Decode near focus. Aspect boxes.",
     "Preview fail → art. Row error isolated.",
     "Catalog authz / region.",
     "Visible focus; no forced autoplay.",
     "LCP poster, INP arrow.",
     "Still windowed at 200 rows.",
     "Rejected: 600 eager images.",
     "Personalization flicker?",
     "Window both axes. Defer trailers."),
    ("Design live trip tracking", "realtime",
     "Map + ETA + driver marker.",
     "Which map SDK? Offline maps?",
     "Map, ETA, states, cancel.",
     "5Hz marker without React storm; battery.",
     "One trip; CDN tiles.",
     "Map island (refs). React chrome.",
     "MapHost, Sheet, Cancel.",
     "GET trip; stream positions to map ref.",
     "GET trip; WS/poll points; POST cancel.",
     "Trip cache. Marker ephemeral in SDK.",
     "Reconnect snapshot. Throttle ETA text 1Hz.",
     "Don’t setState per GPS tick on the sheet tree.",
     "Gap: last point + banner. Cancel 409.",
     "Location sensitivity.",
     "ETA text; cancel labeled.",
     "First map, drops, cancel errors.",
     "Same isolation if 10 riders in a fleet console — then virtualize the list, still island maps.",
     "Rejected: context for lat/lng at 5Hz.",
     "Driver app vs rider app?",
     "Island the map. Throttle React."),
    ("Design a Figma-like canvas (scoped)", "canvas",
     "Pan, zoom, select, move rects, presence.",
     "True multiplayer? 10k nodes?",
     "v1: camera, selection, move, inspector.",
     "Don’t drop frames on pan; inspector INP.",
     "1k nodes; 5 collaborators story.",
     "Scene in a ref. React panels only.",
     "CanvasHost, Inspector, LayerList virtualized.",
     "Snapshot → canvas. PATCH batch on release.",
     "GET file; PATCH nodes; presence WS optional.",
     "URL file+selection. Camera ephemeral.",
     "Inspector not on the 60Hz path.",
     "Hit-test in canvas layer.",
     "If they want CRDT: named engine, not whiteboard math.",
     "Sanitize imported SVG. File ACL.",
     "Panel keyboard; list alternative to canvas select.",
     "FPS, panel INP, op drop.",
     "GL if 10k; SVG if dozens.",
     "Rejected: scene in React context; fake CRDT.",
     "Boolean ops / vectors?",
     "Honesty + isolation. Scope v1."),
    ("Design feature flags in the client", "platform",
     "Boot flags without CLS or flicker.",
     "Experiments? SSR?",
     "Flag provider, chrome flags vs deep flags.",
     "No banner jump; no hydration mismatch.",
     "200 flags; 10 affect chrome.",
     "Inline critical flags in HTML. Rest async.",
     "FlagBoot, useFlag, Experiment slot reserved.",
     "HTML boot → paint → fetch full set.",
     "GET /flags or bootstrap payload.",
     "Memory cache. Don’t localStorage secrets.",
     "SWR full set after paint.",
     "Reserved min-height for experiment chrome.",
     "Fetch fail: defaults you named.",
     "Flags can be an attack surface — least privilege.",
     "Don’t move focus when a flag pops UI.",
     "Mismatch rate, CLS from flags.",
     "Keep chrome flags in the HTML as you grow.",
     "Rejected: /flags after paint that pushes the board down.",
     "Sticky experiments vs flags?",
     "Boot chrome flags with HTML. Reserve space."),
    ("Design a plugin / app host", "platform",
     "Third-party apps on an issue view.",
     "Trust? Who deploys?",
     "Slots, lifecycle, resize, errors.",
     "Host INP stays good; isolate crash.",
     "0–20 iframes; postMessage chatty.",
     "Iframe sandbox + cap. Host bus.",
     "PluginSlot, Bridge, ErrorCard.",
     "Idle-init offscreen. Kill on throw.",
     "Host issues a short-lived capability token, not the session cookie if possible.",
     "Plugin UI state inside iframe.",
     "Don’t cache untrusted HTML in the host origin.",
     "Budget per slot. No sync init in host.",
     "Resize loops: debounce. 3 strikes disable.",
     "CSP frame-src; sandbox; XSS.",
     "Host controls still accessible if plugin dies.",
     "Plugin error rate, host INP vs plugin count.",
     "Cap slots. Don’t federate untrusted JS.",
     "Rejected: in-process eval of vendor JS.",
     "How do you version the bridge?",
     "Iframe + cap + budget. Measure host INP."),
    ("Design i18n + RTL for a large app", "platform",
     "10 locales, RTL, translated UI.",
     "Pseudo-loc? Server strings?",
     "Locale in URL or user profile; catalogs; RTL dir.",
     "No CLS from late fonts/strings; hydration stable.",
     "2k strings; 10 locales; split by route.",
     "dir=rtl on html. Catalogs lazy per route.",
     "I18nProvider, Formatters (dates, numbers).",
     "Boot locale → load catalog → render.",
     "GET /i18n/:locale/:ns.json hashed.",
     "Locale URL or cookie. Catalog cache immutable.",
     "CDN hashed JSON. Don’t block board on unused admin strings.",
     "Reserve font metrics. Avoid concatenated sentences.",
     "Missing key: show key in non-prod, fallback in prod.",
     "Encoded interpolations (XSS).",
     "Lang attribute; don’t disable translation of live regions.",
     "Missing keys, CLS from fonts.",
     "Namespaces per feature as you grow.",
     "Rejected: one 2MB mega-catalog in main.",
     "Pseudo-localization in CI?",
     "Split catalogs. dir on html. Stable hydrate."),
    ("Design search results page", "search",
     "Full search with filters and a result list.",
     "Types? Saved searches? Zero results?",
     "q, filters, sort, pagination, empty.",
     "INP filters; LCP first result; shareable URL.",
     "10M docs; 20 per page; facets.",
     "CSR or SSR first page if public. List virtualize if long cards.",
     "SearchBar, Facets, ResultList, Empty.",
     "URL is the query. GET on change (debounced).",
     "GET /search?q&amp;filters&amp;cursor.",
     "URL all shareable state. Cache by full query key.",
     "Abort in-flight on new q. Don’t offset-deep crawl.",
     "Skeleton matching layout. Cheap cards.",
     "500: retry. Zero: suggestions. 403: hidden types omitted, don’t leak count if that’s policy.",
     "Authz in the index. Encode snippets.",
     "Landmarks; announce result count.",
     "p95 search, zero-result rate, INP facet.",
     "Cursor not deep offset.",
     "Rejected: client-side filter of the corpus.",
     "Typo / synonyms?",
     "URL is the API. Abort. Cursor. Announce count."),
]

def sysdesign() -> str:
    blocks = [_sd(i, *row) for i, row in enumerate(SD, 1)]
    return f'''
<section class="block" id="sysdesign" data-search="Frontend system design practice bank" data-stype="Section">
  <p class="kicker">{len(SD)} timed prompts</p>
  <h2 class="section-title">Design bank</h2>
  <p class="lede">Answer standing up with the 16-step framework. Reveal only after you have boxes and a rejected option. All items are practice questions.</p>
  <div class="card" style="margin-bottom:16px">
    <p>Filter
      <select id="filter-status">
        <option value="all">All statuses</option>
        <option value="not-started">Not started</option>
        <option value="attempted">Attempted</option>
        <option value="solved">Solved</option>
        <option value="review">Review</option>
        <option value="mastered">Mastered</option>
      </select>
      <select id="filter-cat">
        <option value="all">All categories</option>
        <option value="feed">feed</option>
        <option value="work">work</option>
        <option value="search">search</option>
        <option value="realtime">realtime</option>
        <option value="data">data</option>
        <option value="commerce">commerce</option>
        <option value="media">media</option>
        <option value="canvas">canvas</option>
        <option value="platform">platform</option>
      </select>
      <input id="filter-text" type="search" placeholder="Filter titles..." />
    </p>
  </div>
  {''.join(blocks)}
</section>
'''
