from util import esc

TERMS = [
    ('RPS', 'Requests per second.', 'Throughput measure for an API or service.', 'Estimate peak from DAU × actions ÷ seconds.'),
    ('QPS', 'Queries per second.', 'Often DB or search read load.', 'Distinguish read QPS from write TPS in designs.'),
    ('Latency', 'Time one operation takes.', 'p50/p95/p99 — tail matters at scale.', 'Name p99 budget before picking sync fan-out.'),
    ('Throughput', 'Work completed per unit time.', 'RPS, records/sec, bytes/sec.', "Throughput up, latency may rise — Little's Law."),
    ('Availability', 'Fraction of time system works.', 'Often 99.9% = 8.7h downtime/year.', "Define what 'up' means — health check depth."),
    ('Durability', 'Data survives failures.', 'Disk replication, fsync, backups.', 'Redis AOF ≠ Postgres durability story.'),
    ('Replication', 'Copies of data on multiple nodes.', 'Leader/follower, async/sync.', 'Replica lag vs read-your-writes.'),
    ('Partitioning', 'Splitting data by key range or hash.', 'Horizontal scale within one logical DB.', 'Not the same word as network partition.'),
    ('Sharding', 'Partitioning across separate DB instances.', 'Each shard owns key subset.', 'Cross-shard queries become expensive.'),
    ('CAP', 'During partition: pick consistency or availability.', 'Not a one-time architecture choice.', 'Apply per feature — ledger vs badge.'),
    ('Consistency', 'All readers see same data at same time.', 'Strong vs eventual spectrum.', 'Define per action in interview.'),
    ('Eventual consistency', 'Replicas converge if no new writes.', 'Lag bounded in SLA not in math.', 'OK for search index, not for balance.'),
    ('Quorum', 'R+W>N replica overlap.', 'Dynamo-style tunable consistency.', 'Conflicts still need resolution.'),
    ('Leader', 'Primary that accepts writes.', 'Followers replicate.', 'Failover promotion story.'),
    ('Follower', 'Replica that applies leader log.', 'Can serve stale reads.', 'Lag monitoring essential.'),
    ('Cache-aside', 'App loads cache on miss.', 'App invalidates on write.', 'Most common pattern.'),
    ('Write-through', 'Write updates cache and DB together.', 'Consistent cache, slower writes.', 'When read-after-write must hit cache.'),
    ('Write-back', 'Write cache first, flush later.', 'Fast, risk on crash.', 'Rare for authoritative data.'),
    ('TTL', 'Time-to-live on cache entry.', 'Automatic expiry.', 'Jitter TTL to prevent avalanche.'),
    ('Consumer group', 'Kafka consumers sharing partition work.', 'One consumer per partition max.', 'Rebalance pain on scale.'),
    ('Offset', 'Position in Kafka partition log.', 'Commit after process for at-least-once.', 'Reset policy on replay.'),
    ('Partition', 'Ordered log slice in Kafka.', 'Ordering only within partition.', 'Key choice drives hot partition.'),
    ('Idempotency', 'Same request → same effect once.', 'Keys + unique constraints.', 'Required with retries and queues.'),
    ('Backpressure', 'Slow consumer signals producer to slow.', 'Prevent OOM.', 'Pause fetch, drop, or DLQ policy.'),
    ('DLQ', 'Dead letter queue.', 'Poison messages after retries.', 'Alert + safe replay.'),
    ('Circuit breaker', 'Fail fast when dependency sick.', 'Closed/open/half-open.', 'Not a substitute for fixing root cause.'),
    ('SLO', 'Internal reliability target.', 'Error budget derived from it.', 'Product conversation.'),
    ('SLI', 'Measured indicator.', 'Latency, availability, error rate.', 'Pick one SLI per SLO.'),
    ('SLA', 'Contract with customer consequences.', 'Stricter than internal SLO usually.', "Don't confuse with SLO."),
    ('Saga', 'Multi-step transaction with compensations.', 'Avoids 2PC across services.', 'Each step idempotent.'),
    ('Outbox', 'DB table written in same TX as business row.', 'Relay publishes to bus.', 'Dual-write safety.'),
    ('MVCC', 'Multi-version concurrency control.', "Readers don't block writers.", 'Vacuum/bloat in Postgres.'),
    ('Fencing token', 'Monotonic token with lock.', 'Storage rejects stale writer.', 'Redis lock alone insufficient.'),
    ('Consistent hashing', 'Ring mapping keys to nodes.', 'Minimal remapping on add/remove.', 'Virtual nodes for balance.'),
    ('Hot partition', 'Skewed key overloads one shard.', 'Celebrity user problem.', 'Salt key or async fan-out.'),
    ('ACID', 'Atomicity, consistency, isolation, durability.', 'OLTP database guarantee.', 'Which isolation level for transition?'),
    ('BASE', 'Basically available, soft state, eventual.', 'NoSQL tradeoff label.', "Not 'no consistency ever.'"),
    ('Two-phase commit', 'Prepare then commit coordinator.', 'Blocks on coordinator failure.', 'Avoid cross-service 2PC.'),
    ('Paxos', 'Consensus protocol family.', 'Theoretical foundation.', 'Raft is understandable Paxos-like.'),
    ('Raft', 'Leader election + log replication.', 'etcd, Consul use it.', 'Quorum for commit.'),
    ('Load balancer', 'Distributes traffic across backends.', 'L4 vs L7.', 'Health checks and draining.'),
    ('Reverse proxy', 'Front server terminating TLS, routing.', 'nginx, Envoy.', 'Rate limit and auth at edge.'),
    ('CDN', 'Edge cache of static/object bytes.', 'Latency and origin offload.', 'Private vs public cache rules.'),
    ('DNS', 'Name to IP resolution.', 'GeoDNS for routing.', 'TTL affects failover speed.'),
    ('Health check', 'Probe if instance can serve.', 'Liveness vs readiness.', "Don't kill on slow dependency."),
    ('Graceful shutdown', 'Drain then exit.', 'SIGTERM handling.', 'K8s terminationGracePeriodSeconds.'),
    ('Connection pool', 'Reuse DB connections.', 'Bounded concurrency.', 'Size vs Postgres max_connections.'),
    ('Index', 'Structure speeding lookups.', 'B-tree default in Postgres.', 'Left-prefix composite rule.'),
    ('B-tree', 'Balanced tree index.', 'Range queries OK.', 'EXPLAIN ANALYZE verifies use.'),
    ('Covering index', 'Index includes SELECT columns.', 'Index-only scan.', 'Trade write amplification.'),
    ('Normalization', 'Reduce redundancy in schema.', '3NF common default.', 'Denormalize with a story.'),
    ('Denormalization', 'Duplicate data for read speed.', 'Write amplification cost.', 'Event-driven refresh.'),
    ('Foreign key', 'Referential integrity constraint.', 'DB enforces relation.', 'Cascade rules matter.'),
    ('Transaction', 'Atomic unit of work.', 'COMMIT or ROLLBACK.', 'Keep transactions short.'),
    ('Isolation level', 'What anomalies allowed.', 'RC, RR, serializable.', 'Pick for lost-update story.'),
    ('Lost update', 'Concurrent writes overwrite.', 'Version column fix.', 'Classic interview anomaly.'),
    ('Write skew', 'Concurrent reads, disjoint writes.', 'Breaks invariant.', 'Serializable or app lock.'),
    ('Phantom read', 'New rows appear in range re-read.', 'RR helps with indexes.', 'Know examples.'),
    ('Deadlock', 'Transactions wait in cycle.', 'DB detects, aborts one.', 'Lock ordering prevents.'),
    ('Vacuum', 'Postgres reclaims dead tuples.', 'Long TX blocks vacuum.', 'Bloat symptom.'),
    ('WAL', 'Write-ahead log.', 'Durability before page write.', 'Replication streams WAL.'),
    ('Read replica', 'Follower serving reads.', 'Async lag.', 'RYW routing after write.'),
    ('Failover', 'Promote replica on primary death.', 'Automatic vs manual.', 'Split-brain risk.'),
    ('Split-brain', 'Two nodes think they are primary.', 'Quorum prevents.', 'Fencing on storage.'),
    ('Horizontal scaling', 'Add more machines.', 'Shard or partition.', 'vs vertical bigger box.'),
    ('Vertical scaling', 'Bigger machine.', 'Simpler until limit.', 'When before shard?'),
    ('Autoscaling', 'Add/remove instances by metric.', 'CPU, RPS, queue lag.', 'Cooldown prevents flapping.'),
    ('Rate limiting', 'Cap requests per key.', 'Token bucket common.', '429 + Retry-After.'),
    ('Token bucket', 'Burst allowance refill rate.', 'Smooths traffic.', 'Redis implementation pitfalls.'),
    ('Leaky bucket', 'Fixed output rate.', 'Smooths bursts strictly.', 'vs token bucket burst.'),
    ('Sliding window', 'Count in rolling interval.', 'Fairer than fixed window.', 'Redis sorted set trick.'),
    ('Idempotency key', 'Client token for safe retry.', 'Unique constraint stores response.', '409 on body mismatch.'),
    ('Webhook', 'HTTP callback on event.', 'At-least-once delivery.', 'Verify signature + idempotent.'),
    ('Polling', 'Client asks server periodically.', 'Simple, higher latency.', 'Correct when WS not worth it.'),
    ('WebSocket', 'Full-duplex persistent connection.', 'Realtime push.', 'Reconnect + auth + backpressure.'),
    ('SSE', 'Server-sent events one-way stream.', 'HTTP friendly.', 'Auto reconnect built-in.'),
    ('Long polling', 'Hold request until event.', 'Middle ground.', 'Connection count cost.'),
    ('REST', 'Resource-oriented HTTP API.', 'Cacheable GET.', 'Not always CRUD only.'),
    ('gRPC', 'HTTP/2 protobuf RPC.', 'Fast internal APIs.', 'Browser needs gateway.'),
    ('GraphQL', 'Client-shaped query.', 'N+1 and auth complexity.', 'Not auto faster than REST.'),
    ('BFF', 'Backend for frontend.', 'Aggregate + timeout.', 'Can become bottleneck.'),
    ('API gateway', 'Edge routing, auth, limit.', 'Not authz SoT.', 'Version routing.'),
    ('Microservices', 'Independently deployable services.', 'Network failure modes.', 'Refuse until justified.'),
    ('Modular monolith', 'One deploy, module boundaries.', 'Default for many teams.', 'Import lint enforcement.'),
    ('Service mesh', 'Sidecar proxy for mTLS, retry.', 'Operational complexity.', "When plain LB isn't enough."),
    ('mTLS', 'Mutual TLS between services.', 'Identity both ways.', 'Cert rotation automation.'),
    ('OAuth', 'Delegated authorization.', 'BFF + PKCE for SPA.', 'Not authentication alone.'),
    ('JWT', 'Signed claim token.', 'Stateless verification.', 'Revocation hard — short TTL.'),
    ('Session', 'Server-side auth state.', 'HttpOnly cookie common.', 'Store in Redis at scale.'),
    ('RBAC', 'Role-based access control.', 'Role → permissions.', 'Server enforces always.'),
    ('ABAC', 'Attribute-based rules.', 'Fine-grained policy.', 'Harder to audit mentally.'),
    ('Tenant isolation', 'Separate customer data.', 'tenant_id everywhere.', 'RLS + tests for IDOR.'),
    ('SSRF', 'Server fetch of attacker URL.', 'Hit internal metadata.', 'Block private IPs.'),
    ('TLS', 'Encrypt in transit.', 'Terminate at LB or app.', 'HSTS public sites.'),
    ('Encryption at rest', 'Disk/volume encryption.', 'KMS-managed keys.', 'Not same as field-level.'),
    ('Hashing', 'One-way password storage.', 'bcrypt/argon2.', 'Never plaintext passwords.'),
    ('Message queue', 'Async task buffer.', 'Competing consumers.', 'Ordering usually per queue not global.'),
    ('Kafka', 'Distributed commit log.', 'Replay, consumer groups.', 'Not a task queue only.'),
    ('Topic', 'Named stream in Kafka.', 'Split into partitions.', 'Retention policy.'),
    ('Consumer lag', 'Offset behind log end.', 'SLA on processing.', 'Scale consumers ≤ partitions.'),
    ('At-least-once', 'Delivery with duplicates possible.', 'Default with ack+retry.', 'Idempotent consumer.'),
    ('At-most-once', 'May lose messages.', 'Ack before process.', 'Rare except metrics.'),
    ('Exactly-once effect', 'Idempotent + dedupe.', 'Not magic network property.', 'Outbox + inbox pattern.'),
    ('Pub/sub', 'Publishers, subscribers decoupled.', 'Fan-out pattern.', 'Kafka vs Rabbit semantics differ.'),
    ('Fan-out', 'One event → many recipients.', 'Write or read path.', 'Celebrity problem.'),
    ('Fan-in', 'Many sources → one sink.', 'Aggregation.', 'Hot key on counter.'),
    ('Event sourcing', 'Store events not just state.', 'Replay builds state.', 'Complexity cost high.'),
    ('CQRS', 'Separate read/write models.', 'Scale reads differently.', 'Eventual read model lag.'),
    ('Inbox pattern', 'Dedupe incoming messages.', 'Consumer idempotency table.', 'Pair with outbox.'),
    ('Poison message', 'Always fails processing.', 'Goes to DLQ.', 'Fix before replay.'),
    ('Retry storm', 'Clients retry together.', 'Amplifies outage.', 'Jitter + CB + 429.'),
    ('Timeout', 'Max wait for operation.', 'Every outbound call.', 'Shorter than client deadline.'),
    ('Jitter', 'Randomize retry delay.', 'Desynchronizes clients.', 'Full jitter formula.'),
    ('Bulkhead', 'Isolate resource pools.', 'One failure contained.', 'Separate pools per dependency.'),
    ('Degradation', 'Reduced mode when partial fail.', 'Skip search, core OK.', 'Product decision.'),
    ('Chaos engineering', 'Inject failures to learn.', 'Game days.', 'Not random prod breaking.'),
    ('Blue-green deploy', 'Two envs switch traffic.', 'Fast rollback.', 'DB migration compatibility.'),
    ('Canary deploy', 'Small % on new version.', 'Watch metrics.', 'Automated rollback.'),
    ('Rolling deploy', 'Replace instances gradually.', 'Mixed versions briefly.', 'Backward compatible API.'),
    ('Feature flag', 'Runtime behavior toggle.', 'Not authorization.', 'Kill switch cousin.'),
    ('Object storage', 'Blob store S3-like.', 'Pre-signed URLs.', 'Not POSIX filesystem.'),
    ('Pre-signed URL', 'Time-limited auth for object.', 'Client uploads direct.', 'Scope + expiry tight.'),
    ('Multipart upload', 'Large file in parts.', 'Parallel upload resume.', 'Complete with ETag list.'),
    ('Erasure coding', 'Data parity shards.', 'Storage efficiency.', 'vs 3x replication.'),
    ('Inverted index', 'Term → document ids.', 'Search engine core.', 'Analysis/tokenization matters.'),
    ('Full-text search', 'Keyword relevance search.', 'Elasticsearch common.', 'Eventually consistent index.'),
    ('CDC', 'Change data capture.', 'Stream DB changes.', 'Debezium → Kafka.'),
    ('ETL', 'Extract transform load.', 'Batch to warehouse.', "Don't query warehouse from API."),
    ('Data warehouse', 'OLAP analytics store.', 'Columnar.', 'Lag acceptable minutes-hours.'),
    ('OLTP', 'Transactional row store.', 'Short transactions.', 'Issue DB default.'),
    ('OLAP', 'Analytical queries.', 'Aggregates over huge data.', 'Separate from OLTP.'),
    ('Batch processing', 'Periodic bulk jobs.', 'Cheaper for reports.', 'When realtime overkill.'),
    ('Stream processing', 'Continuous computation.', 'Flink, Kafka Streams.', 'Windowing concepts.'),
    ('Lambda architecture', 'Batch + speed layer.', 'Historical + realtime.', 'Complexity tradeoff.'),
    ("Little's Law", 'L = λW concurrency relation.', 'Queue depth insight.', 'More requests, more queue.'),
    ("Amdahl's Law", 'Parallel speedup limit.', 'Serial portion caps gain.', 'Optimize hot serial path.'),
    ('Pareto principle', '80/20 traffic on keys.', 'Cache hot set.', 'Design for skew.'),
    ('Thundering herd', 'Many clients miss cache together.', 'Stampede on expiry.', 'Singleflight fix.'),
    ('Cache stampede', 'Same as thundering herd.', 'Lock on recompute.', 'Probabilistic early refresh.'),
    ('Cache penetration', 'Queries for missing keys.', 'Bloom filter null cache.', 'Attack or bad ids.'),
    ('Cache avalanche', 'Many keys expire together.', 'Jitter TTL.', 'Correlated expiry bad.'),
    ('Bloom filter', 'Probabilistic set membership.', 'May false positive.', 'Reduce DB misses.'),
    ('Singleflight', 'One inflight load per key.', 'Coalesce duplicate misses.', 'Go singleflight pattern.'),
    ('Sticky session', 'Same user → same server.', 'Breaks on scale.', 'Prefer stateless + Redis session.'),
    ('Stateless service', 'No in-memory session.', 'Horizontally scale freely.', 'Default for APIs.'),
    ('Heartbeat', "Periodic I'm-alive signal.", 'Detect dead workers.', 'Lease renewal.'),
    ('Lease', 'Time-bound lock ownership.', 'Expire if holder dies.', 'Fencing on write.'),
    ('Leader election', 'Pick one coordinator.', 'Raft/ZK.', 'Split-brain awareness.'),
    ('Distributed lock', 'Mutual exclusion across nodes.', 'Redis/ZK/etcd.', 'Avoid on hot path if possible.'),
    ('Coordination service', 'ZK/etcd/Consul.', 'Config, locks, discovery.', 'Not a database.'),
    ('Service discovery', 'Find instance addresses.', 'Consul, K8s DNS.', 'Health-aware routing.'),
    ('Correlation ID', 'Trace request across services.', 'Header propagation.', 'Support debugging.'),
    ('Structured logging', 'JSON logs with fields.', 'Queryable.', 'Include tenant, trace id.'),
    ('Metrics', 'Numeric time series.', 'Counters, gauges, histograms.', 'RED/USE methods.'),
    ('Tracing', 'Span tree per request.', 'OpenTelemetry.', 'Tail vs head sampling.'),
    ('Log aggregation', 'Central log search.', 'ELK, Loki.', 'PII scrubbing policy.'),
    ('Error budget', 'Allowed unreliability.', '1 - SLO.', 'Spend on releases.'),
    ('Burn rate', 'Speed of budget consumption.', 'Multi-window alerts.', 'Page on fast burn.'),
    ('Incident', 'User-impacting outage.', 'Postmortem blameless.', 'Action items tracked.'),
    ('Postmortem', 'Structured incident review.', 'Timeline, root cause.', 'Not punishment.'),
    ('Runbook', 'Operational procedure doc.', 'Playbook for alert.', 'On-call quality.'),
    ('On-call', 'Engineer handles alerts.', 'Rotation schedule.', 'SLO-driven paging.'),
    ('Capacity planning', 'Forecast resource needs.', 'Headroom for peak.', 'Load test evidence.'),
    ('Load testing', 'Simulate production traffic.', 'Find breaking point.', 'Before marketing launch.'),
    ('Stress testing', 'Beyond expected load.', 'Find failure mode.', 'Graceful not explode.'),
    ('Soak testing', 'Long duration load.', 'Memory leak find.', 'Hours not minutes.'),
    ('Chaos monkey', 'Random instance termination.', 'Resilience test.', 'Controlled environment first.'),
    ('Multi-AZ', 'Deploy across availability zones.', 'Survive AZ failure.', 'Cross-AZ latency cost.'),
    ('Multi-region', 'Geographic redundancy.', 'DR and latency.', 'Consistency harder.'),
    ('RPO', 'Recovery point objective.', 'Max data loss time.', 'Backup frequency.'),
    ('RTO', 'Recovery time objective.', 'Max downtime.', 'Failover automation speed.'),
    ('Disaster recovery', 'Restore after major failure.', 'Backup, replicate, runbook.', 'Test restores quarterly.'),
    ('Backup', 'Copy data for restore.', 'Point-in-time recovery.', 'Restore drill not optional.'),
    ('Network partition', 'Split cluster communication.', 'CAP scenario.', 'Design partial operation.'),
    ('Split horizon', 'Routing partition behavior.', 'DNS stale.', 'Related to partition.'),
    ('Gossip protocol', 'Peers spread state.', 'Membership, CRDT sync.', 'Eventual cluster view.'),
    ('CRDT', 'Conflict-free replicated datatype.', 'Merge without coordination.', 'Editor/presence use.'),
    ('Vector clock', 'Partial ordering of events.', 'Detect concurrent writes.', 'Causal consistency.'),
    ('Lamport clock', 'Logical timestamp.', 'Ordering not causality full.', 'Simpler than vector.'),
    ('Happens-before', 'Causal ordering relation.', 'Concurrency definition.', 'Explain race bugs.'),
    ('Compare-and-swap', 'Atomic conditional update.', 'Optimistic concurrency.', 'Hardware primitive.'),
    ('Optimistic locking', 'Check version before write.', '409 on conflict.', 'Better than global lock often.'),
    ('Pessimistic locking', 'SELECT FOR UPDATE.', 'Blocks other writers.', 'Deadlock risk.'),
    ('Cursor pagination', 'Keyset on indexed column.', 'Stable deep pages.', 'vs OFFSET cost.'),
    ('Offset pagination', 'LIMIT OFFSET.', 'Simple shallow pages.', 'Deep page slow.'),
    ('N+1 query', 'One query per row in loop.', 'ORM footgun.', 'Batch or join fix.'),
    ('Connection limit', 'Max DB connections.', 'Pool sizing.', 'PgBouncer intermediary.'),
    ('PgBouncer', 'Postgres connection pooler.', 'Transaction pooling mode.', 'Prepared statement caveat.'),
    ('Prepared statement', 'Parsed query plan reuse.', 'SQL injection help.', 'Pooling mode breaks sometimes.'),
    ('SQL injection', 'Untrusted input in SQL.', 'Parameterized queries.', 'Never string concat.'),
    ('NoSQL', 'Non-relational stores family.', 'KV, document, column, graph.', 'Access pattern first.'),
    ('Document store', 'JSON documents Mongo-like.', 'Flexible schema.', 'Joins weak.'),
    ('Key-value store', 'Get/put by key.', 'Redis, Dynamo.', 'Simple scaling.'),
    ('Wide-column store', 'Cassandra/HBase model.', 'Partition + cluster key.', 'Time series friendly.'),
    ('Graph database', 'Nodes and edges native.', 'Traversal queries.', 'Social graph niche.'),
    ('Redis', 'In-memory data structure server.', 'Cache, rate limit, pubsub.', 'Not primary SoT usually.'),
    ('Memcached', 'Simple distributed cache.', 'No persistence richness.', 'Eviction LRU.'),
    ('Elasticsearch', 'Search and analytics engine.', 'Inverted index shards.', 'Not transactional SoT.'),
    ('DynamoDB', 'AWS managed KV/document.', 'Partition key design critical.', 'On-demand vs provisioned.'),
    ('Cassandra', 'Wide-column AP database.', 'Tunable consistency.', 'Write path optimized.'),
    ('MongoDB', 'Document DB.', 'Replica set.', 'When joins rare.'),
    ('Postgres', 'Advanced open-source RDBMS.', 'JSONB, extensions.', 'Default OLTP choice many teams.'),
    ('MySQL', 'Popular RDBMS.', 'Replication modes.', 'InnoDB transactions.'),
    ('NewSQL', 'Distributed SQL Cockroach/Spanner.', 'Horizontal SQL.', 'Global serializable cost.'),
    ('Schema migration', 'Evolve DB structure.', 'Backward compatible steps.', 'Expand-contract pattern.'),
    ('Expand-contract', 'Safe migration pattern.', 'Add column → dual write → switch.', 'Zero downtime goal.'),
    ('Dual write', 'Write two stores.', 'Consistency risk.', 'Outbox better.'),
    ('Read-your-writes', 'User sees own updates.', 'Route to primary or token.', 'Replica lag issue.'),
    ('Monotonic reads', 'Never go backward in time.', 'Sticky to replica.', 'Session consistency.'),
    ('Causal consistency', 'Related ops ordered.', 'Weaker than strong.', 'Vector clocks help.'),
    ('Serializable', 'Strongest isolation.', 'Transactions appear serial.', 'Performance cost.'),
    ('Hinted handoff', 'Temporary write redirect.', 'Dynamo/Cassandra repair.', 'During node failure.'),
    ('Anti-entropy', 'Background replica sync.', 'Mercury repair.', 'Eventually consistent repair.'),
    ('Gossip', 'Epidemic protocol.', 'Cluster membership.', 'See gossip protocol.'),
    ('Merkle tree', 'Hash tree compare data.', 'Efficient sync diff.', 'Cassandra repair.'),
    ('Consistent snapshot', 'Point-in-time backup view.', 'PG snapshot export.', 'Long query caution.'),
    ('Change notification', 'Tell subscribers of updates.', 'LISTEN/NOTIFY, polling.', 'Invalidate cache.'),
    ('Webhook retry', 'Provider resends on non-2xx.', 'Exponential backoff.', 'Idempotent handler.'),
    ('HMAC', 'Message auth code.', 'Verify webhook signature.', 'Shared secret rotation.'),
    ('PII', 'Personally identifiable info.', 'Encrypt, minimize, audit.', 'GDPR delete scope.'),
    ('GDPR', 'EU privacy regulation.', 'Right to erasure.', 'Tenant delete pipeline.'),
    ('Audit log', 'Append-only security record.', 'Who did what when.', 'Tamper-evident storage.'),
    ('Zero trust', 'Verify every request.', 'No flat internal network.', 'mTLS + policy.'),
    ('Least privilege', 'Minimal permissions.', 'IAM roles narrow.', 'Blast radius reduction.'),
    ('Blast radius', 'Scope of failure impact.', 'Bulkhead contains.', 'Multi-tenant isolation goal.'),
    ('Noisy neighbor', 'One tenant hurts others.', 'Rate limit per tenant.', 'Dedicated shard for whale.'),
    ('Multitenancy', 'Many customers one system.', 'tenant_id isolation.', 'Pool vs silo models.'),
    ('Whale tenant', 'Huge customer skew.', 'Dedicated resources.', 'Hot shard mitigation.'),
    ('Cold start', 'New instance slow first requests.', 'Lambda, JVM, cache empty.', 'Warm pool, provisioned concurrency.'),
    ('Provisioned concurrency', 'Pre-warmed Lambda instances.', 'Cost for latency.', 'Spiky traffic pattern.'),
    ('Serverless', 'Function as a unit of deploy.', 'Scale to zero.', 'Cold start and vendor lock.'),
    ('Container', 'Packaged app with deps.', 'Docker OCI.', 'K8s orchestrates.'),
    ('Kubernetes', 'Container orchestration.', 'Pod, service, ingress.', 'Operational learning curve.'),
    ('Pod', 'K8s smallest deploy unit.', 'One or more containers.', 'Shared network namespace.'),
    ('Ingress', 'HTTP routing into cluster.', 'TLS termination.', 'Not same as service mesh.'),
    ('Helm', 'K8s package manager.', 'Templated releases.', 'Chart versioning.'),
    ('Infrastructure as code', 'Terraform/Pulumi.', 'Reproducible envs.', 'State file locking.'),
    ('Immutable infrastructure', 'Replace not patch servers.', 'Golden AMI/image.', 'Deploy new instances.'),
    ('Configuration management', 'Ansible/Chef drift control.', 'Less central now with containers.', 'Still for bare metal.'),
    ('Observability', 'Logs metrics traces unified.', 'Debug unknown unknowns.', 'Three pillars.'),
    ('RED method', 'Rate errors duration.', 'Request service metrics.', 'Microservice monitoring.'),
    ('USE method', 'Utilization saturation errors.', 'Resource monitoring.', 'CPU disk network.'),
    ('Percentile', 'p99 = 99% faster than value.', 'Tail latency SLA.', 'Average hides pain.'),
    ('Histogram', 'Bucketed latency distribution.', 'Prometheus histogram.', 'SLO from histogram.'),
    ('Counter', 'Monotonic increasing metric.', 'Requests total.', 'Rate = derivative.'),
    ('Gauge', 'Point-in-time value.', 'Queue depth.', 'Can go up/down.'),
    ('Cardinality', 'Unique time series count.', 'Explosion from labels.', 'Never label user_id globally.'),
    ('Head sampling', 'Decide trace sample at start.', 'Cheap.', 'May miss slow tail.'),
    ('Tail sampling', 'Keep interesting traces.', 'After complete.', 'Storage efficient debug.'),
    ('OpenTelemetry', 'Vendor-neutral telemetry.', 'SDK + collector.', 'Standardizing traces.'),
    ('Prometheus', 'Pull metrics TSDB.', 'PromQL.', 'Alertmanager pairing.'),
    ('Grafana', 'Dashboard visualization.', 'Many datasources.', 'SLO dashboards.'),
    ('Alert fatigue', 'Too many noisy pages.', 'SLO burn alerts.', 'Actionable only.'),
    ('Synthetic monitoring', 'Probe from outside.', 'Uptime check.', 'Not user experience full.'),
    ('Apdex', 'User satisfaction score.', 'Threshold buckets.', 'Legacy vs histogram SLO.'),
    ('Work queue', 'Tasks for workers.', 'Visibility timeout.', 'Competing consumers.'),
    ('Priority queue', 'Higher priority first.', 'Starvation prevention.', 'Notification tiers.'),
    ('Delayed queue', 'Message available later.', 'Schedule retry.', 'SQS delay seconds.'),
    ('Visibility timeout', 'Message hidden after receive.', 'Redelivery if not ack.', 'Tune to processing time.'),
    ('Message deduplication', 'Drop duplicate ids.', 'SQS FIFO dedupe.', '5 minute window.'),
    ('Ordering key', 'FIFO partition key.', 'Single consumer order.', 'Throughput limit.'),
    ('Schema registry', 'Avro/Protobuf versions.', 'Kafka compatibility.', 'Backward forward rules.'),
    ('Protobuf', 'Binary serialization.', 'gRPC default.', 'Smaller than JSON.'),
    ('Avro', 'Schema-evolving serialization.', 'Kafka common.', 'Writer reader schema.'),
    ('JSON schema', 'Validate JSON shape.', 'API contracts.', 'Lighter than protobuf internal.'),
    ('Contract testing', 'Consumer provider pact.', 'Catch breaking API.', 'CI gate multi-team.'),
    ('Backward compatibility', 'New code reads old data.', 'Additive changes.', 'Expand-contract migrations.'),
    ('Forward compatibility', 'Old code reads new data.', 'Ignore unknown fields.', 'Event evolution.'),
    ('Deprecation', 'Sunset old API path.', 'Version header.', 'Telemetry on usage.'),
    ('API versioning', 'v1 v2 URL or header.', 'Parallel run period.', 'Breaking change policy.'),
    ('Pagination', 'Split large result sets.', 'Cursor preferred scale.', 'Include total count cost.'),
    ('Bulkhead thread pool', 'Dedicated executor.', 'Isolate blocking calls.', 'Node less common than JVM.'),
    ('Event loop', 'Node single-thread dispatch.', 'Non-blocking I/O.', "Don't block with CPU sync."),
    ('Worker thread', 'Node parallel JS thread.', 'CPU offload.', 'Not shared memory by default.'),
    ('Cluster module', 'Node multi-process.', 'Per-core worker.', 'No shared in-proc state.'),
    ('Libuv', 'Node async I/O library.', 'Thread pool for fs.', 'Pool size 4 default.'),
    ('Stream', 'Chunk processing Node.', 'Backpressure pipe.', 'Large file constant memory.'),
    ('Middleware', 'Request pipeline hook.', 'Auth, log, parse.', 'Order matters.'),
    ('ORM', 'Object-relational mapping.', 'Convenience vs SQL control.', 'N+1 risk.'),
    ('Raw SQL', 'Handwritten queries.', 'Performance control.', 'Injection discipline.'),
    ('Migration tool', 'Flyway/Liquibase.', 'Versioned schema.', 'CI applies migrations.'),
    ('Seed data', 'Initial DB rows.', 'Dev/staging.', 'Not production secrets.'),
    ('Fixture', 'Test data setup.', 'Isolated tests.', 'Factory not prod copy.'),
    ('Integration test', 'Real DB or container.', 'Slower, confidence.', 'Testcontainers pattern.'),
    ('Load balancer algorithm', 'Round robin, least conn.', 'Weighted for capacity.', 'Consistent hash sessions.'),
    ('Health endpoint', '/health /ready.', 'LB probe target.', 'Deep vs shallow check.'),
    ('Cold cache', 'Empty after deploy.', 'Miss storm risk.', 'Warm cache job.'),
    ('Warm cache', 'Preload hot keys.', 'Before traffic shift.', 'Canary companion.'),
    ('Dogfooding', 'Use own product internally.', 'Find issues early.', 'Staging realism.'),
    ('SLA violation', 'Miss contractual uptime.', 'Credits/refunds.', 'Stricter than SLO internal.'),
    ('Maintenance window', 'Planned downtime.', 'Less common now.', 'Blue-green preferred.'),
    ('Technical debt', 'Shortcuts accumulating cost.', 'Pay down strategically.', 'ADR documents trade.'),
    ('ADR', 'Architecture decision record.', 'Context decision consequences.', 'Interview why speech.'),
    ('System design interview', 'Open-ended architecture discussion.', 'Clarify scale first.', 'Trade-offs not buzzwords.'),
]


def _slug(term: str) -> str:
    import re
    s = term.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "term"


def glossary() -> str:
    items = []
    seen = {}
    for term, simple, tech, interview in TERMS:
        base = _slug(term)
        sid = base
        n = 2
        while sid in seen:
            sid = f"{base}-{n}"
            n += 1
        seen[sid] = term
        items.append(f"""
<article class="card glossary-item" id="g-{sid}" data-search="{esc(term)}" data-stype="Glossary">
  <h3>{esc(term)}</h3>
  <p><b>Simple.</b> {simple}</p>
  <p><b>Technical.</b> {tech}</p>
  <p><b>Interview.</b> {interview}</p>
</article>""")
    n = len(TERMS)
    return f"""
<section class="block" id="glossary" data-search="Glossary RPS latency CAP Kafka idempotency" data-stype="Section">
  <p class="kicker">{n} terms</p>
  <h2 class="section-title">Backend &amp; System Design Glossary</h2>
  <p class="lede">Searchable definitions at senior density — throughput, consistency, messaging, reliability, and ops. Filter to drill weak areas.</p>
  <p><input id="glossary-filter" type="search" placeholder="Filter glossary…" style="width:100%;max-width:420px;padding:8px 10px;border-radius:8px;border:1px solid var(--border);background:var(--bg-card)" /></p>
  <div class="glossary-grid">{''.join(items)}</div>
</section>
"""
