DAYS = [
  {"n": 1, "title": "System design fundamentals",
   "learn": "Functional vs non-functional requirements, constraints, scalability, reliability, latency vs throughput, cost.",
   "do": "Write FR/NFR/constraints for a URL shortener. List three trade-offs you would name in the first 8 minutes.",
   "verbal": "How do you begin a system-design interview?",
   "rev": "Phase 2: modular monolith vs MFE — one sentence."},
  {"n": 2, "title": "Interview framework (45–60 min)",
   "learn": "16-step framework: clarify → estimate → APIs → data → deep dive → failures → trade-offs.",
   "do": "Timebox 15 min: speak the framework on URL shortener without drawing Kafka.",
   "verbal": "Say three phrases that buy you time and show judgment.",
   "rev": "Yesterday’s NFR list out loud."},
  {"n": 3, "title": "Capacity estimation",
   "learn": "DAU, RPS, peak, read/write, storage/day, bandwidth, cache size. Formulas.",
   "do": "Worked example: 10M users, 1M DAU, 100 req/user/day, 10% peak. Compute average + peak RPS.",
   "verbal": "Walk an interviewer through RPS without a calculator panic.",
   "rev": "1 day ≈ 10^5 seconds. Peak ≈ 2–5× average unless given."},
  {"n": 4, "title": "Estimation drills",
   "learn": "Ten estimation exercises in the Capacity section. Do all of them.",
   "do": "Hide answers. Solve 6 on paper. Compare. Mark weak ones Review.",
   "verbal": "Estimate storage for 5 years of Jira comments.",
   "rev": "Bytes vs bits; UTF-8 comment size assumptions."},
  {"n": 5, "title": "API design — REST",
   "learn": "Resources, cursor pagination, errors, versioning, idempotency keys, authz on the server.",
   "do": "Design issue + comment REST APIs for a Jira-like tracker. Include 409 and cursor examples.",
   "verbal": "Offset vs cursor pagination — when does offset fail?",
   "rev": "Phase 2: URL as public API for filters."},
  {"n": 6, "title": "GraphQL, gRPC, WebSockets, SSE",
   "learn": "When each protocol earns complexity. N+1, BFF, streaming.",
   "do": "ADR paragraph: REST+BFF vs GraphQL for an issue page first paint.",
   "verbal": "Why is GraphQL not automatically better than REST?",
   "rev": "Partial success and timeouts on a BFF."},
  {"n": 7, "title": "Week 1 review + 30-min mock",
   "learn": "Fundamentals + estimation + APIs mixed.",
   "do": "30-min mock: URL shortener or rate limiter. Save debrief.",
   "verbal": "Recite the 16-step framework from memory.",
   "rev": "Mark weak estimation drills."},
  {"n": 8, "title": "Relational design",
   "learn": "PKs, FKs, normalization vs denormalization, multi-tenant tenant_id.",
   "do": "Schema for issues, comments, watchers, permissions. Mark what you would denormalize and why.",
   "verbal": "When is denormalization the senior answer?",
   "rev": "3NF is a default, not a religion."},
  {"n": 9, "title": "Indexes and query planning",
   "learn": "B-tree, composite order, covering, EXPLAIN, why an index is unused.",
   "do": "Write 4 indexes for issue search-by-project+updated. Predict which queries they help.",
   "verbal": "Why might a query be slow despite having an index?",
   "rev": "Left-prefix rule for composite indexes."},
  {"n": 10, "title": "SQL deep dive",
   "learn": "JOIN, GROUP BY, HAVING, CTEs, window functions, latest-row-per-user.",
   "do": "Solve the SQL interview questions in the SQL section before revealing.",
   "verbal": "How do you paginate millions of rows?",
   "rev": "ROW_NUMBER / DISTINCT ON / LATERAL — pick one and defend."},
  {"n": 11, "title": "Transactions and isolation",
   "learn": "ACID, isolation levels, MVCC, lost update, locks.",
   "do": "Issue transition: write the transaction and name the isolation you need.",
   "verbal": "Read committed vs repeatable read for a board move.",
   "rev": "Idempotency key unique constraint as a lock."},
  {"n": 12, "title": "NoSQL and access patterns",
   "learn": "KV / document / column / graph. Partition + sort keys, hot partitions.",
   "do": "Model a Trello card move in Dynamo-style vs Postgres. Name the hot key.",
   "verbal": "When do you refuse NoSQL in an interview?",
   "rev": "Access patterns first, store second."},
  {"n": 13, "title": "Distributed systems fundamentals",
   "learn": "Partial failure, partitions, clocks, duplication, coordination.",
   "do": "List 8 things that are false in a distributed system that are true on one box.",
   "verbal": "Why are distributed systems hard? 3 minutes, no product names.",
   "rev": "There is no now. There is no exactly-once without a story."},
  {"n": 14, "title": "Week 2 review + architecture mock",
   "learn": "SQL + isolation + NoSQL + distributed hardness.",
   "do": "30-min mock: design issue search API + schema only (no Kafka).",
   "verbal": "Explain MVCC as if drawing on a whiteboard.",
   "rev": "Hot partitions."},
  {"n": 15, "title": "Consistency models",
   "learn": "Strong, eventual, read-your-writes, monotonic, causal. Product examples.",
   "do": "Classify: payments, likes, comments, inventory, Jira transition, profile avatar.",
   "verbal": "Where is eventual consistency unacceptable?",
   "rev": "Read-your-writes after a comment submit."},
  {"n": 16, "title": "CAP — not a slogan",
   "learn": "Why partitions happen, CP vs AP, misconceptions.",
   "do": "Draw CAP for: payment ledger vs notification badge vs Jira issue title.",
   "verbal": "Why must real systems tolerate partitions?",
   "rev": "CAP is about a partition, not a lifestyle brand."},
  {"n": 17, "title": "Caching patterns",
   "learn": "Aside, read-through, write-through, write-back. Stampede, penetration, avalanche, hot keys.",
   "do": "Design cache + invalidation for issue detail + board snapshot.",
   "verbal": "What happens when the cache dies at 10× traffic?",
   "rev": "TTL is not a strategy if writes are frequent."},
  {"n": 18, "title": "Redis",
   "learn": "Types, TTL, sessions, rate limit, locks, when Redis is the wrong store.",
   "do": "Pick types for: session, leaderboard, idempotency key, presence set.",
   "verbal": "When is Redis not appropriate?",
   "rev": "Redis is memory + persistence options. It is not your source of truth for issues."},
  {"n": 19, "title": "Message queues",
   "learn": "Ack, visibility, DLQ, at-least-once, ordering. Kafka vs Rabbit vs SQS-like.",
   "do": "Design comment-notification pipeline with retry and DLQ.",
   "verbal": "At-least-once vs exactly-once — what do you actually implement?",
   "rev": "Consumers must be idempotent."},
  {"n": 20, "title": "Kafka / event streaming",
   "learn": "Topic, partition, consumer group, offset, retention, replay, lag.",
   "do": "Partition key for issue events. What ordering do you get? What do you lose?",
   "verbal": "What problem does Kafka solve that a queue does not?",
   "rev": "Replay and multiple consumer groups."},
  {"n": 21, "title": "Week 3 review + 45-min mock",
   "learn": "Consistency + cache + Redis + queues + Kafka.",
   "do": "45-min mock: notification system. Use the 16-step script.",
   "verbal": "Kafka vs queue for this design — say the constraints first.",
   "rev": "Consumer lag investigation."},
  {"n": 22, "title": "Load balancing, proxy, CDN",
   "learn": "L4/L7, algorithms, health checks, sticky sessions, reverse proxy, CDN.",
   "do": "Draw edge → LB → app → DB for a Confluence page. Mark TLS terminate.",
   "verbal": "Why are sticky sessions a scaling smell?",
   "rev": "Hashed assets vs private HTML on a CDN."},
  {"n": 23, "title": "Rate limiting",
   "learn": "Token bucket, leaky, fixed/sliding window. Distributed limiters.",
   "do": "Implement token bucket in TypeScript. Then design for 1M users.",
   "verbal": "Where do you put the limiter — gateway, service, or both?",
   "rev": "Race on Redis INCR without TTL."},
  {"n": 24, "title": "Reliability and fault tolerance",
   "learn": "Timeouts, retries+jitter, circuit breaker, bulkhead, degradation, retry storms.",
   "do": "Write timeout/retry/CB policy for issues API calling search and notifications.",
   "verbal": "How do retries make an outage worse?",
   "rev": "Idempotent GET vs unsafe POST retry."},
  {"n": 25, "title": "Idempotency",
   "learn": "Keys, dedupe stores, unique constraints. Payments, webhooks, uploads.",
   "do": "Node.js idempotent POST /transitions. Name failure if the key store is down.",
   "verbal": "How do you make a payment webhook safe at-least-once?",
   "rev": "Idempotency ≠ exactly-once network."},
  {"n": 26, "title": "Distributed locks",
   "learn": "Why locks are hard, leases, TTL, fencing. When to avoid them.",
   "do": "Redesign “only one worker processes this issue” without a lock if you can.",
   "verbal": "When would you refuse a Redis lock in an interview?",
   "rev": "Lease expiry while work still runs."},
  {"n": 27, "title": "Replication, sharding, partitioning",
   "learn": "Primary/replica, lag, vertical vs horizontal, consistent hashing, hot shards.",
   "do": "Shard key for a multi-tenant Jira. What query becomes impossible?",
   "verbal": "When is sharding premature?",
   "rev": "Read replica lag vs read-your-writes."},
  {"n": 28, "title": "Week 4 review + 45-min mock",
   "learn": "LB + rate limit + reliability + locks + sharding.",
   "do": "45-min mock: file upload for multi-GB files.",
   "verbal": "Recite retry + idempotency + CB in one story.",
   "rev": "Hot shard mitigation."},
  {"n": 29, "title": "Distributed transactions",
   "learn": "2PC costs, sagas, outbox, inbox. Why you avoid 2PC.",
   "do": "Issue create + notify watchers as a saga/outbox. Draw failure of step 2.",
   "verbal": "How do you get dual-write safety without 2PC?",
   "rev": "Transactional outbox."},
  {"n": 30, "title": "Microservices — decision, not fashion",
   "learn": "Monolith vs modular monolith vs services. Ownership, latency, transactions.",
   "do": "ADR: keep issue+comment in one deployable. Split search. Defend.",
   "verbal": "When would you refuse microservices?",
   "rev": "Phase 2 MFE analogy: deploy independence has a cost."},
  {"n": 31, "title": "Service communication + API gateway",
   "learn": "Sync vs async, REST/gRPC/events. Gateway: auth, limit, route, aggregate.",
   "do": "Design a gateway for Jira Cloud-like APIs. What must not live only on the gateway?",
   "verbal": "Why isn’t the gateway your authorization system of record?",
   "rev": "Chatty sync graphs vs events."},
  {"n": 32, "title": "Authentication and authorization",
   "learn": "Sessions, OAuth, JWT, S2S, RBAC/ABAC, tenant isolation.",
   "do": "Threat-model issue permissions. Server enforces; UI hides.",
   "verbal": "JWT in localStorage vs httpOnly cookie — senior answer.",
   "rev": "Phase 2 security table. AuthZ is not a hidden button."},
  {"n": 33, "title": "Observability",
   "learn": "Logs, metrics, traces, SLI/SLO/SLA, correlation IDs. Debug playbooks.",
   "do": "Playbook: “Issue transition is randomly slow.” Ten steps.",
   "verbal": "How do you correlate a user report to a trace?",
   "rev": "SLO is a product conversation, not a Grafana screenshot."},
  {"n": 34, "title": "Security (defensive)",
   "learn": "TLS, secrets, encryption, audit logs, S2S auth. No exploit recipes.",
   "do": "List audit events for issue delete and permission change.",
   "verbal": "What do you encrypt at rest vs in transit, and why keys matter?",
   "rev": "Supply chain + least privilege."},
  {"n": 35, "title": "Week 5 review + 45-min mock",
   "learn": "Services + auth + observability.",
   "do": "45-min mock: search Jira issues.",
   "verbal": "Outbox + trace + tenant isolation in one narrative.",
   "rev": "Weak SLO wording."},
  {"n": 36, "title": "Real-time systems",
   "learn": "WS vs SSE vs long poll. Fan-out, presence, backpressure, reconnect.",
   "do": "Design live board + presence for 50 people on one board.",
   "verbal": "When is polling the correct senior answer?",
   "rev": "Connection fan-out vs event fan-out."},
  {"n": 37, "title": "File storage",
   "learn": "Object store, multipart, pre-signed URL, virus scan, resume, CDN.",
   "do": "Design multi-GB attachment upload connected to a React uploader.",
   "verbal": "Why doesn’t the API server stream the 4GB file?",
   "rev": "Phase 2 frontend uploader + this backend."},
  {"n": 38, "title": "Search",
   "learn": "Inverted index, analysis, shards/replicas, consistency with source-of-truth.",
   "do": "Design “search Jira issues.” Index vs Postgres. Lag story.",
   "verbal": "What is search eventually consistent with?",
   "rev": "Don’t query Elasticsearch for permission source of truth."},
  {"n": 39, "title": "Notification system",
   "learn": "Event → queue → workers → channels. Prefs, dedupe, DLQ, rate limit.",
   "do": "Design email + in-app + push for issue assignment.",
   "verbal": "How do you not email 10k watchers synchronously on transition?",
   "rev": "Fan-out and preference store."},
  {"n": 40, "title": "Data pipelines + analytics",
   "learn": "Ingestion, stream vs batch, warehouse, dashboard freshness.",
   "do": "Design real-time-ish analytics for board throughput. Name lag.",
   "verbal": "When is batch enough for an “analytics” interview?",
   "rev": "Don’t put analytics queries on the OLTP issue DB."},
  {"n": 41, "title": "Node.js backend architecture",
   "learn": "Event loop (Phase 1), pooling, streams, workers, cluster, graceful shutdown.",
   "do": "Sketch a Fastify service: health, config, DI, jobs, shutdown order.",
   "verbal": "What blocks the Node event loop in production?",
   "rev": "Phase 1 event loop + this I/O model."},
  {"n": 42, "title": "Backend exercises",
   "learn": "Implement 4: token bucket, retry+jitter, circuit breaker, idempotent API.",
   "do": "Code them. Then read solutions. Note failure cases.",
   "verbal": "Explain your circuit breaker state machine.",
   "rev": "Closed / open / half-open."},
  {"n": 43, "title": "Atlassian-shaped case studies",
   "learn": "Jira, Confluence, Trello case studies — 45 min each over the day if needed; at least two deep.",
   "do": "Whiteboard Jira without notes, then compare.",
   "verbal": "Multi-tenancy + permissions + search + notifications as one story.",
   "rev": "Customer impact and audit trail."},
  {"n": 44, "title": "60-minute full mock",
   "learn": "Hard design: Slack or YouTube or payments — your weakest.",
   "do": "Record yourself. Score the rubric honestly.",
   "verbal": "Entire 16-step framework, timed.",
   "rev": "Where you went silent or jumped to a library."},
  {"n": 45, "title": "Readiness gate",
   "learn": "Checklist only if you can do it today without this file.",
   "do": "One estimation + one 45-min design + readiness score.",
   "verbal": "Teach CAP, idempotency, outbox, sharding, and Jira design in 15 minutes.",
   "rev": "If score < 85%, schedule another week — do not fake Phase 4."},
]


def plan() -> str:
    cards = []
    for d in DAYS:
        n = d["n"]
        tasks = [
            ("Learn (45 min)", d["learn"]),
            ("Architecture exercise (45 min)", d["do"]),
            ("Verbal (20 min)", d["verbal"]),
            ("Revision (10 min)", d["rev"]),
        ]
        body = []
        for i, (label, text) in enumerate(tasks):
            body.append(
                f'<label class="task"><input type="checkbox" data-id="p3d{n}-t{i}" data-group="checks" />'
                f"<span><b>{label}</b>{text}</span></label>"
            )
        cards.append(f'''<article class="day" id="p3-day-{n}">
  <button type="button" class="day-head">
    <div>
      <h3>Day {n} — {d["title"]}</h3>
      <div class="day-meta">~2 hours · 10 revision · 45 concept · 45 exercise · 20 speaking</div>
    </div>
    <span class="badge badge-pattern">Day {n}</span>
  </button>
  <div class="day-body">{''.join(body)}</div>
</article>''')
    return f'''
<section class="block" id="plan" data-search="45-Day Phase 3 Plan" data-stype="Section">
  <p class="kicker">Schedule</p>
  <h2 class="section-title">45-Day Phase 3 Plan</h2>
  <p class="lede">Six days a week. Review/mock days: 7, 14, 21, 28, 35, 44, 45. If you miss a day, finish the verbal + one exercise — do not double system-design volume.</p>
  <div class="card" style="margin-bottom:16px">
    <h3>Daily cadence</h3>
    <table>
      <tr><th>Time</th><th>Block</th><th>Rule</th></tr>
      <tr><td>10 min</td><td>Revision</td><td>Yesterday’s diagram or a weak checklist item. No new topics.</td></tr>
      <tr><td>45 min</td><td>Concept</td><td>Read the named section. Calculate. Draw.</td></tr>
      <tr><td>45 min</td><td>Exercise</td><td>Design or implement. Speak as if an interviewer is present.</td></tr>
      <tr><td>20 min</td><td>Verbal</td><td>Answer standing up. Then uncover the bank answer.</td></tr>
    </table>
  </div>
  {''.join(cards)}
</section>
'''
