from util import code, topic, diagram, callout, esc

SD = [
    ("easy", "shortener", "URL shortener", "Design a service that maps short codes to long URLs and tracks click counts.", "Custom aliases? TTL on links? Analytics granularity? Abuse/spam?", "100M URLs stored, 10:1 read:write, 10k redirect RPS peak, 99.9% availability.", "Create short URL, redirect, optional expiry, click analytics, rate limit creation.", "LB → stateless API → Redis cache hot codes → Postgres (code, url, user_id, created) → async counter pipeline to column store/rollup.", "Hash vs sequential IDs (guessability); sync vs async click count; SQL vs KV for lookups.", "How prevent short code enumeration? Geo analytics? Collision on custom alias?", "Starting with Kafka for clicks on day one; using sequential IDs without abuse plan."),
    ("easy", "paste", "Paste bin / snippet sharing", "Users paste text, get shareable link, optional burn-after-read and expiry.", "Public vs private? Max size? Syntax highlighting needed? Moderation?", "1M pastes/day, 50KB average, 100:1 read:write, global users.", "Create paste, read by id, expiry, optional password.", "Object storage or Postgres TEXT for body; metadata table; CDN cache public pastes; UUID ids.", "Store body in DB vs S3; cache public reads; encryption at rest for private.", "DMCA takedown flow? View count without hot key?", "Giant paste in single row crashing replicas."),
    ("easy", "rate-limiter", "Distributed rate limiter", "API gateway limit: 100 req/min per user and 10k/min per tenant.", "Burst allowed? Distributed across regions? What response headers?", "1M users, edge + origin enforcement, <5ms overhead.", "Per-key limit, 429 with Retry-After, config per plan tier.", "Token bucket in Redis cluster; local cache for soft limit optional; sync config from control plane.", "Redis vs centralized service; approximate vs exact; sliding vs fixed window.", "Multi-region consistency? Fairness across tenants on shared Redis?", "INCR without TTL; race without Lua script; limit only at app not edge."),
    ("easy", "upload", "Image upload and thumbnail", "Users upload profile/issue attachments; serve resized thumbnails.", "Max size? Virus scan? Direct upload vs through API?", "10k uploads/hour, 5MB avg image, global read.", "Upload, virus scan async, generate 3 sizes, CDN serve.", "Pre-signed POST to object store → metadata in DB → queue worker (sharp) → write derivatives → mark ready.", "API proxy upload vs pre-signed; sync thumbnail vs queue; store originals forever vs lifecycle.", "Resume interrupted upload? Progress webhook? EXIF stripping policy?", "Streaming 100MB through Node without size cap."),
    ("easy", "notifications", "In-app notification bell", "Bell icon, unread count, notification list, mark read.", "Push/email too? Grouping? Retention?", "5M DAU, 20 notifications/user/day avg, 50k peak fan-in/sec on big assign.", "List, unread badge, mark one/all read, deep link.", "Write path: event → queue → notification service → Postgres inbox + Redis unread counter → WebSocket/SSE push.", "Pull vs push; counter in Redis vs count query; infinite scroll vs pages.", "Mute per project? Digest batching? Idempotent assign storm?", "Storing every read in one row without index; WS without reconnect cursor."),
    ("easy", "flags", "Feature flag service", "Runtime toggles per user/tenant/percentage with audit.", "Client-side eval vs server? How fast propagate?", "10k flag reads/sec per service, 500 flags, multi-region.", "Evaluate flag, admin CRUD, gradual rollout, kill switch.", "Flag store (DB) → cache in SDK with TTL → optional streaming updates; eval locally with rules hash.", "Build vs LaunchDarkly; client eval leaks rules; server eval adds latency.", "Consistent rollout across devices? Flag dependency?", "Flags as authorization; no audit on kill switch."),
    ("easy", "scheduler", "Cron / job scheduler", "Schedule recurring and one-off jobs across many workers reliably.", "Exactly-once execution? Timezone? Missed fire during outage?", "100k schedules, 1k executions/sec peak, at-least-once acceptable with idempotent jobs.", "CRUD schedule, trigger, pause, history, lease-based worker pickup.", "Scheduler DB (next_run) → leader election or SKIP LOCKED poll → queue → workers with idempotency key.", "DB polling vs dedicated scheduler (Temporal); clock skew; misfire policy.", "Daylight saving? Long-running job overlap?", "Single cron pod with no failover."),
    ("easy", "chat", "1:1 chat messaging", "Send/receive text messages between two users with history.", "Online presence? Read receipts? Media?", "10M users, 50k concurrent connections peak, 500M messages/day.", "Send, list history, deliver realtime, optional read cursor.", "WS gateway → chat service → message store (partition by conversation_id) → push to recipient connections.", "Cassandra/Dynamo vs Postgres; WS vs long poll; per-user vs per-conversation inbox.", "Message edit/delete? E2E encryption scope?", "Storing all messages in one Postgres table without partition strategy."),
    ("easy", "feed", "Simple news feed (Twitter-like)", "Users post; followers see chronological home timeline.", "Celebrity followers? Ranking or pure time?", "300M users, 500M posts/day, read-heavy.", "Post, follow, home timeline, profile timeline.", "Fan-out on write for normal users; fan-out on read for celebrities; hybrid cache of timelines in Redis.", "Fan-out write vs read; hot user mitigation; eventual consistency of counts.", "Delete post propagation? Feed pagination cursor?", "Fan-out write for user with 50M followers."),
    ("easy", "search", "Basic full-text search", "Search products/issues by keyword with filters.", "Fuzzy? Facets? Instant suggest?", "50M documents, 2k QPS search, index lag OK 30s.", "Query, filter, sort by relevance/recency, highlight.", "CDC/outbox from OLTP → indexer → Elasticsearch cluster → search API with permission filter.", "ES vs Postgres FTS; sync vs async index; permission in index vs filter post-query.", "Reindex zero downtime? Typo tolerance cost?", "Query ES without tenant filter."),
    ("easy", "cache", "Key-value cache layer", "Add cache in front of slow DB for read-heavy API.", "Consistency tolerance? Which endpoints?", "5k RPS read, p99 50ms target, 80% keys account for 95% traffic.", "Cache-aside GET, invalidate on write, TTL fallback.", "App → Redis → Postgres; singleflight on miss; metrics hit rate.", "TTL only vs event invalidation; local vs cluster cache.", "Cold start stampede? Cache aside thundering herd fix?", "Cache permission bitmap forever."),
    ("easy", "saas", "Multi-tenant SaaS signup", "Self-serve signup, tenant provisioning, subdomain per org.", "Free tier limits? Data residency?", "10k new tenants/month, isolate data, custom domain later.", "Register, create tenant, invite users, plan limits.", "Signup API → tenant row + default roles → async provision (schema/row) → DNS/subdomain mapping.", "Pool model vs silo DB per tenant; sync vs async provision.", "Tenant delete GDPR? Cross-tenant admin support?", "Missing tenant_id on one query."),
    ("easy", "poll", "Live polling / voting", "Create poll, users vote once, show live results.", "Anonymous vs authenticated? Close time?", "1M voters, spike on TV event, strong one-vote guarantee.", "Create poll, cast vote, live results, close poll.", "Vote → idempotent insert (poll_id,user_id) unique → counter in Redis → SSE push results.", "DB constraint vs Redis set; approximate vs exact counts.", "Prevent bot votes? Tie handling?", "Check-then-insert race allowing double vote."),
    ("easy", "metrics", "Metrics aggregation service", "Apps emit counters/timers; dashboard queries time series.", "Cardinality limits? Retention?", "100k metrics/sec ingest, 14 day hot, 1 year cold.", "Ingest, tag, query rollup, alert.", "Agents → Kafka → stream processor → TSDB (Prometheus/M3) → Grafana.", "Push vs pull; high cardinality labels; pre-aggregate vs query-time.", "Sampling? Cardinality explosion from user_id tag?", "Unbounded label dimensions."),
    ("medium", "shortener", "URL shortener at scale", "Evolve shortener to 1B links, geo routing, AB variants.", "Same as basic plus fraud detection? Custom domains per tenant?", "1B URLs, 100k RPS redirect, multi-region active-active.", "All basic + custom domain, AB redirect, bot filter.", "GeoDNS → regional edge cache → origin sharded by code hash → async analytics pipeline → data warehouse.", "Global consistency of new codes; edge cache invalidation; analytics loss tolerance.", "Migrate hash algorithm? Dark launch new region?", "Active-active writes without conflict resolution on custom alias."),
    ("medium", "feed", "News feed with ranking", "Home feed ranked by engagement + recency, not pure time.", "Training data? Real-time score update?", "100M DAU, personalized feed, p95 generation <500ms.", "Ranked feed, mute, report, refresh.", "Candidate generation (follow graph + popular) → feature store → ranker → cache per user slice → pagination cursor.", "ML ranker vs heuristic; precompute vs on-demand; filter bubble ethics.", "Cold start new user? Explain rank debug?", "Ranking on every scroll without cache budget."),
    ("medium", "chat", "Group chat (Slack channel)", "Channels, members, history, mentions, threads.", "Max channel size? Search in channel?", "50k workspaces, 10k members max channel, 1M messages/day/workspace peak.", "Join channel, send, mention, thread reply, history pagination.", "Channel service + message store sharded by channel_id + WS fanout via gateway pool + search index async.", "Shard by workspace vs channel; presence separate; edit message propagation.", "Guest access? Export compliance?", "Single WS node without horizontal fanout."),
    ("medium", "search", "Issue search (Jira-like)", "Search issues with JQL-like filters, permissions, facets.", "Index lag SLA? Attachments search?", "50M issues, 5k QPS, complex ACL per issue.", "Query, filter, sort, permission-safe results.", "OLTP Postgres → outbox → indexer with denormalized ACL bitmap → ES → search API joins user caps.", "Denormalize ACL vs query-time filter; index size vs speed.", "Reindex permission change? Saved search alerts?", "Search as SoT for permissions."),
    ("medium", "upload", "Large file upload (multi-GB)", "Resume multipart upload for video/backup files.", "Client direct to cloud? Integrity check?", "Files up to 50GB, 1k concurrent uploads, global.", "Init multipart, upload parts, complete, virus scan, lifecycle to Glacier.", "Pre-signed part URLs → client parallel upload → complete API verifies ETags → metadata DB → async scan.", "Chunk size tradeoff; API vs S3 multipart; cost of retransmit.", "Expired upload cleanup? Bandwidth throttling?", "All bytes through API server."),
    ("medium", "notifications", "Multi-channel notification system", "Email, push, SMS, in-app for same event with preferences.", "Quiet hours? Batching? Unsubscribe compliance?", "10M users, 1M events/hour peak, CAN-SPAM/GDPR.", "Template per channel, prefs, dedupe, delivery status.", "Event → router → per-channel queues → workers → provider webhooks → delivery log.", "Sync vs async; priority queues; idempotent provider calls.", "Fan-out 10k watchers on one issue? A/B template test?", "Sending email synchronously in issue API."),
    ("medium", "scheduler", "Distributed workflow engine", "DAG jobs with dependencies, retries, visibility (Temporal-like lite).", "Human approval steps? Version workflows?", "50k workflows/day, steps may run hours, at-least-once steps.", "Define DAG, schedule, retry policy, status API.", "Workflow state in DB → task queue per activity → workers with heartbeats → saga compensations.", "Orchestrator DB vs event choreography; long poll vs push tasks.", "Stuck workflow detection? Upgrade running workflow definition?", "No idempotent activities with retries."),
    ("medium", "flags", "Dynamic config + experiments", "Flags plus A/B experiments with metrics attribution.", "Bayesian vs frequentist? Holdout groups?", "Same as flags + exposure events 50k/sec.", "Assign variant, log exposure, compute lift, guardrails.", "Assignment hash sticky per user → exposure event stream → metrics join in warehouse.", "Server vs client assignment; peeking; interaction effects.", "Stop bad experiment fast? Sample ratio mismatch?", "Changing variant mid-session without stickiness."),
    ("medium", "saas", "Multi-tenant B2B SaaS platform", "Many orgs, RBAC, billing, data isolation, SSO.", "Enterprise SSO? Per-tenant encryption keys?", "100k tenants, 500 users/tenant max, SOC2.", "Tenant admin, roles, audit log, usage metering, SSO SAML.", "Tenant catalog + shard routing + RLS + billing integration + audit append-only log.", "Pool vs silo; row-level vs schema per tenant; centralized billing.", "Tenant export/delete? Cross-region tenant migration?", "AuthZ only in frontend."),
    ("medium", "editor", "Collaborative document editor", "Google Docs-lite: concurrent edits, presence, version history.", "OT vs CRDT? Offline?", "100 concurrent editors max/doc, 10k docs active.", "Edit, presence cursors, comment, revert version.", "WS room per doc → CRDT/OT server or peer relay → periodic snapshot to object store → version list metadata.", "CRDT memory growth; central server vs P2P; conflict on title.", "Offline merge? Import/export docx?", "Last-write-wins on rich text."),
    ("medium", "payments", "Payment processing flow", "Checkout, authorize, capture, refund, webhook from provider.", "PCI scope? Multi-currency?", "1k TPS peak, strong consistency on ledger.", "Create intent, confirm, webhook reconcile, refund idempotent.", "API → payment provider tokenization → ledger DB (double-entry) → outbox webhooks → reconciliation job.", "Sync capture vs async; store cards or not; saga on partial failure.", "Dispute chargeback? Idempotent webhook replay?", "Updating balance without transaction."),
    ("medium", "analytics", "Real-time analytics dashboard", "Product metrics dashboard near-real-time (minutes lag).", "Exactly-once counts? Ad-hoc SQL?", "1M events/min ingest, dashboard 5 min freshness.", "Ingest events, aggregate, query by dimensions.", "Kafka → Flink/Spark streaming → rollup tables → OLAP (ClickHouse) → query API.", "Stream vs batch; lambda architecture; preaggregate vs raw.", "Late events? Backfill historical?", "Querying OLTP for dashboards."),
    ("medium", "api", "API gateway / BFF", "Single entry for mobile/web composing 5 backend services.", "GraphQL vs REST BFF? Auth termination?", "20k RPS, p99 300ms, partial success OK on non-critical parts.", "Route, auth, rate limit, aggregate, timeout per leg.", "Gateway → parallel calls with deadlines → merge JSON → cache fragments.", "BFF per client vs universal; cache at gateway danger.", "Circuit break one dependency? Version routing?", "Gateway as only authz layer."),
    ("medium", "storage", "Distributed object storage", "S3-like store blobs with durability 11 nines.", "Consistency model? Listing performance?", "PB scale, 100k PUT/sec.", "PUT/GET/List, versioning, lifecycle.", "Metadata service + erasure-coded chunks across AZs + CDN integration.", "Consistency listing; small object overhead; erasure vs replication.", "Cross-region replication lag? Consistency on overwrite?", "Single disk per object."),
    ("medium", "stream", "Live video streaming (HLS)", "Ingest RTMP, transcode, deliver HLS globally.", "Live vs VOD? DRM?", "10k concurrent streams, 5s latency target.", "Ingest, transcode ladder, segment, CDN deliver.", "Ingest → transcode farm → segment to object store → CDN origin shield → player.", "Latency vs segment size; peer CDN vs single; cost at scale.", "Failover ingest? Adaptive bitrate?", "Serving unsegmented giant file."),
    ("medium", "marketplace", "Two-sided marketplace", "Buyers, sellers, listings, search, payments, reviews.", "Escrow? Dispute?", "1M listings, geo search, payment split.", "List item, search, checkout, payout seller, review.", "Listing service + search + order saga + payment escrow + review moderation queue.", "Search geo; payout timing; fraud scoring async.", "Inventory oversell? Chargeback handling?", "Double booking without transaction."),
    ("hard", "feed", "Global social feed at Twitter scale", "Celebrity problem, worldwide, mixed ranking.", "Compliance per country? Delete propagation SLA?", "500M DAU, 400M posts/day, read 100:1.", "All medium feed + delete everywhere, mute block, trends.", "Hybrid fan-out, cache layers, graph service, ranker fleet, multi-region read paths.", "CAP on timeline; cache coherency; hot path cost.", "Failover region read-only? Consistent retweet count?", "Single Postgres for all timelines."),
    ("hard", "chat", "WhatsApp-scale messaging", "E2E optional, delivery receipts, groups, media.", "E2E key management? Multi-device?", "2B users, low latency global, offline delivery.", "Send offline queue, group fanout, media via CDN encrypted.", "Message queue per device + mailbox store + WS/push + MIM media.", "Fanout cost; key rotation; metadata privacy.", "Group size 256 sync? Backup messages?", "Central readable message store for E2E product."),
    ("hard", "search", "Google-scale web search", "Crawl, index, rank billions of pages.", "Freshness vs cost? Spam?", "Billions docs, 100k QPS.", "Crawl, index shards, PageRank-like rank, query.", "Crawler fleet → link graph → inverted index sharded → top-k aggregation → spellcheck.", "Index sharding; crawl politeness; personalized rank.", "Index update without full rebuild? Safe search?", "Single inverted index machine."),
    ("hard", "payments", "Global payment ledger", "Double-entry ledger, multi-currency, audit, reconciliation.", "Regulatory reporting? Zero data loss?", "10k TPS writes, ACID, 7 year retention.", "Post entries, balances, FX, daily reconcile with banks.", "Ledger DB serializable + immutable journal + outbox to external rails + recon batch.", "Strong consistency vs availability; shard ledger by account.", "Hot account (celebrity wallet)? Prove balance never negative?", "Float balance in Redis."),
    ("hard", "saas", "Salesforce-scale multi-tenant CRM", "Massive tenants, custom objects, queries, isolation.", "Custom schema per tenant? Query language?", "Millions tenants, metadata-driven schema.", "CRUD dynamic entities, query, reports, API limits.", "Metadata catalog + universal table or pod per whale + query planner + heavy caching.", "Metadata explosion; noisy neighbor; upgrade migrations.", "Cross-object query index? Sandbox copy tenant?", "One-size relational schema without metadata layer."),
    ("hard", "editor", "Figma-like realtime collaboration", "CRDT on canvas, sub-100ms sync, huge documents.", "Millions of objects? Undo history?", "50 editors, complex scene graph.", "Multiplayer cursors, object CRDT, export.", "WS room + CRDT server authoritative merge + snapshot chunks + S3 history.", "CRDT size; server memory; conflict on delete.", "Version fork? Permission on layer?", "Broadcast full doc every edit."),
    ("hard", "stream", "Netflix-scale video on demand", "Catalog, encode, CDN, resume playback, recommendations.", "4K bitrate? Offline download?", "200M subscribers, global CDN.", "Browse, play, resume, recommend, encode new titles.", "Microservices + Cassandra + EVCache + Open Connect CDN + ML recs offline.", "CDN vs origin; encode pipeline batch; regional catalog.", "Regional license blackout? A/B artwork?", "Single origin for all video bytes."),
    ("hard", "infra", "Distributed tracing platform", "Ingest spans from 10k services, query traces, retention.", "Head vs tail sampling? PII in spans?", "1M spans/sec, 7 day hot storage.", "Ingest, index by trace_id, query UI, alert on error traces.", "Agents → Kafka → column store (Tempo/Jaeger) + object store for long retention.", "Sampling bias; cardinality; cost vs debuggability.", "Critical path analysis? Tail latency debugging?", "100% unsampled production forever."),
    ("hard", "database", "Design a distributed SQL database", "Spanner/Cockroach-like: SQL across regions, survivable partitions.", "TrueTime? Serializable default?", "Global tables, 50k TPS, RPO near zero.", "SQL, horizontal scale, consistent reads option.", "Range sharding + Raft per range + clock sync + transaction coordinator.", "Latency vs strict serializable; cost of global indexes.", "Split hot range? Online schema change?", "2PC across all microservices as 'distributed SQL'."),
    ("hard", "queue", "Global task queue (SQS-like)", "Durable queue, visibility timeout, DLQ, multi-region.", "Ordering? Exactly-once illusion?", "1M messages/sec, many queues.", "Send, receive, ack, delay, DLQ redrive.", "Log segments + broker shards + visibility index + geo-replication async.", "Visibility timeout tuning; long poll; fair scheduling.", "Message size limit? FIFO cost?", "In-memory queue claiming durable."),
    ("hard", "gaming", "Multiplayer game matchmaking + state", "Match players, run game room, anti-cheat signals.", "Dedicated server vs P2P? Tick rate?", "100k concurrent matches, 50ms tick.", "Queue, match ELO, room host, state sync.", "Matchmaker → allocate game server → UDP/state sync → replay for cheat detection.", "Authoritative server vs client prediction; regional pools.", "Disconnect reconnect? Smurf detection?", "Trust client hit detection."),
    ("hard", "maps", "Uber-like ride matching", "Riders, drivers, realtime location, dispatch, pricing.", "Surge? Safety?", "1M active drivers, sub-second dispatch in city.", "Request ride, match nearest, track trip, pay.", "Geospatial index (H3/S2) + dispatch service + trip state machine + location stream Kafka.", "Geo shard by city; consistent trip state; surge pricing calc.", "Driver ghost locations? Payment failure mid-trip?", "Linear scan all drivers globally."),
]


def _sd(i, level, cat, title, prompt, clarify, scale, req, arch, trade, follow, mistakes):
    hid = f"sd-{i}"
    return f"""
<article class="problem" id="{hid}" data-pid="{hid}" data-level="{level}" data-cat="{cat}" data-search="{esc(title)}" data-stype="System design" data-mock="1" data-filterable>
  <div class="meta-row"><span class="badge badge-pattern">{level}</span><span class="chip">{cat}</span></div>
  <h3>{i}. {esc(title)}</h3>
  <p><b>Prompt.</b> {prompt}</p>
  <p><b>Clarifying questions.</b> {clarify}</p>
  <p><b>Expected scale.</b> {scale}</p>
  <p><b>Requirements.</b> {req}</p>
  <p><button type="button" class="toggle-btn" data-toggle="{hid}-a">Reveal architecture</button>
     <button type="button" class="toggle-btn" data-complete="designs" data-cid="{hid}">Mark complete</button></p>
  <div class="reveal" id="{hid}-a">
    <p><b>Architecture.</b> {arch}</p>
    <p><b>Trade-offs.</b> {trade}</p>
    <p><b>Follow-ups.</b> {follow}</p>
    <p><b>Common mistakes.</b> {mistakes}</p>
  </div>
  <div class="status-btns">
    <button type="button" data-status="not-started">Not Started</button>
    <button type="button" data-status="attempted">Attempted</button>
    <button type="button" data-status="solved">Solved</button>
    <button type="button" data-status="review">Review</button>
    <button type="button" data-status="mastered">Mastered</button>
  </div>
</article>"""


def sysdesign() -> str:
    easy = sum(1 for r in SD if r[0] == "easy")
    med = sum(1 for r in SD if r[0] == "medium")
    hard = sum(1 for r in SD if r[0] == "hard")
    cats = sorted({r[1] for r in SD})
    cards = [_sd(i, *row) for i, row in enumerate(SD, 1)]
    cat_opts = "".join(f'<option value="{c}">{c}</option>' for c in cats)
    n = len(SD)
    return f"""
<section class="block" id="sysdesign" data-search="System Design Question Bank practice" data-stype="Section">
  <p class="kicker">{n} practice questions</p>
  <h2 class="section-title">System Design Question Bank</h2>
  <p class="lede">Senior system-design <b>practice</b> prompts — not official questions from any employer. Clarify scale first, then draw the critical path. Use status buttons for spaced repetition.</p>
  {callout("Lead with users, scale, and the critical path. Name two alternatives you rejected. Do not open with 'we'll use Kafka' before requirements.")}
  <div class="tabs" data-tabs="sdq">
    <button type="button" class="tab active" data-tab="all">All ({n})</button>
    <button type="button" class="tab" data-tab="easy">Easy ({easy})</button>
    <button type="button" class="tab" data-tab="medium">Medium ({med})</button>
    <button type="button" class="tab" data-tab="hard">Hard ({hard})</button>
  </div>
  <div class="filters">
    <select id="filter-status">
      <option value="all">All statuses</option>
      <option value="not-started">Not started</option>
      <option value="attempted">Attempted</option>
      <option value="solved">Solved</option>
      <option value="review">Review</option>
      <option value="mastered">Mastered</option>
      <option value="incomplete">Incomplete</option>
      <option value="complete">Complete</option>
    </select>
    <select id="filter-cat">
      <option value="all">All categories</option>
      {cat_opts}
    </select>
    <input id="filter-text" type="search" placeholder="Filter designs…" />
  </div>
  {''.join(cards)}
</section>
"""
