DAYS = [
  {"n": 1, "title": "How to learn + the role",
   "learn": "How to learn and The role. AI engineer vs ML engineer vs research.",
   "do": "Write 8 lines: a product you know, where a model would help, what must not be automated.",
   "verbal": "What does an AI engineer own that a backend engineer does not?",
   "rev": "None — day 1."},
  {"n": 2, "title": "Map of AI",
   "learn": "Rules, classical ML, deep learning, generative AI. What each is for.",
   "do": "Label 10 product features as rules / ML / LLM / RAG. Then the Map gym.",
   "verbal": "When is an if-statement better than a model?",
   "rev": "The role in one minute."},
  {"n": 3, "title": "Python for AI",
   "learn": "Virtualenv, numpy shapes, pandas splits, typing a dataset.",
   "do": "Type the numpy snippets. Do the Python gym (5+).",
   "verbal": "What does a tensor’s shape [B, T, D] mean?",
   "rev": "Map of AI."},
  {"n": 4, "title": "Math you need",
   "learn": "Vectors, dot product, gradient as ‘which way decreases loss’, probability vs likelihood.",
   "do": "Compute a 2-d dot product by hand. Do the Math gym.",
   "verbal": "What is a loss function in one sentence?",
   "rev": "Numpy broadcasting in one example."},
  {"n": 5, "title": "Data and leakage",
   "learn": "Train / val / test. Time splits. Leakage. Label noise.",
   "do": "Find the leak in the three examples. Data gym.",
   "verbal": "Why is a random split illegal on a time series?",
   "rev": "Gradient intuition."},
  {"n": 6, "title": "Supervised learning",
   "learn": "Features → label. Underfit / overfit. The learning loop.",
   "do": "Draw the loop on paper. Supervised gym (4+).",
   "verbal": "What is the job of the validation set?",
   "rev": "Leakage examples."},
  {"n": 7, "title": "Core models",
   "learn": "Linear, logistic, trees, forests, boosting — when each wins.",
   "do": "For 6 product problems pick a first model and say why. Models gym.",
   "verbal": "Why start with logistic regression before a neural net?",
   "rev": "Overfitting picture."},
  {"n": 8, "title": "Metrics",
   "learn": "Accuracy trap. Precision, recall, F1, AUC, calibration. Cost of errors.",
   "do": "Pick metrics for spam, cancer screen, and search. Metrics gym.",
   "verbal": "When is accuracy a lie?",
   "rev": "Tree vs linear."},
  {"n": 9, "title": "Features and regularization",
   "learn": "Scaling, one-hot, target leak features. L1/L2, early stop.",
   "do": "Name three leaky features in a ‘will churn’ dataset. Features gym.",
   "verbal": "What does L2 do to large weights?",
   "rev": "Precision vs recall."},
  {"n": 10, "title": "Week 2 review + 30-min mock",
   "learn": "Classical ML end-to-end.",
   "do": "Timed mock: pick a metric + a first model for a prompt. Save debrief.",
   "verbal": "Teach train/val/test and leakage in 90 seconds.",
   "rev": "Weak gym items."},
  {"n": 11, "title": "Neural nets",
   "learn": "Neuron, layer, activation, backprop as blame assignment.",
   "do": "Implement a 1-layer forward pass in numpy. NN gym.",
   "verbal": "Why do we need a non-linearity?",
   "rev": "Regularization."},
  {"n": 12, "title": "CNNs and sequences",
   "learn": "Local patterns, parameter sharing. RNN limits. Why we moved on.",
   "do": "CNN/sequence gym. Sketch a 3×3 conv on a 5×5 grid.",
   "verbal": "What problem do RNNs have on long text?",
   "rev": "Activation functions."},
  {"n": 13, "title": "Attention and transformers",
   "learn": "Q/K/V, self-attention, encoder/decoder, positional info.",
   "do": "Trace attention on a 3-token toy. Transformer gym.",
   "verbal": "What does a token attend to?",
   "rev": "CNN vs fully connected."},
  {"n": 14, "title": "Embeddings and vectors",
   "learn": "Meaning as geometry. Similarity. Index vs exact search.",
   "do": "Embeddings gym. Write cosine similarity.",
   "verbal": "Why can ‘king − man + woman’ be a joke and still teach something?",
   "rev": "Self-attention one sentence."},
  {"n": 15, "title": "LLM landscape",
   "learn": "Pretrain, SFT, preference. API vs open weights. Context window.",
   "do": "LLM gym. For 4 tasks pick API vs local and say the constraint.",
   "verbal": "What is a context window, really?",
   "rev": "Cosine similarity."},
  {"n": 16, "title": "Prompting",
   "learn": "System vs user, few-shot, schema, tools, failure modes.",
   "do": "Rewrite a vague prompt into a contract. Prompt gym.",
   "verbal": "Why is ‘be a helpful assistant’ not a spec?",
   "rev": "SFT vs pretrain."},
  {"n": 17, "title": "RAG",
   "learn": "Chunk, embed, retrieve, generate, cite, refuse.",
   "do": "Design chunking for a 40-page policy PDF. RAG gym.",
   "verbal": "What does RAG not fix?",
   "rev": "Structured output."},
  {"n": 18, "title": "RAG failure modes",
   "learn": "Bad chunks, stale index, lost citations, prompt stuffing.",
   "do": "List 6 RAG bugs and the test that would catch each.",
   "verbal": "How do you know the model used the retrieved text?",
   "rev": "Chunk size trade-off."},
  {"n": 19, "title": "Fine-tuning",
   "learn": "When LoRA helps. When it is wasted money. Data quality.",
   "do": "Fine-tune gym. Write a 10-row SFT example set for a tone task.",
   "verbal": "Prompt vs RAG vs fine-tune — the decision tree.",
   "rev": "RAG cite/refuse."},
  {"n": 20, "title": "Agents",
   "learn": "Tools, loops, memory, stop conditions. When not to agent.",
   "do": "Agent gym. Spec 3 tools for a support bot and a halt rule.",
   "verbal": "What is the difference between a chain and an agent?",
   "rev": "LoRA in one sentence."},
  {"n": 21, "title": "Week 3 review + 45-min mock",
   "learn": "GenAI path: prompt → RAG → agent.",
   "do": "45-min: design a doc Q&A. Save debrief.",
   "verbal": "Draw the RAG box diagram from memory.",
   "rev": "Agent halt conditions."},
  {"n": 22, "title": "Evaluation",
   "learn": "Golden sets, raters, LLM-as-judge limits, online metrics.",
   "do": "Write 8 golden questions for a HR policy bot. Eval gym.",
   "verbal": "Why is ‘the demo looked good’ not an eval?",
   "rev": "Doc Q&A design."},
  {"n": 23, "title": "Safety",
   "learn": "PII, secrets, copyright, over-refusal, human escalation.",
   "do": "Safety gym. Threat-model a chatbot that can see tickets.",
   "verbal": "What must never go into a prompt log?",
   "rev": "Golden set design."},
  {"n": 24, "title": "Serving and cost",
   "learn": "Tokens, batching, streaming, cache, reserved vs on-demand.",
   "do": "Estimate cost for 1M chats/month with a back-of-envelope. Serve gym.",
   "verbal": "What is a token in billing vs in the model?",
   "rev": "PII in logs."},
  {"n": 25, "title": "MLOps",
   "learn": "Version data, prompts, indexes, models. Drift. Rollback.",
   "do": "MLOps gym. Write a rollback plan for a bad prompt deploy.",
   "verbal": "What do you version besides weights?",
   "rev": "Cost envelope."},
  {"n": 26, "title": "AI system design",
   "learn": "The 12-step design loop. v1 vs fantasy.",
   "do": "Speak the 12 steps on ‘design ChatGPT for our wiki’.",
   "verbal": "What do you cut first at 30 minutes?",
   "rev": "Drift types."},
  {"n": 27, "title": "Practical studies 1",
   "learn": "Classifier, search rank, RAG support bot.",
   "do": "Complete those three practical studies.",
   "verbal": "Map one study to a product you have used.",
   "rev": "12-step list."},
  {"n": 28, "title": "Practical studies 2",
   "learn": "Agent with tools, eval harness, cost incident.",
   "do": "Complete those three studies.",
   "verbal": "How would you halt a looping agent?",
   "rev": "RAG study."},
  {"n": 29, "title": "Practical studies 3",
   "learn": "Fine-tune vs prompt, multimodal intake, offline+online eval.",
   "do": "Complete remaining studies.",
   "verbal": "When is a vision model the wrong first step?",
   "rev": "Eval harness."},
  {"n": 30, "title": "Week 4 review + 60-min mock",
   "learn": "Production + a full design.",
   "do": "60-min: support bot with RAG + tools + eval. Save debrief.",
   "verbal": "Close with v1, rejects, metrics, a question.",
   "rev": "Weak studies."},
  {"n": 31, "title": "Exercise bank — foundations",
   "learn": "Mixed bank, foundation tags.",
   "do": "Solve 8 foundation/classical items standing up.",
   "verbal": "Leakage + metric in 60 seconds.",
   "rev": "Due today."},
  {"n": 32, "title": "Exercise bank — genAI",
   "learn": "RAG, prompt, agent, eval items.",
   "do": "Solve 8 genAI items. Speak the fail path each time.",
   "verbal": "Prompt vs RAG vs fine-tune on a new prompt.",
   "rev": "Failed items."},
  {"n": 33, "title": "Exercise bank — production",
   "learn": "Cost, serve, MLOps, design.",
   "do": "Solve 6 production items.",
   "verbal": "Rollback story.",
   "rev": "Cost math."},
  {"n": 34, "title": "Q&A bank 1",
   "learn": "Interview Q&A, fundamentals + ML.",
   "do": "Answer 20 Qs standing up.",
   "verbal": "What is overfitting?",
   "rev": "Weak Qs."},
  {"n": 35, "title": "Q&A bank 2",
   "learn": "LLM, RAG, agents, safety.",
   "do": "Answer 20 Qs. Mark complete only if you can teach the short answer.",
   "verbal": "What is an embedding?",
   "rev": "Judge-model limits."},
  {"n": 36, "title": "Q&A bank 3",
   "learn": "Production and judgment.",
   "do": "Answer remaining Qs you have not touched.",
   "verbal": "API vs self-host.",
   "rev": "Safety Qs."},
  {"n": 37, "title": "Mixed timed set",
   "learn": "Random mock × 2.",
   "do": "Two 45-min mocks. Different categories.",
   "verbal": "What leaked time?",
   "rev": "Checklist first pass."},
  {"n": 38, "title": "Teach-back: ML",
   "learn": "Teach data + model + metric to a rubber duck.",
   "do": "One page: leakage, logistic vs tree, one metric.",
   "verbal": "No slides. 8 minutes.",
   "rev": "Readiness gaps."},
  {"n": 39, "title": "Teach-back: GenAI",
   "learn": "Teach transformer-lite + RAG + eval.",
   "do": "One page with a box diagram.",
   "verbal": "8 minutes. Name two rejected designs.",
   "rev": "RAG bugs."},
  {"n": 40, "title": "Teach-back: production",
   "learn": "Teach cost, logs, rollback, safety.",
   "do": "Incident table: symptom → check → action.",
   "verbal": "5-minute on-call story.",
   "rev": "Serving."},
  {"n": 41, "title": "Full loop",
   "learn": "One 60-min design + 15-min Q&A.",
   "do": "Save both debriefs. Honest scores.",
   "verbal": "I don’t know — then the next experiment.",
   "rev": "Due today only."},
  {"n": 42, "title": "Gate",
   "learn": "Readiness checklist. Honest.",
   "do": "Light revision only after the checklist.",
   "verbal": "20-minute tour: data → model → RAG → eval → serve.",
   "rev": "Due today only."},
]


def plan() -> str:
    cards = []
    for d in DAYS:
        n = d["n"]
        body = [
            f'<label class="task"><input type="checkbox" data-id="d{n}-rev" data-group="checks" /><span><b>Revision</b> {d["rev"]}</span></label>',
            f'<label class="task"><input type="checkbox" data-id="d{n}-learn" data-group="checks" /><span><b>Concept</b> {d["learn"]}</span></label>',
            f'<label class="task"><input type="checkbox" data-id="d{n}-do" data-group="checks" /><span><b>Exercise</b> {d["do"]}</span></label>',
            f'<label class="task"><input type="checkbox" data-id="d{n}-verbal" data-group="checks" /><span><b>Verbal</b> {d["verbal"]}</span></label>',
        ]
        cards.append(f'''<article class="day" id="ai-day-{n}">
  <button type="button" class="day-head">
    <div>
      <h3>Day {n} — {d["title"]}</h3>
      <div class="day-meta">~2 hours · read, then make something small</div>
    </div>
    <span class="badge badge-pattern">Day {n}</span>
  </button>
  <div class="day-body">{''.join(body)}</div>
</article>''')
    return f'''
<section class="block" id="plan" data-search="42-Day AI Engineer plan" data-stype="Section">
  <p class="kicker">Schedule</p>
  <h2 class="section-title">42-Day from-scratch plan</h2>
  <p class="lede">Six days a week is enough. If you miss a day, finish the concept + one gym item — do not binge three chapters. GPU optional: most of this course is thinking and small Python.</p>
  <div class="card" style="margin-bottom:16px">
    <h3>Daily cadence</h3>
    <table>
      <tr><th>Time</th><th>Block</th><th>Rule</th></tr>
      <tr><td>10 min</td><td>Revision</td><td>Yesterday’s definition from memory.</td></tr>
      <tr><td>45 min</td><td>Lesson</td><td>Read until you can teach the diagram.</td></tr>
      <tr><td>45 min</td><td>Gym / study</td><td>Solve before reveal.</td></tr>
      <tr><td>20 min</td><td>Verbal</td><td>Product example + what you would not build.</td></tr>
    </table>
  </div>
  {''.join(cards)}
</section>
'''
