TERMS = [
    ("Fiber", "React work unit.", "Linked node holding type, hooks, effects, DOM pointer.", "Explain render vs commit."),
    ("Reconciliation", "Matching old tree to new.", "Type+key identity; update vs remount.", "Keys interview."),
    ("Hydration", "Attach React to server HTML.", "Must match markup; costs main-thread JS.", "SSR vs INP."),
    ("SSR", "HTML on the server.", "TTFB/LCP vs hydrate cost.", "CSR vs SSR ADR."),
    ("CSR", "Render in the browser.", "Simple; slower first HTML.", "Issue page default."),
    ("ISR", "Rebuild static pages on a cadence.", "CDN HTML + revalidate.", "Docs/marketing."),
    ("Suspense", "Wait boundary + fallback.", "Throws thenable / lazy.", "Don’t invent a cache casually."),
    ("Concurrent rendering", "Interruptible render.", "Lanes, transitions, discard WIP.", "Why render is a calculation."),
    ("Transition", "Non-urgent update.", "useTransition; keeps input snappy.", "Jira filter."),
    ("Memoization", "Skip if inputs equal.", "Not free; shallow compare.", "Don’t memo everything."),
    ("Virtualization", "Render visible window.", "Overscan; a11y rowcount.", "20k tables."),
    ("CDN", "Edge cache of bytes.", "Great for hashed assets.", "Not for private HTML."),
    ("TTFB", "Time to first byte.", "Server/edge/network.", "LCP contributor."),
    ("LCP", "Largest contentful paint.", "Hero image/text.", "Preload the LCP asset."),
    ("INP", "Interaction to next paint.", "Handler+render+paint.", "Long tasks."),
    ("CLS", "Layout shift score.", "Reserve space.", "Fonts, plugins, images."),
    ("FCP", "First contentful paint.", "Something appeared.", "Critical CSS."),
    ("TTI", "Time to interactive (legacy-ish).", "Main thread quiet + usable.", "Talk INP + hydrate instead."),
    ("CSP", "Content-Security-Policy.", "Restrict script/frame sources.", "Depth, not a substitute for encoding."),
    ("CORS", "Browser cross-origin read rules.", "Not a server ACL.", "Doesn’t stop curl."),
    ("CSRF", "Cookie-auth request from another site.", "SameSite + token/header.", "JWT-in-header ≠ XSS-safe."),
    ("XSS", "Attacker JS as the user.", "Encode; sanitize HTML; CSP.", "React is not magic."),
    ("ETag", "Response validator.", "If-None-Match → 304.", "With Cache-Control."),
    ("Cache-Control", "Freshness policy.", "max-age, no-store, SWR.", "HTML vs hashed JS."),
    ("Service Worker", "Client proxy.", "Offline, precache.", "Stale HTML danger."),
    ("Microfrontend", "Independently deployed UI.", "Costly; isolation.", "Refuse by default."),
    ("Module Federation", "Runtime share/load remotes.", "Singleton React required.", "MFE implementation."),
    ("Idempotency", "Same request → same effect.", "Keys on POST retry.", "Transitions, uploads."),
    ("Optimistic update", "UI before server ACK.", "Rollback on fail.", "Not for irreversible."),
    ("Stale-while-revalidate", "Show old, refresh.", "HTTP or app cache.", "Issue lists."),
    ("staleTime", "App-cache freshness.", "No refetch while fresh.", "≠ gcTime."),
    ("gcTime", "When unused cache is dropped.", "Memory policy.", "Was cacheTime."),
    ("AbortController", "Cancel fetch.", "On key change/unmount.", "Plus generation token."),
    ("Generation token", "Ignore stale responses.", "Monotonic counter.", "Races."),
    ("BFF", "Backend for frontend.", "Compose + timeouts + partial.", "Can become a bottleneck."),
    ("Port/adapter", "Interface vs impl.", "Test fakes.", "Hexagonal-lite."),
    ("Modular monolith", "One deploy, hard modules.", "Default for 20 engineers.", "Enforce imports."),
    ("Cohesion", "One reason to change.", "Feature folders.", "vs coupling."),
    ("Coupling", "Forced to change together.", "Deep imports.", "Lint the graph."),
    ("Boundary", "Contract line.", "Package export, HTTP, event.", "Crossing without contract is a bug."),
    ("Design token", "Named visual decision.", "color.space.100.", "Not hex in apps."),
    ("Headless component", "Behavior without look.", "Focus, keyboard.", "Buy combobox."),
    ("CODEOWNERS", "Review routing.", "Ownership SLO.", "Scale people."),
    ("Tree shaking", "Drop unused exports.", "ESM side-effect free.", "Icon imports."),
    ("Code splitting", "Lazy chunks.", "Route + widget.", "5MB bundle."),
    ("Long task", ">50ms main thread.", "Blocks INP.", "Performance panel."),
    ("Forced reflow", "Sync layout from JS.", "offsetHeight after write.", "Thrash."),
    ("Critical rendering path", "Bytes to pixels.", "DOM+CSSOM+layout+paint.", "Whiteboard this."),
    ("preload", "This-page high priority.", "LCP image/font.", "Can steal bandwidth."),
    ("prefetch", "Likely next nav.", "Idle.", "Waste risk."),
    ("preconnect", "Early TLS.", "API/CDN origins.", "Few only."),
    ("HTTP/2", "Mux one TCP.", "HOL at TCP remains.", "≠ free 5MB JS."),
    ("HTTP/3", "QUIC/UDP.", "Better loss recovery.", "Still JS cost."),
    ("Brotli", "Text compression.", "Static assets.", "Not images."),
    ("SameSite", "Cookie cross-site rule.", "Lax/Strict/None+Secure.", "Not XSS protection."),
    ("HttpOnly", "JS cannot read cookie.", "Session cookies.", "vs localStorage."),
    ("JWT", "Signed claims token.", "Short-lived access.", "Storage is the question."),
    ("OAuth", "Delegated auth.", "BFF + PKCE common.", "Implicit is dated."),
    ("AuthN", "Who you are.", "Login/session.", "≠ AuthZ."),
    ("AuthZ", "What you can do.", "Server enforces.", "UI is UX."),
    ("Capability", "Permission bit.", "Batch /caps.", "Stale allow → 403 UX."),
    ("CSP nonce", "Allow listed scripts.", "Per-response.", "vs unsafe-inline."),
    ("frame-ancestors", "Who can iframe you.", "Clickjacking.", "Plugin allowlists."),
    ("WCAG", "A11y standard.", "POUR principles.", "AA typical bar."),
    ("ARIA", "A11y supplement.", "Wrong ARIA is worse.", "Native first."),
    ("Focus trap", "Tab stays in dialog.", "Restore on close.", "One Modal."),
    ("Live region", "SR announcement.", "polite vs assertive.", "Not every keystroke."),
    ("Roving tabindex", "One tab stop, arrows move.", "Boards, menus.", "Not 400 tab stops."),
    ("RTL layout", "Right-to-left layout.", "Logical CSS props.", "i18n architecture."),
    ("ICU", "Message format.", "Plurals, dates.", "i18n packs."),
    ("RUM", "Real-user monitoring.", "Vitals in prod.", "Slice by release/plugin."),
    ("Trace", "Request story.", "Click → BFF → DB.", "Correlation id."),
    ("Correlation ID", "Join telemetry.", "Header on APIs.", "Support dialog."),
    ("Session replay", "Record UX.", "PII/consent.", "Not a trace."),
    ("Error boundary", "Catch render errors.", "Not event/async unless routed.", "Route + plugin."),
    ("Feature flag", "Runtime gate.", "Not authz.", "Anti-flicker bootstrap."),
    ("Kill switch", "Turn off a feature/release.", "Flag + version.json.", "Keep drafts."),
    ("ADR", "Decision record.", "Why + alternatives.", "Interview speech."),
    ("Entity package", "Shared domain types/UI atoms.", "Issue, User.", "Don’t dump features here."),
    ("Public barrel", "index.ts exports.", "Small surface.", "Avoid re-export everything."),
    ("Dependency cruiser", "Import lint.", "Enforce layers.", "CI."),
    ("Affected tests", "Run what changed.", "Nx/Turbo.", "CI scale."),
    ("Visual regression", "Screenshot diff.", "DS primitives.", "Flake risk."),
    ("Contract test", "API shape pact.", "Cheaper than E2E.", "Multi-team."),
    ("MSW", "Mock Service Worker.", "Network in tests.", "vs spy fetch."),
    ("RTL (Testing Library)", "Testing Library.", "User-centric queries.", "Not enzyme."),
    ("Playwright", "E2E browser.", "Money paths.", "Not every tooltip."),
    ("useSyncExternalStore", "Safe external subscribe.", "No tearing.", "Stores."),
    ("Tearing", "UI shows mixed versions.", "Concurrent read hazard.", "Snapshots immutable."),
    ("Lane", "Priority band of updates.", "Internal scheduler.", "Urgent vs transition."),
    ("Commit phase", "Sync apply DOM.", "Cannot interrupt.", "Then layout/passive effects."),
    ("Render phase", "Calculate next tree.", "Interruptible.", "Must be pure-ish."),
    ("Host fiber", "DOM/native component.", "div, input.", "vs composite (YourComp)."),
    ("Composite fiber", "Function/class component.", "Has hooks list.", "Reconcile by type+key."),
    ("Key remount", "Change key to reset state.", "Forms, steppers.", "Deliberate."),
    ("Index key", "key={i}.", "State slides on reorder.", "Boards: never."),
    ("Fat context", "Many fields one value.", "All consumers rerender.", "Split / selector."),
    ("Selector", "Subscribe to a slice.", "Store libs.", "vs useContext whole."),
    ("Colocation", "State next to user.", "Stops render fanout.", "Search box."),
    ("Derived state", "Compute from source.", "Don’t copy props to state.", "Sync bugs."),
    ("Waterfall", "Serial waits.", "Fetch-then-fetch; parse-then-fetch.", "BFF, parallel."),
    ("N+1", "One + per-child requests.", "Widget dashboards.", "Batch."),
    ("Partial success", "Some parts fail, page lives.", "BFF timeouts.", "Senior answer."),
    ("Idempotency key", "Client-generated write id.", "Retries safe.", "POST /transition."),
    ("if-match", "Version precondition.", "409 on conflict.", "Multi-tab."),
    ("BroadcastChannel", "Tab-to-tab messages.", "Same origin.", "Draft/conflict."),
    ("Signed URL", "Time-limited object access.", "Uploads/downloads.", "Don’t cache long."),
    ("Sandbox iframe", "Restricted plugin frame.", "Hostile by default.", "postMessage allowlist."),
    ("Design system", "Tokens+primitives+docs+versioning.", "Multi-team UI.", "Governance."),
    ("Token pipeline", "Figma/JSON → CSS vars.", "Single language.", "Theming."),
    ("Semver", "Major breaking.", "DS public API.", "Dual-major window."),
    ("FOUC", "Flash of unstyled/wrong theme.", "Boot script before paint.", "data-theme."),
    ("INP attribution", "Which interaction/element.", "Web vitals JS.", "RUM."),
    ("Performance budget", "CI fail number.", "kB JS, LCP, INP.", "Stops entropy."),
    ("Coverage tab", "Unused JS in a session.", "DevTools.", "5MB hunt."),
    ("React Profiler", "Commit durations / why rendered.", "DevTools.", "First click when slow."),
    ("Why did this render?", "DevTools highlight.", "Props/state/hook.", "Context storms."),
    ("Keep-alive", "Cache hidden views.", "Must cap.", "20 tabs."),
    ("Detached DOM", "Node out of doc, still JS-held.", "Leak.", "Heap snapshot."),
    ("WeakMap cache", "Doesn’t pin the key.", "GC-friendly.", "Element metadata."),
    ("StructuredClone", "Deep copy platform.", "Workers, storage.", "JSON limits."),
    ("Beacon", "Send on unload.", "Analytics flush.", "Don’t block INP."),
    ("Retry-After", "Server backoff hint.", "429.", "Honor it."),
    ("Jitter", "Randomize backoff.", "Avoid thundering herd.", "Retries."),
    ("Cursor pagination", "Opaque next token.", "Stable under inserts.", "vs offset."),
    ("Offset pagination", "page=3&size=20.", "Breaks when data moves.", "Admin OK."),
    ("Normalized cache", "Entities by id (GraphQL).", "Share issue objects.", "GC complexity."),
    ("Document cache", "Query → payload.", "TanStack default.", "Simpler."),
    ("Plugin slot", "Host mount point.", "Budget + boundary.", "Issue view."),
    ("Bridge", "postMessage contract.", "Versioned.", "Host↔plugin."),
    ("Realm / tenant", "Isolation unit.", "Cache keys include it.", "Switch SEV-0."),
    ("Bootstrap payload", "User+flags+config first.", "Anti-flicker.", "Cookie-vary carefully."),
    ("Public env", "Build-time non-secret.", "VITE_*.", "Never secrets."),
    ("Runtime config", "Fetched/injected host config.", "Realms.", "Retarget without rebuild."),
    ("CODEOWNERS SLO", "Review time as a metric.", "People scale.", "Bottleneck teams."),
    ("Shared kernel", "Tiny cross-feature core.", "Grow it slowly.", "Distributed monolith risk."),
    ("RFC", "Written change proposal.", "Kernel/DS breaks.", "12 teams."),
    ("Dual-major", "Support two DS majors.", "Migration window.", "Cost vs freeze."),
    ("Codemod", "AST rewrite upgrades.", "DS migrations.", "Not perfect."),
    ("Chromatic", "Visual review SaaS.", "Storybook.", "DS CI."),
    ("OpenAPI types", "Generated client types.", "Avoid drift.", "Who owns breaks."),
    ("Pact", "Consumer-driven contract.", "Front/back.", "Cheaper than E2E."),
    ("INP p75", "75th percentile interaction.", "RUM target.", "Lab ≠ field."),
    ("Field vs lab", "RUM vs Lighthouse.", "Both.", "Plugins show in field."),
    ("Main thread", "JS+style+layout.", "Workers help CPU not React DOM.", "INP home."),
    ("Compositor", "GPU layers.", "Transforms.", "Doesn’t save fat JS."),
    ("Fetch Priority", "hint=high/low.", "LCP image high.", "Analytics low."),
    ("Priority hints", "See Fetch Priority.", "Not magic if busy.", "With preload."),
    ("Idle callback", "requestIdleCallback.", "Defer work.", "Not for paint."),
    ("rAF", "Before paint.", "Visual batch.", "Scrubbers."),
    ("startTransition", "API for transition lane.", "Filter lists.", "≠ faster CPU."),
    ("useDeferredValue", "Lag a value.", "Similar goal.", "vs debounce network."),
    ("flushSync", "Force commit now.", "Rare; hurts INP.", "Libraries sometimes."),
    ("Strict Mode", "Dev double-invoke.", "Find impure render.", "Don’t disable to hide."),
    ("Hook order", "Identity by position.", "No conditionals.", "Custom hooks too."),
    ("Stale closure", "Old captured state.", "Deps / fn update / ref.", "Phase 1 carry-over."),
    ("Controlled input", "value+onChange.", "Source of truth React.", "20k cells: careful."),
    ("Uncontrolled input", "defaultValue+ref.", "Fewer renders.", "Key remount resets."),
    ("asChild / Slot", "Compose element type.", "Button as link.", "DS APIs."),
    ("Token theme", "CSS vars on :root.", "No fat context.", "FOUC boot script."),
    ("Logical properties", "margin-inline-start.", "RTL.", "i18n."),
    ("ADF", "Atlassian Document Format (concept).", "Stored rich text.", "XSS/macros."),
    ("JQL", "Issue query language (concept).", "URL filter.", "Abort on change."),
    ("Issue key", "ISSUE-12 identity.", "Cache keys, React keys.", "Never index."),
    ("Presence", "Who’s viewing.", "Ephemeral channel.", "Don’t rerender body."),
    ("Catch-up", "REST after WS drop.", "Since timestamp/seq.", "Realtime designs."),
    ("At-least-once", "Dups possible.", "Dedupe by id.", "Chat/notify."),
    ("Exactly-once", "Usually a lie on FE.", "Idempotent apply.", "Don’t promise it."),
    ("Conflict UI", "409 / two tabs.", "if-match + modal.", "Don’t silent overwrite."),
    ("Draft durability", "IDB/localStorage.", "Kill switch must keep it.", "Comments/editor."),
    ("Sandbox", "Restricted execution.", "iframe plugins.", "Hostile."),
    ("Allowlist", "Explicit origins/scripts.", "CSP, postMessage.", "Denylist fails."),
    ("Principle of least privilege", "Min caps in UI+API.", "Batch caps.", "Admin portals."),
    ("Supply chain", "npm risk.", "Lockfile, pin, audit.", "postinstall."),
    ("BFF session", "Cookie at your origin.", "Tokens stay server-side.", "Preferred 2026."),
    ("PKCE", "OAuth public-client proof.", "With BFF still better.", "SPA flows."),
    ("Refresh token", "Long-lived credential.", "HttpOnly rotate.", "Not localStorage."),
    ("PCI", "Card data rules.", "Hosted fields.", "Ecommerce."),
    ("PII", "Personal data.", "Minimize analytics.", "Replay masking."),
    ("Consent", "Legal gate for tags/replay.", "Architecture, not a banner only.", "EU."),
    ("Tenant switch", "Clear all caches.", "SEV-0 if leak.", "Multi-tenant."),
    ("Custom domain", "Tenant hostname.", "Bootstrap by host.", "SSL at edge."),
    ("Project reference", "TS incremental.", "Monorepo.", "CI time."),
    ("Source map explorer", "See JS composition.", "5MB.", "CI artifact."),
    ("Lighthouse CI", "Lab budgets.", "Not field.", "Both needed."),
    ("Web vitals JS", "Field INP/LCP/CLS.", "RUM.", "Attribution."),
    ("Marker / measure", "performance.mark.", "Custom INP.", "Board drag."),
    ("INP long animation frame", "LoAF.", "Attribution help.", "Chrome."),
    ("Scheduler.yield", "Break long tasks.", "Newer API.", "INP."),
    ("Island architecture", "Hydrate widgets not the page.", "Marketing/docs.", "Not always the app."),
    ("RSC", "React Server Components.", "Know conceptually; not required to cargo-cult.", "Trade-off: network + cache."),
    ("Streaming HTML", "Bytes as ready.", "SSR.", "Earlier LCP possible."),
    ("Hydration mismatch", "Server≠client markup.", "time/random/theme.", "useId, boot theme."),
    ("useId", "Stable a11y ids.", "SSR-safe.", "Not CSS."),
    ("Portal", "Render elsewhere in DOM.", "Modals, listbox.", "Focus still your job."),
    ("Stacking context", "z-index world.", "Modals vs plugins.", "DS tokens."),
    ("Inert", "Ignore a subtree.", "Background behind modal.", "A11y."),
    ("aria-activedescendant", "Focus stays on input.", "Combobox.", "Autocomplete."),
    ("Grid pattern", "ARIA grid for tables.", "Heavy; or don’t fake.", "Data tables."),
    ("Name, Role, Value", "SR basics.", "Every control.", "Axe."),
    ("Contrast", "WCAG ratio.", "Tokens in CI.", "Lozenges."),
    ("Reduced motion", "prefers-reduced-motion.", "Skip big anim.", "Boards."),
    ("Data saver", "Save-Data header / hint.", "Skip prefetch.", "Prefetch risks."),
    ("Signed part upload", "Direct-to-store PUT.", "BFF init.", "Multi-GB."),
    ("Virus scan state", "Async after upload.", "UX poll.", "Files case."),
    ("CRDT", "Conflict-free types.", "Collab editors.", "Costly metadata."),
    ("OT", "Operational transform.", "Collab.", "vs lock."),
    ("Locking", "One writer.", "Simple collab.", "vs CRDT."),
    ("Presence heartbeat", "I’m still here.", "15–30s.", "Don’t setState the page."),
    ("Toast vs inbox", "Ephemeral vs history.", "Don’t Redux toasts forever.", "Notifications."),
    ("Badge", "Unread count.", "Not the inbox.", "Poll fallback."),
    ("Deep link", "URL to a notification target.", "URL design.", "Center items."),
    ("Command palette", "Cmd-K.", "Modal combobox.", "Don’t steal from inputs."),
    ("Feature edge", "Where a flag is evaluated.", "One place.", "Not 40 ifs."),
    ("Exposure event", "User saw a variant.", "Experiments.", "Analytics."),
    ("Anti-flicker", "Flags before first paint.", "Bootstrap.", "A/B."),
    ("Default flag", "Value if service down.", "Safe off for new risk.", "Kill switch."),
    ("Version.json", "Deployed SHA for tabs.", "Reload prompt.", "Stale tabs."),
    ("Skip waiting", "SW activate now.", "Emergency.", "UX flicker."),
    ("Precache", "SW install cache.", "Hashed assets.", "Not HTML casually."),
    ("Runtime cache", "SW fetch handler.", "SWR strategies.", "Auth pages careful."),
    ("Opaque response", "no-cors body unreadable.", "CDN images.", "Cache carefully."),
    ("Vary", "Cache key extra headers.", "Cookie/Accept.", "CDN poison risk."),
    ("Cache poison", "Wrong variant stored.", "Vary + tenant.", "Multi-tenant."),
    ("ETag weak", "W/ semantic same.", "304 still.", "Know it exists."),
    ("Immutable", "Cache-Control extra.", "Hashed files.", "Year-long."),
    ("no-store", "Don’t write cache.", "HTML/session.", "vs no-cache."),
    ("no-cache", "Revalidate before use.", "Often APIs.", "Name is confusing."),
    ("private", "Browser not CDN.", "User JSON.", "vs public."),
    ("public", "Any cache may store.", "Assets.", "Not cookie HTML."),
    ("max-age=0", "Immediately stale.", "Must revalidate.", "Dev sometimes."),
    ("SWR HTTP", "stale-while-revalidate=n.", "Edge/browser.", "vs app SWR."),
    ("Origin", "scheme+host+port.", "Cookies, CORS.", "postMessage."),
    ("Site", "eTLD+1.", "SameSite.", "vs origin."),
    ("Top-level navigation", "User clicked a link.", "Lax cookies sent.", "CSRF GET."),
    ("Custom header", "X-Requested-With etc.", "CSRF mitigator.", "CORS preflight."),
    ("Preflight", "OPTIONS before fancy CORS.", "Cost.", "Simple requests skip."),
    ("Simple request", "GET/POST limited headers.", "Form-like.", "CSRF still."),
    ("BFF cookie", "First-party session.", "Preferred.", "CSRF tokens still for mutations."),
    ("Double submit cookie", "CSRF pattern.", "Legacy-ish.", "SameSite often enough + header."),
    ("Content type XSS", "JSON as HTML.", "X-Content-Type-Options.", "APIs."),
    ("nosniff", "X-Content-Type-Options.", "Don’t guess MIME.", "Always."),
    ("Referrer-Policy", "How much referrer.", "Privacy.", "Cross-origin."),
    ("Permissions-Policy", "Disable powerful APIs.", "camera etc.", "Defense."),
    ("Trusted Types", "DOM XSS policy.", "Advanced CSP.", "If you must assign HTML."),
    ("Sanitizer API", "Platform sanitize.", "Emerging.", "Still encode default."),
    ("dangerouslySetInnerHTML", "React HTML hole.", "Needs sanitize+CSP.", "Classic trap."),
    ("javascript: URL", "XSS vector.", "Validate href.", "Link components."),
    ("SVG upload", "Scriptable image.", "Sanitize or sandbox.", "Files."),
    ("Macro / embed", "Stored HTML/JS.", "Confluence-like.", "Treat as hostile."),
    ("PostMessage", "Cross-frame events.", "Check event.origin.", "Plugins."),
    ("Resize loop", "Plugin grows forever.", "Cap + debounce.", "Host."),
    ("Singleton React", "One copy in runtime.", "Hooks.", "MFE."),
    ("Duplicate React", "Two copies.", "Invalid hook call.", "Federation share."),
    ("Import map", "Browser module remap.", "CDN React.", "Supply chain."),
    ("Lockfile", "Pinned graph.", "Commit it.", "CI."),
    ("postinstall", "Script on npm i.", "Review.", "Supply chain."),
    ("SBOM", "Software bill of materials.", "Awareness.", "Enterprise."),
    ("Dependabot", "Bump PRs.", "Review majors.", "Not autopilot."),
    ("CODEOWNERS merge", "Required review.", "Ownership.", "Bottlenecks."),
    ("Trunk-based", "Short branches.", "Flags for dark launch.", "vs long-lived."),
    ("Dark launch", "Ship code off.", "Flag on later.", "Kill switch cousin."),
    ("Progressive rollout", "% flag.", "Watch RUM.", "Not only backend."),
    ("Canary frontend", "Subset of users get new JS.", "CDN / cookie.", "RUM compare."),
    ("Rollback frontend", "Point HTML to previous hashes.", "Need versioned assets.", "SW cache."),
    ("Asset hash", "contenthash in name.", "Immutable cache.", "HTML must point new."),
    ("HTML as pointer", "References hashed JS.", "Must be fresher than JS.", "Cache rules."),
    ("Project graph", "Package deps.", "CI affected.", "Monorepo."),
    ("Circular import", "A↔B.", "Runtime undefined.", "Lint."),
    ("Barrel explosion", "index re-exports all.", "Kills tree-shake / cycles.", "Small barrels."),
    ("Deep import", "features/a/internal.", "Forbidden across features.", "Public API only."),
    ("Published path", "exports in package.json.", "Enforce.", "DS."),
    ("Dual package hazard", "CJS+ESM mess.", "Libraries.", "Know it exists."),
    ("Peer dependency", "Host supplies React.", "DS/MFE.", "Version align."),
    ("Resolutions / overrides", "Force a nested version.", "Last resort.", "Duplicate React."),
    ("Why-did-you-render", "Dev lib.", "Find rerenders.", "Not prod."),
    ("React DevTools", "Components + Profiler.", "First tool.", "Slow app."),
    ("Performance panel", "Long tasks, INP, layout.", "Second tool.", "With Profiler."),
    ("Memory panel", "Heaps, detachments.", "20 tabs.", "Compare snapshots."),
    ("Network waterfalls", "TTFB, blocking, size.", "LCP.", "Disable cache when debugging."),
    ("Disable cache", "DevTools checkbox.", "Don’t forget in HAR.", "Field is cached."),
    ("Throttling", "CPU/net emulate.", "Mid-range India laptops.", "Atlassian users aren’t all M3."),
    ("Field data", "CrUX / RUM.", "Truth.", "Lab is a microscope."),
    ("CrUX", "Chrome UX Report.", "Origins.", "Not logged-in app detail."),
    ("INP good", "<200ms.", "Target.", "p75."),
    ("LCP good", "<2.5s.", "Target.", "p75."),
    ("CLS good", "<0.1.", "Target.", "p75."),
]


def glossary() -> str:
    items = []
    for term, simple, tech, where in TERMS:
        items.append(f'''
<article class="card glossary-item" id="g-{term.lower().replace(" ", "-").replace("/", "-")}" data-search="{term}" data-stype="Glossary">
  <h3>{term}</h3>
  <p><b>Simple.</b> {simple}</p>
  <p><b>Technical.</b> {tech}</p>
  <p><b>Interview.</b> {where}</p>
</article>''')
    return f'''
<section class="block" id="glossary" data-search="Glossary Fiber INP CSP" data-stype="Section">
  <p class="kicker">{len(TERMS)} terms</p>
  <h2 class="section-title">Glossary</h2>
  <p class="lede">Searchable definitions at senior density. Use the box to filter.</p>
  <p><input id="glossary-filter" type="search" placeholder="Filter glossary…" style="width:100%;max-width:420px;padding:8px 10px;border-radius:8px;border:1px solid var(--border);background:var(--bg-card)" /></p>
  <div class="glossary-grid">{''.join(items)}</div>
</section>
'''
