from util import esc


def _sd(i, title, cat, stmt, clarify, fr, nfr, assume, arch, comps, flow, api, state, cache, perf, fail, sec, a11y, obs, scale, trade, follow, talk=None):
    if not talk:
        talk = (
            f"Lead with users, scale, and the critical path for {title}. "
            "Name two alternatives you rejected. Cover failure, accessibility, security, and how you would measure success. "
            "Do not start with a library or a Kubernetes diagram."
        )
    hid = f"sd-{i}"
    return f'''
<article class="problem" id="{hid}" data-pid="{hid}" data-search="{esc(title)}" data-stype="System design" data-cat="{cat}" data-mock="1" data-filterable>
  <div class="meta-row"><span class="badge badge-pattern">Practice question</span><span class="chip">{cat}</span></div>
  <h3>{i}. {esc(title)}</h3>
  <p><b>1. Problem.</b> {stmt}</p>
  <p><b>2. Clarifying questions.</b> {clarify}</p>
  <p><button type="button" class="toggle-btn" data-toggle="{hid}-a">Reveal ideal discussion</button>
     <button type="button" class="toggle-btn" data-complete="designs" data-cid="{hid}">Mark complete</button></p>
  <div class="reveal" id="{hid}-a">
    <p><b>3. Functional.</b> {fr}</p>
    <p><b>4. Non-functional.</b> {nfr}</p>
    <p><b>5. Assumptions.</b> {assume}</p>
    <p><b>6–8. Architecture / components / data flow.</b> {arch} {comps} {flow}</p>
    <p><b>9. API.</b> {api}</p>
    <p><b>10. State.</b> {state}</p>
    <p><b>11. Caching.</b> {cache}</p>
    <p><b>12. Performance.</b> {perf}</p>
    <p><b>13. Failures.</b> {fail}</p>
    <p><b>14. Security.</b> {sec}</p>
    <p><b>15. Accessibility.</b> {a11y}</p>
    <p><b>16. Observability.</b> {obs}</p>
    <p><b>17. Scaling.</b> {scale}</p>
    <p><b>18. Trade-offs.</b> {trade}</p>
    <p><b>19. Follow-ups.</b> {follow}</p>
    <p><b>20. Ideal interview discussion.</b> {talk}</p>
  </div>
  <div class="status-btns">
    <button type="button" data-status="not-started">Not Started</button>
    <button type="button" data-status="attempted">Attempted</button>
    <button type="button" data-status="solved">Solved</button>
    <button type="button" data-status="review">Review</button>
    <button type="button" data-status="mastered">Mastered</button>
  </div>
</article>
'''


SD = [
    ("Design a Jira-like board", "architecture",
     "Kanban board with columns, drag-drop, filters, issue overlay.",
     "Realtime? Plugin fields? How many cards? Mobile?",
     "Move issues, filter, open issue, presence optional.",
     "INP on drag, permission-safe, keyboard.",
     "400 cards, 10k in filter, cookie session.",
     "Feature module + virtualized columns + issue route overlay.",
     "BoardPage, Column, Card, IssueDrawer, useBoard, useMoveIssue.",
     "Snapshot load → render → optimistic move → PATCH → invalidate/reconcile. Remote: WS or poll.",
     "GET /board?jql; PATCH /issue/:id; GET /issue/:id.",
     "URL jql+selected; server cache board/issues; local drag.",
     "SWR snapshot; mutation invalidates issue+board.",
     "Virtualize, cheap cards, transition on filter.",
     "409 conflict, WS drop, PATCH fail rollback.",
     "Authz server-side; XSS in titles if HTML; CSRF.",
     "Roving tab, live region on move, no color-only status.",
     "Drag INP, transition errors, plugin crashes.",
     "More cards → virtualize + paginate columns; more teams → clearer package boundaries.",
     "Poll vs WS; iframe plugins vs in-bundle.",
     "How do you handle custom fields on the card?",
     "Start with users and scale, then URL+cache+virtualize, then failures. Do not draw Kubernetes."),
    ("Design autocomplete / typeahead", "architecture",
     "Search-as-you-type for issues or users.",
     "Debounce? Min chars? Empty state? Mobile?",
     "Suggest, keyboard, recents, abort stale.",
     "INP on type; a11y combobox; &lt;200ms suggest p75.",
     "10M issues, prefix search on server.",
     "Input + listbox portal; query key [suggest, q]; abort+gen.",
     "useSuggest, HighlightMatch, Recents store.",
     "Keystroke → local value → debounce 150ms → fetch → replace list.",
     "GET /suggest?q=&limit=20",
     "Input local; recents localStorage; results server cache short TTL.",
     "Dedup in-flight; cache last 20 queries.",
     "Debounce, cancel, cheap highlight, don’t re-render app.",
     "Slow network: show last; error: retry; empty: recents.",
     "Authz filter server-side; no leak private titles.",
     "combobox pattern, aria-activedescendant, announce count.",
     "Suggest latency, abort rate.",
     "QPS: cache popular prefixes at edge.",
     "Client filter vs server; GraphQL vs REST.",
     "Typo-tolerance? Multi-entity?",
     "Say combobox + abort + debounce before any library name."),
    ("Design real-time notifications", "architecture",
     "In-app bell, toast, badge, notification center.",
     "Email too? Mobile push? Retention?",
     "Fan-in events, read/unread, deep link.",
     "At-least-once; badge freshness; a11y live polite.",
     "1M users, bursty (release), 50 events/min peak per user rare.",
     "WS or SSE + REST inbox; service worker for push.",
     "NotificationCenter, Toaster, Badge, event mapper.",
     "Event → normalize → drop dup by id → update cache + toast if foreground.",
     "GET /notifications?cursor; POST /read; WS /push.",
     "Inbox infinite query; badge in tiny store; don’t put toasts in Redux forever.",
     "Inbox pages; badge poll fallback 30s.",
     "Virtualize center; batch toasts.",
     "WS drop → poll; dup events; permission denied.",
     "No token in query string; user isolation.",
     "aria-live polite; don’t steal focus on toast.",
     "Delivery lag, WS error rate.",
     "Per-user connections: fanout at edge; fallback poll.",
     "WS vs SSE vs poll; in-app vs OS notifications.",
     "Mute, digest, per-project filters.",
     "Clarify urgency vs history. Badge is not the inbox."),
    ("Design a collaborative editor", "architecture",
     "Multi-user document editing in the browser.",
     "How concurrent? Offline? Rich text?",
     "Type, presence, comments, versions.",
     "Conflict safety; INP typing; a11y of editor.",
     "Usually 1–3 concurrent; large docs.",
     "Iframe or isolated editor package; OT/CRDT/lock — pick from concurrency requirement.",
     "EditorSurface, Presence, Comments, SaveIndicator.",
     "Local edits → OT/CRDT → send; apply remote; presence separate channel.",
     "WS ops; REST snapshot/version; comments REST.",
     "Draft IDB; committed version server.",
     "Don’t rerender whole app per key; isolate editor store.",
     "Disconnect rebase/reject; version conflict UI.",
     "XSS in embeds; ACL; if-match.",
     "Contenteditable a11y is a project; budget it.",
     "Save lag, conflict rate, JS errors in editor.",
     "Doc size: window rendering; CRDT metadata growth.",
     "CRDT vs OT vs locking vs comments-only.",
     "Offline, macros, images.",
     "Most products should not invent CRDT on the whiteboard without saying the cost."),
    ("Design a dashboard with 100 widgets", "architecture",
     "Configurable analytics home.",
     "Who authors widgets? Live data?",
     "Layout, range, widget types, export.",
     "First paint, isolation of slow widgets, CLS.",
     "100 widgets, mixed cost queries.",
     "Registry + grid + lazy widget + BFF batch.",
     "Grid, WidgetChrome, WidgetError, RangeBar.",
     "Range in URL → each widget query key includes range → fetch visible first.",
     "GET /widgets/data?ids=&range= or batch POST.",
     "Layout prefs; range URL; per-widget cache.",
     "CDN aggregates; short TTL.",
     "Idle load; virtualize; request cap.",
     "One widget 500s: timeout + skeleton, not blank page.",
     "Tenant ACL; no leak in exported PNG.",
     "Chart text alternative; keyboard chrome.",
     "Slow widget traces.",
     "N+1 vs megaquery; custom JS widgets.",
     "Realtime widgets?",
     "Isolation and batching beat a prettier chart library."),
    ("Design an infinite social feed", "architecture",
     "Mobile/web activity stream.",
     "Ranking? Ads? Media?",
     "Scroll, like, compose, unread.",
     "Scroll INP, memory, a11y new-content.",
     "Unbounded items.",
     "Virtual list + cursor pages + media unmount.",
     "Feed, Item, Composer, Player.",
     "Cursor fetch append; like optimistic; rank server.",
     "GET /feed?cursor; POST /like.",
     "Infinite query; composer local.",
     "Personalized first page short TTL.",
     "Windowing; recycle; image sizing.",
     "Hole in timeline; retry page.",
     "XSS posts; authz delete.",
     "Load more button vs infinite (a11y + SEO).",
     "Jank RUM.",
     "Client vs server rank.",
     "Live prepend?",
     "Talk memory after 20 screens explicitly."),
    ("Design a multi-GB file uploader", "architecture",
     "Resume, progress, many files.",
     "Max size? Virus scan? Folders?",
     "Select, pause, retry, complete.",
     "Flaky net; durable progress; don’t lose hours.",
     "4GB, 6 files, laptop.",
     "Queue in IDB; worker hash; parallel parts cap=3; BFF signed URLs.",
     "Dropzone, Queue, Row, Preview.",
     "Init upload → parts PUT → complete → scan state poll.",
     "POST /uploads; PUT part; POST complete.",
     "Queue durable local; server upload session.",
     "No long cache on signed URLs.",
     "Worker hashing; don’t block UI.",
     "Part fail retry; complete 409; tab close resume.",
     "ACL; sandbox preview; XSS SVG.",
     "Progress announced.",
     "Fail/resume metrics.",
     "Direct-to-store vs proxy (cost vs inspect).",
     "Checksum? Folder upload?",
     "Idempotency and resume are the design, not the dropzone CSS."),
    ("Design a video streaming frontend", "architecture",
     "Play, seek, quality, captions.",
     "Live vs VOD? DRM?",
     "Player, timeline, captions, continue-watching.",
     "Startup time; rebuffer; a11y captions.",
     "CDN segments; adaptive bitrate.",
     "Lazy player; MSE/HLS library; don’t write a demuxer.",
     "Player, Controls, Captions, NextUp.",
     "Manifest → segments; prefetch next; position heartbeat.",
     "GET manifest; GET segments; POST progress.",
     "Continue-watching server; quality local.",
     "CDN long cache segments; short manifest.",
     "Don’t rerender app on timeupdate (10Hz) — ref/rAF.",
     "Stall, 403 signed URL expiry, caption fail.",
     "Signed URLs; DRM if required.",
     "Captions default-on option; keyboard.",
     "Rebuffer rate, startup.",
     "Player isolation from React render.",
     "Live DVR?",
     "timeupdate + React is a classic INP footgun."),
    ("Design a frontend for 1M MAU", "architecture",
     "Generic SaaS web app at million-user scale.",
     "Read/write mix? Regions? Plugins?",
     "Core CRUD + search + notify.",
     "Vitals budgets; 99.9%; multi-region.",
     "1M MAU, 10% DAU, peaks.",
     "Modular monolith, edge CDN static, BFF, RUM.",
     "Shell, features, DS, query client.",
     "Public marketing SSR; app CSR/SSR hybrid.",
     "Versioned REST; idempotent writes.",
     "Hashed assets immutable; API SWR.",
     "Edge + HTTP cache + app cache.",
     "Split; vitals budgets in CI.",
     "Region fail: failover static + API.",
     "Session cookie; CSP; tenant isolation.",
     "A11y in DS so 1M inherit it.",
     "RUM by geo/release.",
     "Scale people (CI, packages) and runtime.",
     "Multi-tenant noisy neighbor.",
     "Don’t jump to Kafka. Talk CDN, bundles, RUM, teams."),
    ("Design a multi-tenant SaaS frontend", "architecture",
     "Tenant-specific branding, data isolation, entitlements.",
     "Custom domain? Data residency?",
     "Tenant switch, theming, features.",
     "No cross-tenant leak; fast switch.",
     "10k tenants, some huge.",
     "Runtime config per host; token-scoped APIs; theme tokens from tenant.",
     "TenantProvider (slow), FeatureGate, Theme.",
     "Host → config → boot → queries always include tenant context server-side (never trust client).",
     "GET /bootstrap; all APIs session-bound.",
     "Clear all caches on tenant switch.",
     "no-store HTML; tenant assets on CDN with separate paths.",
     "Don’t download all tenant themes.",
     "Wrong-tenant cache bug is a SEV-0.",
     "Server isolation; audit.",
     "Theme contrast still WCAG.",
     "Switch errors, leak tests.",
     "Custom domain SSL at edge.",
     "Build-per-tenant vs runtime theme.",
     "How do you test isolation?",
     "Cache keys and switch are the interview."),
    ("Design a plugin architecture", "architecture",
     "Third parties extend issue view.",
     "In-process JS vs iframe? Marketplace?",
     "Slots, lifecycle, theming, permissions.",
     "Isolation; perf budget per plugin; security.",
     "20 plugins on a page possible.",
     "Iframe sandbox + postMessage contract + DS tokens via vars; error boundary per slot.",
     "PluginHost, Slot, Bridge.",
     "Host loads manifest → iframe → handshake → resize → events.",
     "GET /plugins; plugin own APIs.",
     "Host cache manifests; plugin own cache.",
     "Budget time-to-slot; lazy offscreen.",
     "Plugin throw; infinite resize loop; handshake timeout.",
     "Treat plugin as hostile; origin allowlist; CSP frame-src.",
     "Focus in/out of iframe.",
     "Plugin INP contribution; crash rate.",
     "Many plugins: queue init.",
     "In-bundle vs iframe vs web component.",
     "Versioning of the bridge.",
     "Atlassian-like: isolation first, pretty integration second."),
    ("Design a feature-flag system (client)", "architecture",
     "Flags in a large React app.",
     "Server authoritative? % rollouts? User targeting?",
     "Gate features, experiments, kill switches.",
     "No flash of wrong variant; consistent; fast boot.",
     "200 flags, 20 teams.",
     "Boot flags from edge/bootstrap; FlagProvider; evaluate at feature edge; typed flag map.",
     "useFlag, Gate, experiment expose.",
     "Bootstrap → evaluate → render; updates via poll/WS rare.",
     "GET /flags (signed, user-scoped).",
     "In-memory; don’t persist experiments in localStorage (bias).",
     "CDN bootstrap with cookie variation carefully (cache poison).",
     "Don’t re-render the world on one flag.",
     "Flag service down: defaults + last known.",
     "Flags are not authz; still enforce server.",
     "Don’t skip a11y in gated UI.",
     "Exposure events for experiments.",
     "Fanout flag service.",
     "Build-time vs runtime flags.",
     "Sticky experiments, anti-flicker.",
     "Flicker and ‘flag as permission’ are the traps."),
    ("Design a large data table", "architecture",
     "Sort, filter, virtualize, select, bulk.",
     "Server or client sort? Editable cells?",
     "10k–100k rows, many columns.",
     "Scroll 60fps; keyboard; selection.",
     "Server-backed unless tiny.",
     "Headless table + virtualizer + URL sort/filter.",
     "Table, Header, Row, Cell, BulkBar.",
     "URL → query key → page/window fetch → render window.",
     "GET /rows?sort&cursor&filter.",
     "URL + server cache; selection local.",
     "Short TTL; ETag optional.",
     "Virtualize rows and sometimes columns; memo cells.",
     "Stale sort; lost selection on refresh.",
     "Export ACL.",
     "aria-rowcount, grid pattern or don’t fake a grid.",
     "Scroll jank.",
     "Window fetch vs page.",
     "Spreadsheet editing?",
     "Virtualization + URL is 80% of the answer."),
    ("Design a design system platform", "architecture",
     "Tokens, packages, docs, adoption.",
     "Multi-brand? React only?",
     "Primitives, docs, versioning, a11y.",
     "Breaking-change policy; CI visual.",
     "12 product teams.",
     "Token pipeline → primitives → composites → apps. Docs site. Codemods.",
     "Packages, Storybook, lint plugin.",
     "Publish major/minor; apps upgrade; RFC for breaks.",
     "npm packages; token JSON.",
     "n/a mostly; docs CDN.",
     "Tree-shake; no second React.",
     "Failed visual CI blocks.",
     "Don’t ship XSS in docs MDX.",
     "A11y in primitives is the point.",
     "Adoption metrics, a11y violations.",
     "Multi-major support window.",
     "Headless vs full visual.",
     "Icon system, i18n density.",
     "Talk governance, not Button CSS."),
    ("Design a micro-frontend platform", "architecture",
     "Host + independently deployed apps.",
     "Why not modular monolith?",
     "Route integrate, auth, DS, shared deps.",
     "Singleton React; isolation; perf budget.",
     "5 teams, weekly deploys.",
     "Shell router; runtime load; shared DS; contract tests.",
     "Shell, Remote, Boundary, Nav.",
     "Shell fetch manifest → load remote → mount at path.",
     "Manifest GET; remotes static hashed.",
     "Shell session; remotes no separate login.",
     "Long cache remotes; short manifest.",
     "Shared deps; avoid duplicate React.",
     "Remote 404; version mismatch.",
     "Auth cookie parent; CSP.",
     "Focus when crossing remotes.",
     "Load time per remote.",
     "Indep deploy vs UX consistency.",
     "Federation vs iframe.",
     "Rollback a remote.",
     "Only after you justified not using a modular monolith."),
    ("Design typeahead mention list in an editor", "architecture",
     " @user in comments.",
     "Permissions? Groups?",
     "Trigger, filter, insert token.",
     "Keyboard, a11y listbox, abort.",
     "Large orgs 100k users.",
     "Editor plugin + portaled list + suggest API.",
     "MentionPlugin, List, Chip.",
     " @ → debounce → search → insert mention id not name only.",
     "GET /users?q=",
     "Editor local; results cache.",
     "Short TTL.",
     "Don’t search on every key without debounce.",
     "No results; permission hide.",
     "Don’t leak hidden users.",
     "listbox; insert announces.",
     "Suggest latency.",
     "Client filter vs server.",
     "Notify mentioned users.",
     "Store IDs so renames work."),
    ("Design image pipeline on the frontend", "architecture",
     "Responsive images, CDN, LCP.",
     "User upload? Formats?",
     "Upload, variants, display.",
     "LCP, CLS, cost.",
     "Millions of assets.",
     "Upload to store; CDN variants; &lt;img&gt; srcset; priority on LCP only.",
     "Avatar, Hero, Gallery.",
     "Upload → scan → variants → URL.",
     "Signed POST; GET variants.",
     "CDN long cache variants.",
     "Hash URLs.",
     "Correct sizes; lazy non-LCP.",
     "Broken image; scan fail.",
     "SVG XSS; auth on private.",
     "Alt required in API.",
     "LCP element attribution.",
     "Client crop vs server.",
     "Art direction.",
     "Connect to LCP explicitly."),
    ("Design SSR vs CSR for an issue page", "architecture",
     "Choose rendering mode.",
     "SEO? Auth? Interactivity?",
     "First view, then edit.",
     "LCP, TTFB, hydration cost.",
     "Logged-in app, weak SEO need.",
     "Often CSR + skeleton is enough; SSR if LCP/HTML needed for bots or first paint of body text.",
     "Document vs app shell.",
     "SSR HTML → hydrate → fetch extras; or CSR shell → fetch.",
     "GET page; streaming optional.",
     "CDN for public; private no-store.",
     "Edge cache public only.",
     "Hydration long task risk.",
     "Mismatch hydrate errors.",
     "Auth on SSR (cookie at edge).",
     "Content in HTML helps a11y/SEO.",
     "TTFB vs hydrate INP.",
     "SSR vs CSR vs stream.",
     "i18n, themes FOUC.",
     "Pick from constraints, not fashion."),
    ("Design permissions UI", "architecture",
     "Hide/disable by capability.",
     "ABAC? Groups?",
     "Gate buttons, routes, fields.",
     "No leak via UI only; fast evaluate.",
     "Many schemes per issue.",
     "usePermission hook; server still enforces; cache capabilities per resource.",
     "Gate, DisabledReason, RouteGuard.",
     "Bootstrap caps → evaluate → render; refresh on role change.",
     "GET /caps?resource=",
     "Caps in query cache; never only-client.",
     "User-scoped, short TTL.",
     "Don’t waterfall 40 cap calls — batch.",
     "Stale allow → server 403 UX.",
     "UI is not security.",
     "Disabled buttons have names/reasons.",
     "403 rate.",
     "Batch caps.",
     "Field-level vs view-level.",
     "Talk 403 UX and batching."),
    ("Design i18n architecture", "architecture",
     "20 languages, RTL, density.",
     "Pseudo-loc? ICU?",
     "Messages, dates, plurals, RTL layout.",
     "No layout break; load only needed locale.",
     "Large catalogs.",
     "Lazy locale packs; ICU; logical CSS properties; DS spacing.",
     "T, DateTime, RtlProvider.",
     "Boot locale → load pack → render; switch reloads packs.",
     "Static JSON per locale.",
     "CDN long cache hashed packs.",
     "Hashed.",
     "Don’t bundle 20 locales in main.",
     "Missing key fallback.",
     "XSS if you interpolate HTML in translations.",
     "Lang attribute; no truncation-only.",
     "Missing translation rate.",
     "Split by feature.",
     "Client vs server render locale.",
     "RTL is architecture (logical props), not a CSS afterthought."),
    ("Design analytics event pipeline (client)", "architecture",
     "Product analytics from the SPA.",
     "PII? Consent?",
     "Track intents, batch, consent.",
     "Don’t block INP; privacy.",
     "High volume clicks.",
     "Telemetry port; queue; batch; flush on hide; map PII in adapter.",
     "track(), consent gate.",
     "UI → track(intent) → queue → send.",
     "POST /events batch.",
     "In-memory queue; not localStorage PII.",
     "n/a.",
     "Idle flush; never in the click hot path sync.",
     "Beacon fail; consent revoke.",
     "Consent, minimize, no secrets.",
     "Don’t track keystrokes in inputs.",
     "Drop rate.",
     "Sample.",
     "3rd party tags vs first-party.",
     "INP and privacy first."),
    ("Design a search results page", "architecture",
     "Full search, facets, preview.",
     "JQL? Typo?",
     "Query, facets, sort, preview pane.",
     "Shareable URL; INP facets; a11y.",
     "10M docs.",
     "URL is source of query; results virtualized; preview prefetch.",
     "SearchBar, Facets, Results, Preview.",
     "URL → search key → results + facets; abort on change.",
     "GET /search?q&facets&cursor.",
     "URL + server cache.",
     "SWR; popular q at edge if public.",
     "Abort; virtualize; don’t fetch preview for all.",
     "Slow query cancel; zero results.",
     "ACL in results.",
     "Landmarks; announce count.",
     "Query latency.",
     "Facet explosion.",
     "Highlight snippets XSS.",
     "URL + abort is the core."),
    ("Design presence (who’s viewing)", "architecture",
     "Avatars on an issue.",
     "Accuracy needs?",
     "Join/leave, cursor optional.",
     "Cheap; degrade; privacy.",
     "50 viewers.",
     "Presence channel separate from document; ephemeral store; throttle.",
     "PresenceStack, Cursor.",
     "Heartbeat 15–30s; WS events; timeout.",
     "WS presence; REST fallback.",
     "Not cached long.",
     "n/a.",
     "Don’t rerender issue body on presence.",
     "Ghost users; disconnect.",
     "Don’t expose hidden watchers if product forbids.",
     "Announce join only if useful (usually not).",
     "Connection count.",
     "Fanout.",
     "Poll vs WS.",
     "Isolate from the document render tree."),
    ("Design comment thread UX", "architecture",
     "Nested comments on an issue.",
     "Realtime? Reactions?",
     "CRUD, quote, mention, sort.",
     "INP editor; a11y threads.",
     "1k comments worst.",
     "Paginate or virtualize; composer isolated; mention autocomplete.",
     "Thread, Item, Composer.",
     "Fetch page; optimistic post; invalidate issue comments key.",
     "GET/POST /comments.",
     "Draft local; list server.",
     "SWR.",
     "Don’t mount 1k editors — one composer.",
     "Post fail; moderation.",
     "XSS; mentions ACL.",
     "Nested lists semantics; live new comment.",
     "Post error rate.",
     "Virtualize deep trees.",
     "Realtime comments.",
     "One editor instance is the performance insight."),
    ("Design keyboard-first command palette", "architecture",
     "Cmd-K actions and search.",
     "Scope? Plugins?",
     "Open, filter, run action, recents.",
     "INP; a11y listbox; don’t steal from inputs unexpectedly.",
     "200 commands + search.",
     "Portal modal; fuse client commands; debounce server search.",
     "Palette, Group, Item.",
     "Hotkey → open → filter local → optional server → run.",
     "GET /suggest optional.",
     "Recents local; commands registry.",
     "n/a.",
     "Virtualize long lists; cheap fuzzy.",
     "Action fail toast.",
     "Don’t run destructive without confirm.",
     "Focus trap; restore; combobox.",
     "Open-to-run time.",
     "Plugin commands isolation.",
     "Global hotkey vs input.",
     "Treat it as a modal combobox, not a div."),
    ("Design theme switching without FOUC", "architecture",
     "Light/dark/system + tenant tokens.",
     "SSR?",
     "Toggle, persist, system sync.",
     "No flash; no app-wide rerender storm.",
     "All users.",
     "Inline boot script sets data-theme before paint; CSS vars; React only syncs.",
     "ThemeToggle, boot snippet.",
     "localStorage + prefers-color-scheme → attribute → CSS.",
     "Optional user pref API.",
     "Pref in localStorage / user profile.",
     "n/a.",
     "Don’t put theme in fat context with tickets.",
     "Invalid stored value.",
     "Contrast still WCAG; persist XSS n/a.",
     "Respect prefers-contrast if you can.",
     "Flash rate (hard).",
     "SSR must emit the same attribute.",
     "User vs system.",
     "Boot script + CSS vars, not a React-only theme."),
    ("Design optimistic issue transition", "architecture",
     "Move status immediately.",
     "Validators? Conditions?",
     "Click transition, undo, fail.",
     "Rollback; consistency; a11y confirm.",
     "Common path success.",
     "Cache overlay; PATCH; rollback + toast; 409 refresh.",
     "TransitionMenu, OptimisticCard.",
     "UI update → request → confirm or revert.",
     "POST /transition idempotent key.",
     "Issue+board keys.",
     "Invalidate related.",
     "Don’t block the click on network.",
     "Validator fail; concurrent move.",
     "Server authz; CSRF.",
     "Announce new status.",
     "Rollback rate.",
     "When not to be optimistic (irreversible).",
     "Conditions, screens on transition.",
     "Idempotency key + rollback story."),
    ("Design a BFF for the issue page", "architecture",
     "Aggregate issue, comments, watchers, fields.",
     "GraphQL or REST BFF?",
     "One round trip first paint; progressive extras.",
     "TTFB budget; partial fail.",
     "Many backends.",
     "BFF compose; field-level errors; don’t block LCP on watchers.",
     "BFF route, client query.",
     "Parallel downstream; timeout per part; return partial.",
     "GET /bff/issue/:id?parts=",
     "Client cache the aggregate and parts.",
     "Short TTL user-specific.",
     "Timeouts; don’t mega-await.",
     "1 of 5 down: still show issue.",
     "Auth forward; no over-fetch leak.",
     "n/a.",
     "Part latency traces.",
     "BFF as bottleneck — cache + timeouts.",
     "GraphQL vs BFF REST.",
     "N+1 clients vs BFF complexity.",
     "Partial success is the senior answer."),
    ("Design rollback / kill switch UX", "architecture",
     "Bad release, flag off, stale tabs.",
     "Who can kill?",
     "Banner, force refresh, flag default.",
     "Don’t lose drafts; communicate.",
     "All sessions.",
     "Version file on CDN; compare; prompt reload; flags default off.",
     "UpdateBanner, draft guard.",
     "Poll version; if mismatch and no dirty state, reload; else prompt.",
     "GET /version.json cache-bust.",
     "Drafts IDB.",
     "version.json no-cache.",
     "Don’t loop reload.",
     "User ignores banner.",
     "Only admins kill; audit.",
     "Focus the banner.",
     "Old-version session count.",
     "Hard kill vs soft.",
     "SW cache of old HTML.",
     "Stale tabs are part of frontend architecture."),
    ("Design multi-tab consistency", "architecture",
     "Two tabs edit the same issue.",
     "Lock or merge?",
     "Awareness, conflict, draft.",
     "Don’t silent overwrite.",
     "Two tabs same user.",
     "BroadcastChannel + version if-match; presence; conflict modal.",
     "ConflictModal, version hook.",
     "Tab A saves → channel notify → Tab B dirty? prompt.",
     "if-match versions.",
     "Per-tab draft.",
     "n/a.",
     "Cheap channel; don’t sync every keystroke.",
     "Both saved; 409.",
     "Same session cookies.",
     "Announce conflict.",
     "409 rate.",
     "Lock vs last-write.",
     "Shared worker?",
     "BroadcastChannel + if-match is enough for most products."),
]

def sysdesign() -> str:
    cards = []
    for i, row in enumerate(SD, 1):
        cards.append(_sd(i, *row))
    return f'''
<section class="block" id="sysdesign" data-search="Frontend System Design Question Bank" data-stype="Section">
  <p class="kicker">{len(SD)} practice questions</p>
  <h2 class="section-title">Frontend System Design Question Bank</h2>
  <p class="lede">Every item is a <b>practice question</b> for senior interviews — not labeled as an official Atlassian question. Use the 15-step communication framework. Filter and mark status for spaced repetition.</p>
  <div class="filters">
    <select id="filter-status">
      <option value="all">All</option>
      <option value="incomplete">Incomplete</option>
      <option value="complete">Complete</option>
      <option value="weak">Weak</option>
      <option value="review">Review</option>
    </select>
    <select id="filter-cat">
      <option value="all">All categories</option>
      <option value="architecture">Architecture</option>
    </select>
    <input id="filter-text" type="search" placeholder="Filter designs…" />
  </div>
  {''.join(cards)}
</section>
'''
