from util import practice_gym


def arrays_gym() -> str:
    return practice_gym("gym-arrays", "Practice this topic — Arrays",
        "Get fluent at indexes, write-pointers, prefixes, and in-place work. Do not reach for <code>splice</code> in a loop.",
        [
            ("tp-ar-1", 1, "Second largest", "easy", "array", "one-pass scan",
             "Return the second-largest distinct value, or null if it does not exist (all equal, or n < 2).",
             "Track max and second. Only demote into second when x is strictly between them.",
             "function secondLargest(a) {\n  let max = -Infinity, second = -Infinity;\n  for (const x of a) {\n    if (x > max) { second = max; max = x; }\n    else if (x < max && x > second) second = x;\n  }\n  return second === -Infinity ? null : second;\n}",
             "O(n)", "O(1)"),
            ("tp-ar-2", 2, "Move zeros to the end", "easy", "array", "write pointer",
             "Mutate nums so all zeros sit at the end. Relative order of non-zeros stays. Extra array is legal only if you then copy back — prefer one write index.",
             "Read pointer scans. Write index takes the next non-zero. Fill the tail with zeros.",
             "function moveZeroes(nums) {\n  let w = 0;\n  for (let r = 0; r < nums.length; r++) if (nums[r] !== 0) nums[w++] = nums[r];\n  while (w < nums.length) nums[w++] = 0;\n  return nums;\n}",
             "O(n)", "O(1)"),
            ("tp-ar-3", 3, "Running sum", "easy", "array", "prefix in place",
             "Return the prefix sums: out[i] = nums[0] + … + nums[i]. Mutate or allocate — say which.",
             "Keep a running total. Each slot is previous total + this value.",
             "function runningSum(nums) {\n  for (let i = 1; i < nums.length; i++) nums[i] += nums[i - 1];\n  return nums;\n}",
             "O(n)", "O(1) extra"),
            ("tp-ar-4", 4, "Plus one", "easy", "array", "digits / carry",
             "digits is a non-negative integer, most significant digit first. Add one and return the new digit array.",
             "Walk from the end. 9 becomes 0 and carry continues. If you leave the loop still carrying, unshift 1.",
             "function plusOne(digits) {\n  for (let i = digits.length - 1; i >= 0; i--) {\n    if (digits[i] < 9) { digits[i]++; return digits; }\n    digits[i] = 0;\n  }\n  digits.unshift(1);\n  return digits;\n}",
             "O(n)", "O(1) extra (unshift is O(n) once)"),
            ("tp-ar-5", 5, "All disappeared numbers", "easy", "array", "index as mark",
             "nums contains n integers, each in 1..n. Some values are missing (others repeat). Return every missing value. O(n) time, O(1) extra besides the answer.",
             "Mark presence by negating nums[abs(x)-1]. A still-positive slot i means i+1 never appeared.",
             "function findDisappeared(nums) {\n  for (const x of nums) {\n    const i = Math.abs(x) - 1;\n    if (nums[i] > 0) nums[i] = -nums[i];\n  }\n  const out = [];\n  for (let i = 0; i < nums.length; i++) if (nums[i] > 0) out.push(i + 1);\n  return out;\n}",
             "O(n)", "O(1) extra"),
            ("tp-ar-6", 6, "Max consecutive ones", "easy", "array", "run length",
             "Binary array. Length of the longest run of 1s.",
             "Reset the run on 0. Track the best run.",
             "function findMaxConsecutiveOnes(nums) {\n  let run = 0, best = 0;\n  for (const x of nums) {\n    run = x === 1 ? run + 1 : 0;\n    best = Math.max(best, run);\n  }\n  return best;\n}",
             "O(n)", "O(1)"),
            ("tp-ar-7", 7, "Merge into a buffer", "easy", "array", "fill from the back",
             "nums1 has length m+n: first m values sorted, last n are unused 0s. nums2 is n sorted values. Merge nums2 into nums1 in-place, sorted.",
             "Three pointers from the tails. The largest leftover writes at the end so you do not overwrite unread values.",
             "function merge(nums1, m, nums2, n) {\n  let i = m - 1, j = n - 1, w = m + n - 1;\n  while (j >= 0) {\n    if (i >= 0 && nums1[i] > nums2[j]) nums1[w--] = nums1[i--];\n    else nums1[w--] = nums2[j--];\n  }\n  return nums1;\n}",
             "O(m+n)", "O(1)"),
            ("tp-ar-8", 8, "Majority element", "easy", "array", "Boyer–Moore",
             "An element appears more than n/2 times. Return it. Follow-up: O(1) extra, one pass.",
             "Candidate + count. Matching increments, mismatch decrements, count 0 picks a new candidate. The majority always survives.",
             "function majorityElement(nums) {\n  let cand = null, count = 0;\n  for (const x of nums) {\n    if (count === 0) cand = x;\n    count += x === cand ? 1 : -1;\n  }\n  return cand;\n}",
             "O(n)", "O(1)"),
            ("tp-ar-9", 9, "Sort colors (Dutch flag)", "medium", "array", "three-way partition",
             "Array of 0, 1, 2 only. Sort in-place in one pass. No library sort.",
             "lo writes the next 0, hi the next 2, i scans. Swap 0 left, 2 right, stay on 2 because the inbound value is unknown.",
             "function sortColors(a) {\n  let lo = 0, i = 0, hi = a.length - 1;\n  while (i <= hi) {\n    if (a[i] === 0) { [a[lo], a[i]] = [a[i], a[lo]]; lo++; i++; }\n    else if (a[i] === 2) { [a[hi], a[i]] = [a[i], a[hi]]; hi--; }\n    else i++;\n  }\n  return a;\n}",
             "O(n)", "O(1)"),
            ("tp-ar-10", 10, "Pivot index", "easy", "array", "prefix vs suffix",
             "Index i where sum(left of i) === sum(right of i). Return the leftmost, or -1.",
             "Total sum once. Walk left-sum. Right = total - left - a[i].",
             "function pivotIndex(a) {\n  const total = a.reduce((s, x) => s + x, 0);\n  let left = 0;\n  for (let i = 0; i < a.length; i++) {\n    if (left === total - left - a[i]) return i;\n    left += a[i];\n  }\n  return -1;\n}",
             "O(n)", "O(1)"),
        ])


def strings_gym() -> str:
    return practice_gym("gym-strings", "Practice this topic — Strings",
        "Treat strings as immutable. Prefer two pointers on indexes, or split to a char array when you must write.",
        [
            ("tp-st-1", 1, "Reverse a character array", "easy", "string", "two pointers",
             "s is an array of characters. Reverse it in place.",
             "Swap from the ends inward. Do not build a new string in a loop.",
             "function reverseString(s) {\n  let lo = 0, hi = s.length - 1;\n  while (lo < hi) { [s[lo], s[hi]] = [s[hi], s[lo]]; lo++; hi--; }\n  return s;\n}",
             "O(n)", "O(1)"),
            ("tp-st-2", 2, "Longest common prefix", "easy", "string", "scan columns",
             "Array of strings. Longest prefix shared by every string, or \"\".",
             "Walk character columns of the first word. Stop at the first mismatch or short word.",
             "function longestCommonPrefix(strs) {\n  if (!strs.length) return \"\";\n  for (let i = 0; i < strs[0].length; i++) {\n    const ch = strs[0][i];\n    for (let k = 1; k < strs.length; k++) if (strs[k][i] !== ch) return strs[0].slice(0, i);\n  }\n  return strs[0];\n}",
             "O(total chars)", "O(1)"),
            ("tp-st-3", 3, "String compression", "medium", "string", "run-length write",
             "chars is a char array. Compress in-place: a,a,a,b,b → a,3,b,2. Return the new length. Groups of 1 stay a single letter.",
             "Read runs. Write the letter, then the digits of the count if count > 1.",
             "function compress(chars) {\n  let w = 0, r = 0;\n  while (r < chars.length) {\n    const ch = chars[r];\n    let n = 0;\n    while (r < chars.length && chars[r] === ch) { r++; n++; }\n    chars[w++] = ch;\n    if (n > 1) for (const d of String(n)) chars[w++] = d;\n  }\n  return w;\n}",
             "O(n)", "O(1) extra"),
            ("tp-st-4", 4, "Is subsequence", "easy", "string", "two pointers",
             "True if s is a subsequence of t (delete some chars of t, keep order).",
             "Advance i through s only when t[j] matches. Done if i reaches s.length.",
             "function isSubsequence(s, t) {\n  let i = 0;\n  for (let j = 0; j < t.length && i < s.length; j++) if (s[i] === t[j]) i++;\n  return i === s.length;\n}",
             "O(|t|)", "O(1)"),
            ("tp-st-5", 5, "Reverse vowels", "easy", "string", "skip non-vowels",
             "Reverse only the vowels in s. Other characters stay put.",
             "Two pointers. Move until both land on vowels, then swap.",
             "function reverseVowels(s) {\n  const a = s.split(\"\"), v = new Set(\"aeiouAEIOU\");\n  let lo = 0, hi = a.length - 1;\n  while (lo < hi) {\n    while (lo < hi && !v.has(a[lo])) lo++;\n    while (lo < hi && !v.has(a[hi])) hi--;\n    [a[lo], a[hi]] = [a[hi], a[lo]];\n    lo++; hi--;\n  }\n  return a.join(\"\");\n}",
             "O(n)", "O(n) for the array"),
            ("tp-st-6", 6, "Palindrome after one delete", "easy", "string", "one skip",
             "True if s is a palindrome, or can become one by deleting at most one character.",
             "On the first mismatch, try skipping left or skipping right. Helper checks a slice.",
             "function validPalindrome(s) {\n  const ok = (lo, hi) => {\n    while (lo < hi) if (s[lo++] !== s[hi--]) return false;\n    return true;\n  };\n  let lo = 0, hi = s.length - 1;\n  while (lo < hi) {\n    if (s[lo] !== s[hi]) return ok(lo + 1, hi) || ok(lo, hi - 1);\n    lo++; hi--;\n  }\n  return true;\n}",
             "O(n)", "O(1)"),
            ("tp-st-7", 7, "Add two numeric strings", "medium", "string", "digit carry",
             "num1 and num2 are non-negative integers as strings (may be huge). Return the sum as a string. No BigInt.",
             "Walk from the ends. Digit + digit + carry. Build an array and reverse-join.",
             "function addStrings(a, b) {\n  let i = a.length - 1, j = b.length - 1, carry = 0;\n  const out = [];\n  while (i >= 0 || j >= 0 || carry) {\n    const x = (i >= 0 ? a.charCodeAt(i--) - 48 : 0) + (j >= 0 ? b.charCodeAt(j--) - 48 : 0) + carry;\n    out.push(String(x % 10));\n    carry = Math.floor(x / 10);\n  }\n  return out.reverse().join(\"\");\n}",
             "O(n)", "O(n)"),
            ("tp-st-8", 8, "Repeated substring pattern", "easy", "string", "fold the string",
             "True if s is made by repeating a smaller string at least twice (\"abab\" yes, \"aba\" no).",
             "s+s without the first and last char contains s iff a period exists. Or try lengths that divide n.",
             "function repeatedSubstringPattern(s) {\n  return (s + s).slice(1, -1).includes(s);\n}",
             "O(n)", "O(n)"),
        ])


def hash_gym() -> str:
    return practice_gym("gym-hash", "Practice this topic — Hash maps and sets",
        "Default to <code>Map</code> / <code>Set</code>. Frequency, complement, and “have I seen this key” are the three muscles.",
        [
            ("tp-hm-1", 1, "Intersection of two arrays", "easy", "hash", "Set presence",
             "Return the distinct values that appear in both arrays. Order does not matter.",
             "Set of the smaller array. Scan the other, add to a result Set.",
             "function intersection(a, b) {\n  const set = new Set(a.length <= b.length ? a : b);\n  const other = a.length <= b.length ? b : a;\n  const out = new Set();\n  for (const x of other) if (set.has(x)) out.add(x);\n  return [...out];\n}",
             "O(n+m)", "O(min(n,m))"),
            ("tp-hm-2", 2, "Nearby duplicate", "easy", "hash", "index map",
             "True if some value appears twice with index distance ≤ k.",
             "Map value → last index. If i − last ≤ k, true. Update last.",
             "function containsNearbyDuplicate(nums, k) {\n  const last = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    if (last.has(nums[i]) && i - last.get(nums[i]) <= k) return true;\n    last.set(nums[i], i);\n  }\n  return false;\n}",
             "O(n)", "O(n)"),
            ("tp-hm-3", 3, "Isomorphic strings", "easy", "hash", "two maps",
             "True if you can rename letters of s to get t, one-to-one.",
             "s→t and t→s maps. A letter cannot map to two different letters either way. \"ab\" / \"aa\" is false.",
             "function isIsomorphic(s, t) {\n  if (s.length !== t.length) return false;\n  const st = new Map(), ts = new Map();\n  for (let i = 0; i < s.length; i++) {\n    if (st.has(s[i]) && st.get(s[i]) !== t[i]) return false;\n    if (ts.has(t[i]) && ts.get(t[i]) !== s[i]) return false;\n    st.set(s[i], t[i]); ts.set(t[i], s[i]);\n  }\n  return true;\n}",
             "O(n)", "O(alphabet)"),
            ("tp-hm-4", 4, "Word pattern", "easy", "hash", "bijection",
             "pattern \"abba\" and words \"dog cat cat dog\" match. Same rule as isomorphic, but tokens are words.",
             "Split s on spaces. Length must match. Two maps: char→word and word→char.",
             "function wordPattern(pattern, s) {\n  const words = s.split(\" \");\n  if (words.length !== pattern.length) return false;\n  const pw = new Map(), wp = new Map();\n  for (let i = 0; i < pattern.length; i++) {\n    const p = pattern[i], w = words[i];\n    if (pw.has(p) && pw.get(p) !== w) return false;\n    if (wp.has(w) && wp.get(w) !== p) return false;\n    pw.set(p, w); wp.set(w, p);\n  }\n  return true;\n}",
             "O(n)", "O(n)"),
            ("tp-hm-5", 5, "Happy number", "easy", "hash", "seen Set",
             "Replace a number by the sum of squares of its digits. True if you reach 1. False if you cycle.",
             "Set of seen values. Cycle ⇒ unhappy. Digit square loop is tiny.",
             "function isHappy(n) {\n  const seen = new Set();\n  while (n !== 1 && !seen.has(n)) {\n    seen.add(n);\n    let s = 0;\n    while (n) { const d = n % 10; s += d * d; n = Math.floor(n / 10); }\n    n = s;\n  }\n  return n === 1;\n}",
             "O(log n) per step, bounded cycle", "O(cycle length)"),
            ("tp-hm-6", 6, "Group anagrams", "medium", "hash", "canonical key",
             "Group words that are anagrams of each other.",
             "Key = sorted letters, or a 26-count signature joined. Map key → list.",
             "function groupAnagrams(strs) {\n  const m = new Map();\n  for (const w of strs) {\n    const k = [...w].sort().join(\"\");\n    if (!m.has(k)) m.set(k, []);\n    m.get(k).push(w);\n  }\n  return [...m.values()];\n}",
             "O(n · L log L)", "O(n L)"),
            ("tp-hm-7", 7, "Longest consecutive sequence", "medium", "hash", "start of a run",
             "Length of the longest consecutive run in an unsorted array (100,4,200,1,3,2 → 4). O(n) expected.",
             "Put all in a Set. Only start a run from x if x-1 is missing. Then walk x+1…",
             "function longestConsecutive(nums) {\n  const s = new Set(nums);\n  let best = 0;\n  for (const x of s) {\n    if (s.has(x - 1)) continue;\n    let y = x, n = 1;\n    while (s.has(y + 1)) { y++; n++; }\n    best = Math.max(best, n);\n  }\n  return best;\n}",
             "O(n)", "O(n)"),
            ("tp-hm-8", 8, "Find the added letter", "easy", "hash", "count cancel",
             "t is s plus one extra character (shuffled). Return that character.",
             "Count s, decrement with t, or XOR all char codes.",
             "function findTheDifference(s, t) {\n  let x = 0;\n  for (const ch of s) x ^= ch.charCodeAt(0);\n  for (const ch of t) x ^= ch.charCodeAt(0);\n  return String.fromCharCode(x);\n}",
             "O(n)", "O(1)"),
            ("tp-hm-9", 9, "Unique frequencies", "easy", "hash", "Set of counts",
             "True if no two values share the same frequency (\"1,2,2,3,3,3\" yes).",
             "Map value→count. Then a Set of those counts. Size must equal the number of distinct values.",
             "function uniqueOccurrences(arr) {\n  const f = new Map();\n  for (const x of arr) f.set(x, (f.get(x) || 0) + 1);\n  return new Set(f.values()).size === f.size;\n}",
             "O(n)", "O(n)"),
            ("tp-hm-10", 10, "Ransom note", "easy", "hash", "consume counts",
             "True if magazine letters can build ransomNote (each letter used at most once).",
             "Count magazine. Decrement while reading the note. Fail on missing or zero.",
             "function canConstruct(note, mag) {\n  const f = new Map();\n  for (const ch of mag) f.set(ch, (f.get(ch) || 0) + 1);\n  for (const ch of note) {\n    const n = f.get(ch) || 0;\n    if (!n) return false;\n    f.set(ch, n - 1);\n  }\n  return true;\n}",
             "O(n)", "O(alphabet)"),
        ])


def lists_gym() -> str:
    return practice_gym("gym-lists", "Practice this topic — Linked lists",
        "Draw arrows. Dummy node for head edits. Slow/fast for middle and palindrome.",
        [
            ("tp-ll-1", 1, "Remove all of a value", "easy", "list", "dummy + walk",
             "Delete every node whose val equals target. Return the new head.",
             "Dummy before head. While curr.next exists, skip it or step.",
             "function removeElements(head, val) {\n  const dummy = { val: 0, next: head };\n  let t = dummy;\n  while (t.next) {\n    if (t.next.val === val) t.next = t.next.next;\n    else t = t.next;\n  }\n  return dummy.next;\n}",
             "O(n)", "O(1)"),
            ("tp-ll-2", 2, "Delete duplicates in a sorted list", "easy", "list", "skip equals",
             "Sorted list. Leave one of each value.",
             "If curr.val === curr.next.val, skip next. Else step.",
             "function deleteDuplicates(head) {\n  let t = head;\n  while (t && t.next) {\n    if (t.val === t.next.val) t.next = t.next.next;\n    else t = t.next;\n  }\n  return head;\n}",
             "O(n)", "O(1)"),
            ("tp-ll-3", 3, "Intersection of two lists", "easy", "list", "equal remaining length",
             "Lists may share a tail (same node objects). Return the first shared node, or null.",
             "Walk A then B and B then A. Same leftover distance after the switch. Or count lengths and skip the prefix.",
             "function getIntersectionNode(a, b) {\n  let p = a, q = b;\n  while (p !== q) {\n    p = p ? p.next : b;\n    q = q ? q.next : a;\n  }\n  return p;\n}",
             "O(n+m)", "O(1)"),
            ("tp-ll-4", 4, "Palindrome list", "easy", "list", "reverse second half",
             "True if node values read the same forward and back. O(1) extra.",
             "Slow/fast to mid. Reverse the second half. Compare. (Optional: restore.)",
             "function isPalindrome(head) {\n  let s = head, f = head;\n  while (f && f.next) { s = s.next; f = f.next.next; }\n  let prev = null, curr = s;\n  while (curr) { const n = curr.next; curr.next = prev; prev = curr; curr = n; }\n  let a = head, b = prev;\n  while (b) { if (a.val !== b.val) return false; a = a.next; b = b.next; }\n  return true;\n}",
             "O(n)", "O(1)"),
            ("tp-ll-5", 5, "Add two numbers", "medium", "list", "digit carry",
             "Each list is a number stored reverse (1s place at the head). Return the sum as a list.",
             "Dummy. While either list or carry remains, write a node.",
             "function addTwoNumbers(a, b) {\n  const dummy = { val: 0, next: null };\n  let t = dummy, carry = 0;\n  while (a || b || carry) {\n    const x = (a ? a.val : 0) + (b ? b.val : 0) + carry;\n    t.next = { val: x % 10, next: null };\n    t = t.next;\n    carry = Math.floor(x / 10);\n    if (a) a = a.next;\n    if (b) b = b.next;\n  }\n  return dummy.next;\n}",
             "O(n)", "O(1) extra"),
            ("tp-ll-6", 6, "Swap nodes in pairs", "medium", "list", "rewire four pointers",
             "1→2→3→4 becomes 2→1→4→3. Swap nodes, not just values.",
             "Dummy. While two nodes ahead exist, reverse that pair and attach.",
             "function swapPairs(head) {\n  const dummy = { next: head };\n  let t = dummy;\n  while (t.next && t.next.next) {\n    const a = t.next, b = a.next;\n    a.next = b.next; b.next = a; t.next = b; t = a;\n  }\n  return dummy.next;\n}",
             "O(n)", "O(1)"),
            ("tp-ll-7", 7, "Odd-even list", "medium", "list", "two tails",
             "Group odd-positioned nodes, then even-positioned, keeping relative order. 1-based positions.",
             "odd and even tails. Connect odd tail to even head at the end.",
             "function oddEvenList(head) {\n  if (!head) return null;\n  let odd = head, even = head.next, evenHead = even;\n  while (even && even.next) {\n    odd.next = even.next; odd = odd.next;\n    even.next = odd.next; even = even.next;\n  }\n  odd.next = evenHead;\n  return head;\n}",
             "O(n)", "O(1)"),
            ("tp-ll-8", 8, "Rotate list right by k", "medium", "list", "close then cut",
             "Rotate the list k places to the right. k may be larger than n.",
             "Count n. k %= n. Connect tail to head (ring). Walk n-k-1 from old head, cut, new head is next.",
             "function rotateRight(head, k) {\n  if (!head || !head.next) return head;\n  let n = 1, t = head;\n  while (t.next) { t = t.next; n++; }\n  k %= n;\n  if (!k) return head;\n  t.next = head;\n  let cut = head;\n  for (let i = 0; i < n - k - 1; i++) cut = cut.next;\n  const neu = cut.next;\n  cut.next = null;\n  return neu;\n}",
             "O(n)", "O(1)"),
        ])


def stacks_gym() -> str:
    return practice_gym("gym-stacks", "Practice this topic — Stacks and queues",
        "Stack = most recent unmatched / next greater. Queue = time order. Never <code>shift</code> in a hot loop without saying the cost.",
        [
            ("tp-sk-1", 1, "Evaluate reverse Polish", "medium", "stack", "operands then op",
             "Tokens like [\"2\",\"1\",\"+\",\"3\",\"*\"] → 9. Operators + - * / (trunc toward 0).",
             "Push numbers. On an op, pop b then a, push a ⊕ b.",
             "function evalRPN(tokens) {\n  const st = [];\n  const op = {\n    \"+\": (a, b) => a + b,\n    \"-\": (a, b) => a - b,\n    \"*\": (a, b) => a * b,\n    \"/\": (a, b) => Math.trunc(a / b),\n  };\n  for (const t of tokens) {\n    if (op[t]) { const b = st.pop(), a = st.pop(); st.push(op[t](a, b)); }\n    else st.push(Number(t));\n  }\n  return st[0];\n}",
             "O(n)", "O(n)"),
            ("tp-sk-2", 2, "Next greater of subset", "easy", "stack", "monotonic decreasing",
             "nums1 is a subset of nums2. For each x in nums1, the next greater value to the right of x in nums2, or -1.",
             "Scan nums2. Pop while current is greater — that current is the answer for the popped value. Map value→next.",
             "function nextGreaterElement(nums1, nums2) {\n  const next = new Map(), st = [];\n  for (const x of nums2) {\n    while (st.length && x > st[st.length - 1]) next.set(st.pop(), x);\n    st.push(x);\n  }\n  return nums1.map((x) => next.has(x) ? next.get(x) : -1);\n}",
             "O(n)", "O(n)"),
            ("tp-sk-3", 3, "Asteroid collision", "medium", "stack", "cancel on contact",
             "Positive = right, negative = left. Same-direction pass. Opposite collide: smaller abs explodes; equal both explode.",
             "Stack of survivors. A new left-mover may keep crushing a right-moving top.",
             "function asteroidCollision(a) {\n  const st = [];\n  for (const x of a) {\n    let alive = true;\n    while (alive && x < 0 && st.length && st[st.length - 1] > 0) {\n      const top = st[st.length - 1];\n      if (top < -x) st.pop();\n      else { if (top === -x) st.pop(); alive = false; }\n    }\n    if (alive) st.push(x);\n  }\n  return st;\n}",
             "O(n)", "O(n)"),
            ("tp-sk-4", 4, "Decode string", "medium", "stack", "nested counts",
             "\"3[a2[c]]\" → \"accaccacc\". Digits may be multi-digit.",
             "Stack of [prevString, k]. On digit, build k. On [, push and reset. On ], pop and repeat.",
             "function decodeString(s) {\n  const st = [];\n  let cur = \"\", k = 0;\n  for (const ch of s) {\n    if (ch >= \"0\" && ch <= \"9\") k = k * 10 + Number(ch);\n    else if (ch === \"[\") { st.push([cur, k]); cur = \"\"; k = 0; }\n    else if (ch === \"]\") { const [prev, n] = st.pop(); cur = prev + cur.repeat(n); }\n    else cur += ch;\n  }\n  return cur;\n}",
             "O(output)", "O(output)"),
            ("tp-sk-5", 5, "Queue from two stacks", "easy", "stack", "lazy transfer",
             "Implement enqueue / dequeue / peek / empty using two stacks only.",
             "in-stack for enqueue. On dequeue, if out is empty, pour in→out (reverses order).",
             "class MyQueue {\n  constructor() { this.in = []; this.out = []; }\n  enqueue(x) { this.in.push(x); }\n  _pour() { if (!this.out.length) while (this.in.length) this.out.push(this.in.pop()); }\n  dequeue() { this._pour(); return this.out.pop(); }\n  peek() { this._pour(); return this.out[this.out.length - 1]; }\n  empty() { return !this.in.length && !this.out.length; }\n}",
             "Amortized O(1)", "O(n)"),
            ("tp-sk-6", 6, "Recent counter", "easy", "queue", "expire old pings",
             "ping(t) records a call at time t (ms). Return how many pings lie in [t-3000, t]. Calls come in order.",
             "Queue of timestamps. Pop from the front while < t-3000. Size is the answer.",
             "class RecentCounter {\n  constructor() { this.q = []; }\n  ping(t) {\n    this.q.push(t);\n    while (this.q[0] < t - 3000) this.q.shift();\n    return this.q.length;\n  }\n}",
             "O(1) amortized", "O(window)"),
            ("tp-sk-7", 7, "Moving average stream", "easy", "queue", "fixed window sum",
             "Class with window size k. next(val) returns the average of the last at most k values.",
             "Queue + running sum. If length > k, subtract the expired front.",
             "class MovingAverage {\n  constructor(k) { this.k = k; this.q = []; this.sum = 0; }\n  next(val) {\n    this.q.push(val); this.sum += val;\n    if (this.q.length > this.k) this.sum -= this.q.shift();\n    return this.sum / this.q.length;\n  }\n}",
             "O(1)", "O(k)"),
            ("tp-sk-8", 8, "Remove adjacent duplicates", "easy", "stack", "explode pairs",
             "\"abbaca\" → \"ca\". Repeatedly delete two adjacent equal letters.",
             "Stack. If top equals current, pop; else push. Join at the end.",
             "function removeDuplicates(s) {\n  const st = [];\n  for (const ch of s) {\n    if (st.length && st[st.length - 1] === ch) st.pop();\n    else st.push(ch);\n  }\n  return st.join(\"\");\n}",
             "O(n)", "O(n)"),
        ])


def recursion_gym() -> str:
    return practice_gym("gym-recursion", "Practice this topic — Recursion",
        "Name the base case, the smaller call, and how you combine. Memoize if the same n is asked twice.",
        [
            ("tp-rc-1", 1, "Power x^n", "medium", "recursion", "halve the exponent",
             "Compute x**n for integer n (may be negative). Do not loop n times.",
             "x^n = (x^(n/2))^2. Odd n multiplies one extra x. Negative: 1 / x^-n. Watch -2^31.",
             "function myPow(x, n) {\n  if (n === 0) return 1;\n  if (n < 0) return 1 / myPow(x, -n);\n  const half = myPow(x, Math.floor(n / 2));\n  return n % 2 ? half * half * x : half * half;\n}",
             "O(log n)", "O(log n) stack"),
            ("tp-rc-2", 2, "Generate parentheses", "medium", "recursion", "open/close counts",
             "All valid strings of n pairs of parentheses.",
             "Place '(' if open < n. Place ')' if close < open. Path is a char array.",
             "function generateParenthesis(n) {\n  const out = [];\n  function go(path, open, close) {\n    if (path.length === 2 * n) { out.push(path.join(\"\")); return; }\n    if (open < n) { path.push(\"(\"); go(path, open + 1, close); path.pop(); }\n    if (close < open) { path.push(\")\"); go(path, open, close + 1); path.pop(); }\n  }\n  go([], 0, 0);\n  return out;\n}",
             "Catalan · n", "O(n)"),
            ("tp-rc-3", 3, "Phone letter combinations", "medium", "recursion", "digit map",
             "digits is \"23\". Return all letter strings (ad, ae, …).",
             "Map 2–9 to letters. At index i, try each letter of digits[i].",
             "function letterCombinations(digits) {\n  if (!digits) return [];\n  const m = {2:\"abc\",3:\"def\",4:\"ghi\",5:\"jkl\",6:\"mno\",7:\"pqrs\",8:\"tuv\",9:\"wxyz\"};\n  const out = [];\n  function go(i, path) {\n    if (i === digits.length) { out.push(path.join(\"\")); return; }\n    for (const ch of m[digits[i]]) { path.push(ch); go(i + 1, path); path.pop(); }\n  }\n  go(0, []);\n  return out;\n}",
             "O(4^n n)", "O(n)"),
            ("tp-rc-4", 4, "Max depth of nested arrays", "easy", "recursion", "tree of arrays",
             "Nested number arrays, e.g. [1,[2,[3]]]. Depth of the deepest nest (that example is 3).",
             "A number is depth 1 if you count the current box, or 0 if you only count arrays — pick one and be consistent. Here: empty array is 1, number does not add a level beyond its container.",
             "function arrayDepth(x) {\n  if (!Array.isArray(x)) return 0;\n  if (!x.length) return 1;\n  return 1 + Math.max(0, ...x.map(arrayDepth));\n}",
             "O(nodes)", "O(depth)"),
            ("tp-rc-5", 5, "Fibonacci with memo", "easy", "recursion", "cache the state",
             "Return F(n) with F(0)=0, F(1)=1. Must be O(n), not the naive tree.",
             "Map or array cache. This is DP in recursive clothes.",
             "function fib(n, memo = new Map([[0, 0], [1, 1]])) {\n  if (memo.has(n)) return memo.get(n);\n  const v = fib(n - 1, memo) + fib(n - 2, memo);\n  memo.set(n, v);\n  return v;\n}",
             "O(n)", "O(n)"),
            ("tp-rc-6", 6, "K-th symbol in grammar", "medium", "recursion", "which half",
             "Row 1 is 0. Each 0 becomes 01, each 1 becomes 10. Return the k-th (1-based) bit in row n.",
             "Row n has 2^(n-1) bits. The second half is the first half flipped. Recurse into the half that contains k.",
             "function kthGrammar(n, k) {\n  if (n === 1) return 0;\n  const half = 1 << (n - 2);\n  if (k <= half) return kthGrammar(n - 1, k);\n  return 1 - kthGrammar(n - 1, k - half);\n}",
             "O(n)", "O(n)"),
        ])


def trees_gym() -> str:
    return practice_gym("gym-trees", "Practice this topic — Trees and BST",
        "Every tree problem is: null base, recurse children, combine. BFS when you care about levels.",
        [
            ("tp-tr-1", 1, "Invert a binary tree", "easy", "tree", "swap children",
             "Swap every left/right pair. Return the root.",
             "Recurse both sides, then swap — or swap then recurse. Same work.",
             "function invertTree(root) {\n  if (!root) return null;\n  const L = invertTree(root.left);\n  root.left = invertTree(root.right);\n  root.right = L;\n  return root;\n}",
             "O(n)", "O(h)"),
            ("tp-tr-2", 2, "Symmetric tree", "easy", "tree", "mirror pair",
             "True if the tree is a mirror of itself.",
             "Helper(a,b): both null, or vals equal and a.left mirrors b.right and a.right mirrors b.left.",
             "function isSymmetric(root) {\n  function same(a, b) {\n    if (!a || !b) return a === b;\n    return a.val === b.val && same(a.left, b.right) && same(a.right, b.left);\n  }\n  return same(root, root);\n}",
             "O(n)", "O(h)"),
            ("tp-tr-3", 3, "Path sum", "easy", "tree", "remaining target",
             "True if a root-to-leaf path sums to target.",
             "At a leaf, check val === remain. Else try children with remain - val.",
             "function hasPathSum(root, target) {\n  if (!root) return false;\n  if (!root.left && !root.right) return root.val === target;\n  return hasPathSum(root.left, target - root.val) || hasPathSum(root.right, target - root.val);\n}",
             "O(n)", "O(h)"),
            ("tp-tr-4", 4, "Diameter", "easy", "tree", "height + side path",
             "Longest number of edges on any path (need not pass through the root).",
             "Height function returns height and updates a global best = leftH + rightH.",
             "function diameterOfBinaryTree(root) {\n  let best = 0;\n  function h(n) {\n    if (!n) return 0;\n    const L = h(n.left), R = h(n.right);\n    best = Math.max(best, L + R);\n    return 1 + Math.max(L, R);\n  }\n  h(root);\n  return best;\n}",
             "O(n)", "O(h)"),
            ("tp-tr-5", 5, "LCA in a binary tree", "medium", "tree", "found in both sides",
             "Lowest common ancestor of p and q in a general binary tree (not necessarily BST).",
             "If root is null/p/q, return root. If both sides return non-null, root is LCA. Else bubble the non-null.",
             "function lowestCommonAncestor(root, p, q) {\n  if (!root || root === p || root === q) return root;\n  const L = lowestCommonAncestor(root.left, p, q);\n  const R = lowestCommonAncestor(root.right, p, q);\n  return L && R ? root : L || R;\n}",
             "O(n)", "O(h)"),
            ("tp-tr-6", 6, "Count good nodes", "medium", "tree", "max on the path",
             "A node is good if it is the maximum on the path from the root to itself. Count them.",
             "DFS with maxSoFar. If node.val >= maxSoFar, count 1.",
             "function goodNodes(root) {\n  function go(n, mx) {\n    if (!n) return 0;\n    const good = n.val >= mx ? 1 : 0;\n    const next = Math.max(mx, n.val);\n    return good + go(n.left, next) + go(n.right, next);\n  }\n  return go(root, -Infinity);\n}",
             "O(n)", "O(h)"),
            ("tp-tr-7", 7, "Right side view", "medium", "tree", "last on each level",
             "Values you see standing on the right, top to bottom.",
             "BFS. The last node in each level is visible. DFS: visit right first and record the first visit at each depth.",
             "function rightSideView(root) {\n  if (!root) return [];\n  const q = [root], out = [];\n  while (q.length) {\n    const n = q.length;\n    for (let i = 0; i < n; i++) {\n      const node = q.shift();\n      if (i === n - 1) out.push(node.val);\n      if (node.left) q.push(node.left);\n      if (node.right) q.push(node.right);\n    }\n  }\n  return out;\n}",
             "O(n)", "O(w)"),
            ("tp-tr-8", 8, "Flatten to a linked list", "medium", "tree", "preorder rewind",
             "Flatten the tree into a right-skewed list in preorder. left must become null. Do it in place.",
             "Recurse right, then left. A trailing prev pointer: node.right = prev; node.left = null; prev = node. Walk from the right.",
             "function flatten(root) {\n  let prev = null;\n  function go(n) {\n    if (!n) return;\n    go(n.right); go(n.left);\n    n.right = prev; n.left = null; prev = n;\n  }\n  go(root);\n}",
             "O(n)", "O(h)"),
            ("tp-tr-9", 9, "Kth smallest in a BST", "medium", "tree", "inorder count",
             "1-based k. BST inorder is sorted.",
             "Iterative inorder, decrement k on each pop. When k hits 0, that node is the answer.",
             "function kthSmallest(root, k) {\n  const st = [];\n  let n = root;\n  while (st.length || n) {\n    while (n) { st.push(n); n = n.left; }\n    n = st.pop();\n    if (--k === 0) return n.val;\n    n = n.right;\n  }\n}",
             "O(h+k)", "O(h)"),
            ("tp-tr-10", 10, "Range sum of BST", "easy", "tree", "prune branches",
             "Sum of BST values in [low, high]. Skip whole subtrees you cannot need.",
             "If val < low, only go right. If val > high, only go left. Else add and go both.",
             "function rangeSumBST(root, low, high) {\n  if (!root) return 0;\n  if (root.val < low) return rangeSumBST(root.right, low, high);\n  if (root.val > high) return rangeSumBST(root.left, low, high);\n  return root.val + rangeSumBST(root.left, low, high) + rangeSumBST(root.right, low, high);\n}",
             "O(n)", "O(h)"),
        ])


def heaps_gym() -> str:
    return practice_gym("gym-heaps", "Practice this topic — Heaps",
        "You implement the heap in this course. For fluency: top-k, stream, and “always the current min.”",
        [
            ("tp-hp-1", 1, "Last stone weight", "easy", "heap", "max twice",
             "Smash the two heaviest. If unequal, push the difference. Last stone (or 0).",
             "Max-heap (negate in a min-heap, or sort each time for n≤30). Pop two, push |a-b| if nonzero.",
             "function lastStoneWeight(stones) {\n  const h = stones.slice().sort((a, b) => a - b);\n  while (h.length > 1) {\n    const a = h.pop(), b = h.pop();\n    if (a !== b) {\n      h.push(a - b);\n      h.sort((x, y) => x - y);\n    }\n  }\n  return h[0] || 0;\n}\n// Interview: replace sort-each-time with a max-heap O(n log n).",
             "O(n² log n) sort-cheat / O(n log n) heap", "O(n)"),
            ("tp-hp-2", 2, "K closest points to origin", "medium", "heap", "max-heap of size k",
             "points[i] = [x,y]. Return k points with smallest x²+y². Order in the answer does not matter.",
             "Max-heap of size k by distance. Or sort. Say both.",
             "function kClosest(points, k) {\n  return points\n    .slice()\n    .sort((p, q) => p[0]*p[0] + p[1]*p[1] - (q[0]*q[0] + q[1]*q[1]))\n    .slice(0, k);\n}",
             "O(n log n) sort / O(n log k) heap", "O(k)"),
            ("tp-hp-3", 3, "Kth largest with a min-heap", "medium", "heap", "cap at k",
             "Kth largest in an unsorted array. Use a min-heap of size k (do not only sort).",
             "Push; if size > k, pop. The root is the answer.",
             "function findKthLargest(nums, k) {\n  const h = [];\n  const up = (i) => { while (i) { const p = (i-1)>>1; if (h[p] <= h[i]) break; [h[p],h[i]]=[h[i],h[p]]; i=p; } };\n  const down = (i) => { for (;;) { let s=i,l=2*i+1,r=l+1; if (l<h.length && h[l]<h[s]) s=l; if (r<h.length && h[r]<h[s]) s=r; if (s===i) break; [h[s],h[i]]=[h[i],h[s]]; i=s; } };\n  for (const x of nums) {\n    h.push(x); up(h.length-1);\n    if (h.length > k) { h[0] = h.pop(); if (h.length) down(0); }\n  }\n  return h[0];\n}",
             "O(n log k)", "O(k)"),
            ("tp-hp-4", 4, "Kth largest in a stream", "easy", "heap", "online cap",
             "Class(k, nums) then add(val) returns the current kth largest after each add.",
             "Same min-heap of size k, seeded with nums.",
             "class KthLargest {\n  constructor(k, nums) {\n    this.k = k; this.h = [];\n    for (const x of nums) this.add(x);\n  }\n  add(val) {\n    this.h.push(val);\n    this.h.sort((a, b) => a - b);\n    if (this.h.length > this.k) this.h.shift();\n    return this.h[0];\n  }\n}\n// Replace sort/shift with a real heap in an interview.",
             "O(log k) with a heap", "O(k)"),
            ("tp-hp-5", 5, "Sort a k-sorted array", "medium", "heap", "window of k+1",
             "Every element is at most k positions from its sorted index. Sort in better than n log n when k ≪ n.",
             "Min-heap of the first k+1 values. Pop into the write index, push the next.",
             "function sortKSorted(a, k) {\n  const h = a.slice(0, k + 1).sort((x, y) => x - y);\n  const out = [];\n  for (let i = k + 1; i < a.length; i++) {\n    out.push(h.shift());\n    h.push(a[i]);\n    h.sort((x, y) => x - y);\n  }\n  while (h.length) out.push(h.shift());\n  return out;\n}",
             "O(n log k) with a heap", "O(k)"),
            ("tp-hp-6", 6, "Median of a stream", "hard", "heap", "two heaps",
             "addNum and findMedian. Median is middle or average of two middles.",
             "Max-heap for the lower half, min-heap for the upper. Sizes differ by at most 1. Rebalance after each insert.",
             "class MedianFinder {\n  constructor() { this.lo = []; this.hi = []; } // lo max via negate, hi min — here we sort for the idea\n  addNum(x) {\n    this.lo.push(x); this.lo.sort((a, b) => a - b);\n    this.hi.push(this.lo.pop()); this.hi.sort((a, b) => a - b);\n    if (this.hi.length > this.lo.length) this.lo.push(this.hi.shift());\n    this.lo.sort((a, b) => a - b);\n  }\n  findMedian() {\n    if (this.lo.length > this.hi.length) return this.lo[this.lo.length - 1];\n    return (this.lo[this.lo.length - 1] + this.hi[0]) / 2;\n  }\n}\n// Real answer: binary heaps, not sort. This is the split invariant.",
             "O(log n) with heaps", "O(n)"),
        ])


def graphs_gym() -> str:
    return practice_gym("gym-graphs", "Practice this topic — Graphs",
        "Adj list + seen set. BFS for hops. Flood a grid. Kahn when order matters.",
        [
            ("tp-gr-1", 1, "Flood fill", "easy", "graph", "DFS/BFS paint",
             "image[sr][sc] starts a fill. Recolor every 4-connected pixel of the same old color.",
             "If new color equals old, return. Else DFS/BFS the component.",
             "function floodFill(image, sr, sc, color) {\n  const old = image[sr][sc];\n  if (old === color) return image;\n  const R = image.length, C = image[0].length;\n  function go(r, c) {\n    if (r<0||c<0||r>=R||c>=C||image[r][c]!==old) return;\n    image[r][c] = color;\n    go(r+1,c); go(r-1,c); go(r,c+1); go(r,c-1);\n  }\n  go(sr, sc);\n  return image;\n}",
             "O(RC)", "O(RC)"),
            ("tp-gr-2", 2, "Max area of island", "medium", "graph", "size the component",
             "1 = land. Return the largest 4-connected island area (0 if none).",
             "DFS returns 1 + sum of neighbors after sinking the cell.",
             "function maxAreaOfIsland(grid) {\n  const R = grid.length, C = grid[0].length;\n  function area(r, c) {\n    if (r<0||c<0||r>=R||c>=C||grid[r][c]!==1) return 0;\n    grid[r][c] = 0;\n    return 1 + area(r+1,c) + area(r-1,c) + area(r,c+1) + area(r,c-1);\n  }\n  let best = 0;\n  for (let r=0;r<R;r++) for (let c=0;c<C;c++) best = Math.max(best, area(r,c));\n  return best;\n}",
             "O(RC)", "O(RC)"),
            ("tp-gr-3", 3, "Rotting oranges", "medium", "graph", "multi-source BFS",
             "0 empty, 1 fresh, 2 rotten. Each minute, rotten infects 4-neighbors. Minutes until no fresh, or -1.",
             "Enqueue every rotten at minute 0. BFS. Count fresh; fail if leftover.",
             "function orangesRotting(grid) {\n  const R = grid.length, C = grid[0].length, q = [];\n  let fresh = 0, minutes = 0;\n  for (let r=0;r<R;r++) for (let c=0;c<C;c++) {\n    if (grid[r][c]===2) q.push([r,c,0]);\n    if (grid[r][c]===1) fresh++;\n  }\n  const dirs = [[1,0],[-1,0],[0,1],[0,-1]];\n  for (let i = 0; i < q.length; i++) {\n    const [r,c,d] = q[i];\n    minutes = d;\n    for (const [dr,dc] of dirs) {\n      const nr=r+dr, nc=c+dc;\n      if (nr<0||nc<0||nr>=R||nc>=C||grid[nr][nc]!==1) continue;\n      grid[nr][nc]=2; fresh--; q.push([nr,nc,d+1]);\n    }\n  }\n  return fresh ? -1 : minutes;\n}",
             "O(RC)", "O(RC)"),
            ("tp-gr-4", 4, "Keys and rooms", "medium", "graph", "reachability",
             "rooms[i] is a list of keys. Start in room 0. True if you can open every room.",
             "DFS/BFS from 0 following keys. seen.size === n.",
             "function canVisitAllRooms(rooms) {\n  const seen = new Set([0]), st = [0];\n  while (st.length) {\n    const u = st.pop();\n    for (const k of rooms[u]) if (!seen.has(k)) { seen.add(k); st.push(k); }\n  }\n  return seen.size === rooms.length;\n}",
             "O(n+keys)", "O(n)"),
            ("tp-gr-5", 5, "Course order", "medium", "graph", "Kahn list",
             "n courses, prereqs [a,b] means b before a. Return a valid order, or [] if a cycle.",
             "Same as canFinish, but record the pop order.",
             "function findOrder(n, pre) {\n  const adj = Array.from({length:n}, () => []), indeg = Array(n).fill(0);\n  for (const [a,b] of pre) { adj[b].push(a); indeg[a]++; }\n  const q = [], out = [];\n  for (let i=0;i<n;i++) if (!indeg[i]) q.push(i);\n  while (q.length) {\n    const u = q.shift(); out.push(u);\n    for (const v of adj[u]) if (--indeg[v]===0) q.push(v);\n  }\n  return out.length === n ? out : [];\n}",
             "O(V+E)", "O(V+E)"),
            ("tp-gr-6", 6, "Number of provinces", "medium", "graph", "components",
             "isConnected[i][j] is 1 if cities i and j are linked (undirected). Count connected components.",
             "DFS from each unvisited city. Or union-find on the matrix.",
             "function findCircleNum(g) {\n  const n = g.length, seen = Array(n).fill(false);\n  function dfs(i) {\n    seen[i] = true;\n    for (let j = 0; j < n; j++) if (g[i][j] && !seen[j]) dfs(j);\n  }\n  let p = 0;\n  for (let i = 0; i < n; i++) if (!seen[i]) { p++; dfs(i); }\n  return p;\n}",
             "O(n²)", "O(n)"),
            ("tp-gr-7", 7, "01 matrix nearest zero", "medium", "graph", "multi-source BFS",
             "For each cell, distance to the nearest 0. 4-direction.",
             "Enqueue all zeros at dist 0. First visit to a 1 is the shortest.",
             "function updateMatrix(mat) {\n  const R = mat.length, C = mat[0].length;\n  const dist = Array.from({length:R}, () => Array(C).fill(Infinity));\n  const q = [];\n  for (let r=0;r<R;r++) for (let c=0;c<C;c++) if (mat[r][c]===0) { dist[r][c]=0; q.push([r,c]); }\n  const dirs = [[1,0],[-1,0],[0,1],[0,-1]];\n  for (let i=0;i<q.length;i++) {\n    const [r,c] = q[i];\n    for (const [dr,dc] of dirs) {\n      const nr=r+dr,nc=c+dc;\n      if (nr<0||nc<0||nr>=R||nc>=C||dist[nr][nc]<=dist[r][c]+1) continue;\n      dist[nr][nc]=dist[r][c]+1; q.push([nr,nc]);\n    }\n  }\n  return dist;\n}",
             "O(RC)", "O(RC)"),
            ("tp-gr-8", 8, "Shortest path in a binary matrix", "medium", "graph", "8-dir BFS",
             "n×n grid, 0 is open, 1 blocked. Shortest 8-connected path from [0,0] to [n-1,n-1], or -1. Length counts cells.",
             "BFS. Mark visited when enqueue. Clear start/end first.",
             "function shortestPathBinaryMatrix(g) {\n  const n = g.length;\n  if (g[0][0] || g[n-1][n-1]) return -1;\n  const q = [[0,0,1]]; g[0][0] = 1;\n  const dirs = [-1,0,1].flatMap((dr) => [-1,0,1].map((dc) => [dr,dc])).filter(([a,b]) => a||b);\n  for (let i=0;i<q.length;i++) {\n    const [r,c,d] = q[i];\n    if (r===n-1 && c===n-1) return d;\n    for (const [dr,dc] of dirs) {\n      const nr=r+dr,nc=c+dc;\n      if (nr<0||nc<0||nr>=n||nc>=n||g[nr][nc]) continue;\n      g[nr][nc]=1; q.push([nr,nc,d+1]);\n    }\n  }\n  return -1;\n}",
             "O(n²)", "O(n²)"),
        ])


def sort_gym() -> str:
    return practice_gym("gym-sort", "Practice this topic — Sorting and search",
        "Comparator on numbers. Binary search: know whether you want a hit or the first true.",
        [
            ("tp-ss-1", 1, "Search insert position", "easy", "search", "lower bound",
             "Sorted unique array. Index of target, or where it would be inserted.",
             "Classic lower bound. lo < hi, mid, pred = a[mid] >= target.",
             "function searchInsert(a, t) {\n  let lo = 0, hi = a.length;\n  while (lo < hi) {\n    const m = (lo + hi) >> 1;\n    if (a[m] >= t) hi = m; else lo = m + 1;\n  }\n  return lo;\n}",
             "O(log n)", "O(1)"),
            ("tp-ss-2", 2, "First and last position", "medium", "search", "two bounds",
             "Sorted array with duplicates. [first, last] index of target, or [-1,-1].",
             "lowerBound(target) and lowerBound(target+1)-1. Check the value.",
             "function searchRange(a, t) {\n  const lb = (x) => { let lo=0, hi=a.length; while (lo<hi) { const m=(lo+hi)>>1; if (a[m]>=x) hi=m; else lo=m+1; } return lo; };\n  const L = lb(t), R = lb(t + 1) - 1;\n  if (L >= a.length || a[L] !== t) return [-1, -1];\n  return [L, R];\n}",
             "O(log n)", "O(1)"),
            ("tp-ss-3", 3, "Find peak element", "medium", "search", "uphill half",
             "A peak is strictly greater than neighbors (ends compare one side). Return any peak index. O(log n).",
             "If a[mid] < a[mid+1], a peak exists on the right. Else on the left (including mid).",
             "function findPeakElement(a) {\n  let lo = 0, hi = a.length - 1;\n  while (lo < hi) {\n    const m = (lo + hi) >> 1;\n    if (a[m] < a[m + 1]) lo = m + 1;\n    else hi = m;\n  }\n  return lo;\n}",
             "O(log n)", "O(1)"),
            ("tp-ss-4", 4, "Koko eating bananas", "medium", "search", "binary on answer",
             "piles of bananas, h hours. Min eat-speed k so she finishes. She eats one pile per hour (ceil(pile/k)).",
             "lo=1, hi=max pile. Feasible(k) = hours needed ≤ h. First true k.",
             "function minEatingSpeed(piles, h) {\n  const ok = (k) => piles.reduce((s, p) => s + Math.ceil(p / k), 0) <= h;\n  let lo = 1, hi = Math.max(...piles);\n  while (lo < hi) {\n    const m = (lo + hi) >> 1;\n    if (ok(m)) hi = m; else lo = m + 1;\n  }\n  return lo;\n}",
             "O(n log max)", "O(1)"),
            ("tp-ss-5", 5, "Min in rotated sorted unique", "medium", "search", "unsorted half",
             "Rotated sorted unique array. Return the minimum.",
             "If a[mid] > a[hi], min is to the right of mid. Else min is at mid or left.",
             "function findMin(a) {\n  let lo = 0, hi = a.length - 1;\n  while (lo < hi) {\n    const m = (lo + hi) >> 1;\n    if (a[m] > a[hi]) lo = m + 1;\n    else hi = m;\n  }\n  return a[lo];\n}",
             "O(log n)", "O(1)"),
            ("tp-ss-6", 6, "Ship packages within D days", "medium", "search", "capacity search",
             "weights in order (cannot reorder). Min ship capacity to finish in days days.",
             "Same binary-on-answer. Feasible: greedy pack until the next weight would overflow, start a new day.",
             "function shipWithinDays(weights, days) {\n  const ok = (cap) => {\n    let d = 1, load = 0;\n    for (const w of weights) {\n      if (load + w > cap) { d++; load = 0; }\n      load += w;\n    }\n    return d <= days;\n  };\n  let lo = Math.max(...weights), hi = weights.reduce((s, w) => s + w, 0);\n  while (lo < hi) {\n    const m = (lo + hi) >> 1;\n    if (ok(m)) hi = m; else lo = m + 1;\n  }\n  return lo;\n}",
             "O(n log sum)", "O(1)"),
        ])


def twopointer_gym() -> str:
    return practice_gym("gym-twopointer", "Practice this topic — Two pointers",
        "Opposite ends need a sorted invariant (or a height argument). Same direction is a write pointer.",
        [
            ("tp-tp-1", 1, "Squares of a sorted array", "easy", "twopointer", "fill from the back",
             "Sorted array (may have negatives). Return squares, sorted.",
             "Largest square is at one of the ends. Fill out from the right.",
             "function sortedSquares(a) {\n  const out = Array(a.length);\n  let lo = 0, hi = a.length - 1, w = hi;\n  while (lo <= hi) {\n    if (Math.abs(a[lo]) > Math.abs(a[hi])) out[w--] = a[lo] * a[lo++];\n    else out[w--] = a[hi] * a[hi--];\n  }\n  return out;\n}",
             "O(n)", "O(n)"),
            ("tp-tp-2", 2, "Two sum II (1-indexed)", "easy", "twopointer", "sorted ends",
             "1-indexed sorted array. Two numbers that add to target. Exactly one solution. Constant extra space.",
             "lo/hi. Too small, lo++. Too big, hi--.",
             "function twoSum(a, target) {\n  let lo = 0, hi = a.length - 1;\n  while (lo < hi) {\n    const s = a[lo] + a[hi];\n    if (s === target) return [lo + 1, hi + 1];\n    if (s < target) lo++; else hi--;\n  }\n}",
             "O(n)", "O(1)"),
            ("tp-tp-3", 3, "3Sum closest", "medium", "twopointer", "track best",
             "Triplet whose sum is closest to target. Return that sum.",
             "Sort. Fix i. Two pointers. Update best by absolute distance. Skip dups on i.",
             "function threeSumClosest(nums, target) {\n  nums.sort((a, b) => a - b);\n  let best = nums[0] + nums[1] + nums[2];\n  for (let i = 0; i < nums.length - 2; i++) {\n    let lo = i + 1, hi = nums.length - 1;\n    while (lo < hi) {\n      const s = nums[i] + nums[lo] + nums[hi];\n      if (Math.abs(s - target) < Math.abs(best - target)) best = s;\n      if (s < target) lo++; else if (s > target) hi--; else return s;\n    }\n  }\n  return best;\n}",
             "O(n²)", "O(1)"),
            ("tp-tp-4", 4, "Boats to save people", "medium", "twopointer", "fattest + lightest",
             "people[i] is weight. Boat holds at most 2 people, limit weight. Min boats.",
             "Sort. If lightest + heaviest fit, take both; else heaviest alone.",
             "function numRescueBoats(people, limit) {\n  people.sort((a, b) => a - b);\n  let lo = 0, hi = people.length - 1, boats = 0;\n  while (lo <= hi) {\n    if (people[lo] + people[hi] <= limit) lo++;\n    hi--; boats++;\n  }\n  return boats;\n}",
             "O(n log n)", "O(1)"),
            ("tp-tp-5", 5, "Valid triangle count", "medium", "twopointer", "a+b>c after sort",
             "Count triplets that can form a triangle (strict inequality).",
             "Sort. Fix the largest side k. Two pointers on [0,k) counting pairs that sum > a[k].",
             "function triangleNumber(a) {\n  a.sort((x, y) => x - y);\n  let n = 0;\n  for (let k = a.length - 1; k >= 2; k--) {\n    let lo = 0, hi = k - 1;\n    while (lo < hi) {\n      if (a[lo] + a[hi] > a[k]) { n += hi - lo; hi--; }\n      else lo++;\n    }\n  }\n  return n;\n}",
             "O(n²)", "O(1)"),
            ("tp-tp-6", 6, "Interval intersection", "medium", "twopointer", "two lists walk",
             "Two lists of disjoint sorted intervals. Return their intersections.",
             "Advance the interval that ends first. Overlap is max(start) .. min(end) when that is valid.",
             "function intervalIntersection(A, B) {\n  const out = [];\n  let i = 0, j = 0;\n  while (i < A.length && j < B.length) {\n    const lo = Math.max(A[i][0], B[j][0]), hi = Math.min(A[i][1], B[j][1]);\n    if (lo <= hi) out.push([lo, hi]);\n    if (A[i][1] < B[j][1]) i++; else j++;\n  }\n  return out;\n}",
             "O(n+m)", "O(1) extra"),
        ])


def window_gym() -> str:
    return practice_gym("gym-window", "Practice this topic — Sliding window",
        "Right always moves. Left moves while the window is illegal. Each index enters/leaves once.",
        [
            ("tp-wd-1", 1, "Max average subarray", "easy", "window", "fixed k",
             "Max average of any contiguous subarray of length k.",
             "Fixed window sum. Slide: add right, drop left. Track max sum, divide once.",
             "function findMaxAverage(a, k) {\n  let sum = 0;\n  for (let i = 0; i < k; i++) sum += a[i];\n  let best = sum;\n  for (let i = k; i < a.length; i++) {\n    sum += a[i] - a[i - k];\n    best = Math.max(best, sum);\n  }\n  return best / k;\n}",
             "O(n)", "O(1)"),
            ("tp-wd-2", 2, "Longest ones after k flips", "medium", "window", "count zeros",
             "Binary array. Longest window that contains at most k zeros (those are the flips).",
             "Grow right. While zeros > k, if left was 0 decrement, left++.",
             "function longestOnes(a, k) {\n  let left = 0, zeros = 0, best = 0;\n  for (let r = 0; r < a.length; r++) {\n    if (a[r] === 0) zeros++;\n    while (zeros > k) { if (a[left++] === 0) zeros--; }\n    best = Math.max(best, r - left + 1);\n  }\n  return best;\n}",
             "O(n)", "O(1)"),
            ("tp-wd-3", 3, "Find all anagrams", "medium", "window", "need map",
             "Start indexes in s where a permutation of p begins.",
             "Need counts of p. Window of length p. A 'match' counter of 26 letters that currently agree.",
             "function findAnagrams(s, p) {\n  if (s.length < p.length) return [];\n  const need = Array(26).fill(0), win = Array(26).fill(0);\n  for (const ch of p) need[ch.charCodeAt(0) - 97]++;\n  const out = [];\n  for (let i = 0; i < s.length; i++) {\n    win[s.charCodeAt(i) - 97]++;\n    if (i >= p.length) win[s.charCodeAt(i - p.length) - 97]--;\n    if (i >= p.length - 1 && need.every((n, j) => n === win[j])) out.push(i - p.length + 1);\n  }\n  return out;\n}",
             "O(n)", "O(1)"),
            ("tp-wd-4", 4, "Minimum window substring", "hard", "window", "cover then shrink",
             "Smallest substring of s that covers every char of t (including duplicates). \"\" if impossible.",
             "Need map + missing count. Grow right. When missing is 0, shrink left and record best.",
             "function minWindow(s, t) {\n  const need = new Map();\n  for (const ch of t) need.set(ch, (need.get(ch) || 0) + 1);\n  let missing = t.length, best = \"\", bestLen = Infinity, left = 0;\n  for (let r = 0; r < s.length; r++) {\n    if (need.has(s[r])) {\n      if (need.get(s[r]) > 0) missing--;\n      need.set(s[r], need.get(s[r]) - 1);\n    }\n    while (!missing) {\n      if (r - left + 1 < bestLen) { bestLen = r - left + 1; best = s.slice(left, r + 1); }\n      if (need.has(s[left])) {\n        need.set(s[left], need.get(s[left]) + 1);\n        if (need.get(s[left]) > 0) missing++;\n      }\n      left++;\n    }\n  }\n  return best;\n}",
             "O(n)", "O(alphabet)"),
            ("tp-wd-5", 5, "Subarray product less than k", "medium", "window", "shrink product",
             "Count contiguous subarrays whose product is < k. All nums are positive.",
             "Product is monotonic while all positive. Grow right, divide out left while product >= k. Then add (r-left+1).",
             "function numSubarrayProductLessThanK(a, k) {\n  if (k <= 1) return 0;\n  let prod = 1, left = 0, n = 0;\n  for (let r = 0; r < a.length; r++) {\n    prod *= a[r];\n    while (prod >= k) prod /= a[left++];\n    n += r - left + 1;\n  }\n  return n;\n}",
             "O(n)", "O(1)"),
            ("tp-wd-6", 6, "Fruit into baskets", "medium", "window", "two types",
             "Array of fruit types. Longest subarray with at most two distinct types.",
             "Map of counts in the window. Shrink while map.size > 2.",
             "function totalFruit(fruits) {\n  const f = new Map();\n  let left = 0, best = 0;\n  for (let r = 0; r < fruits.length; r++) {\n    f.set(fruits[r], (f.get(fruits[r]) || 0) + 1);\n    while (f.size > 2) {\n      const x = fruits[left++];\n      f.set(x, f.get(x) - 1);\n      if (!f.get(x)) f.delete(x);\n    }\n    best = Math.max(best, r - left + 1);\n  }\n  return best;\n}",
             "O(n)", "O(1)"),
        ])


def backtrack_gym() -> str:
    return practice_gym("gym-backtrack", "Practice this topic — Backtracking",
        "Choose, recurse, pop. Copy the path when you store it. Sort + skip to kill duplicates.",
        [
            ("tp-bt-1", 1, "Combination sum II", "medium", "backtrack", "each number once",
             "candidates may contain duplicates. Each index used at most once. Unique combinations that sum to target.",
             "Sort. At a depth, skip nums[i] === nums[i-1] when i > start. Advance i+1 (no reuse).",
             "function combinationSum2(cands, target) {\n  cands.sort((a, b) => a - b);\n  const out = [], path = [];\n  function go(start, left) {\n    if (left === 0) { out.push(path.slice()); return; }\n    for (let i = start; i < cands.length && cands[i] <= left; i++) {\n      if (i > start && cands[i] === cands[i - 1]) continue;\n      path.push(cands[i]); go(i + 1, left - cands[i]); path.pop();\n    }\n  }\n  go(0, target);\n  return out;\n}",
             "exponential", "O(n)"),
            ("tp-bt-2", 2, "Palindrome partition", "medium", "backtrack", "cut when palindrome",
             "Partition s so every piece is a palindrome. Return all partitions.",
             "From start, try every end. If s[start..i] is a palindrome, recurse on i+1.",
             "function partition(s) {\n  const out = [], path = [];\n  const pal = (lo, hi) => { while (lo < hi) if (s[lo++] !== s[hi--]) return false; return true; };\n  function go(start) {\n    if (start === s.length) { out.push(path.slice()); return; }\n    for (let i = start; i < s.length; i++) {\n      if (!pal(start, i)) continue;\n      path.push(s.slice(start, i + 1)); go(i + 1); path.pop();\n    }\n  }\n  go(0);\n  return out;\n}",
             "O(n · 2^n)", "O(n)"),
            ("tp-bt-3", 3, "Restore IP addresses", "medium", "backtrack", "1–3 digits",
             "s is digits only. All valid IPv4 restorations (four parts, 0–255, no leading zeros unless the part is 0).",
             "At most 4 parts. Try length 1–3. Reject leading zeros and >255.",
             "function restoreIpAddresses(s) {\n  const out = [], path = [];\n  function go(i) {\n    if (path.length === 4) { if (i === s.length) out.push(path.join(\".\")); return; }\n    for (let len = 1; len <= 3 && i + len <= s.length; len++) {\n      const part = s.slice(i, i + len);\n      if ((part.length > 1 && part[0] === \"0\") || Number(part) > 255) continue;\n      path.push(part); go(i + len); path.pop();\n    }\n  }\n  go(0);\n  return out;\n}",
             "O(1) — n ≤ 12", "O(1)"),
            ("tp-bt-4", 4, "Letter case permutation", "medium", "backtrack", "digit stay / letter fork",
             "s has letters and digits. All strings you can make by toggling letter case.",
             "If digit, only one branch. If letter, two: lower and upper.",
             "function letterCasePermutation(s) {\n  const out = [], a = s.split(\"\");\n  function go(i) {\n    if (i === a.length) { out.push(a.join(\"\")); return; }\n    if (a[i] < \"A\") { go(i + 1); return; }\n    a[i] = a[i].toLowerCase(); go(i + 1);\n    a[i] = a[i].toUpperCase(); go(i + 1);\n  }\n  go(0);\n  return out;\n}",
             "O(n 2^L)", "O(n)"),
            ("tp-bt-5", 5, "N-queens (n = 4 first)", "hard", "backtrack", "cols and diagonals",
             "Place n queens so none attack. Return all boards as string arrays. Practice n=4, then n=8.",
             "cols, diag (r-c), adiag (r+c) sets. Place row by row.",
             "function solveNQueens(n) {\n  const cols = new Set(), d = new Set(), a = new Set(), board = Array.from({length:n}, () => Array(n).fill(\".\")), out = [];\n  function go(r) {\n    if (r === n) { out.push(board.map((row) => row.join(\"\"))); return; }\n    for (let c = 0; c < n; c++) {\n      if (cols.has(c) || d.has(r - c) || a.has(r + c)) continue;\n      cols.add(c); d.add(r - c); a.add(r + c); board[r][c] = \"Q\";\n      go(r + 1);\n      board[r][c] = \".\"; cols.delete(c); d.delete(r - c); a.delete(r + c);\n    }\n  }\n  go(0);\n  return out;\n}",
             "O(n!)", "O(n²)"),
            ("tp-bt-6", 6, "Subsets with duplicates", "medium", "backtrack", "skip twins",
             "nums may contain duplicates. Unique subsets.",
             "Sort. Take/skip, but if you skip a value, skip the whole run of that value.",
             "function subsetsWithDup(nums) {\n  nums.sort((a, b) => a - b);\n  const out = [], path = [];\n  function go(i) {\n    if (i === nums.length) { out.push(path.slice()); return; }\n    path.push(nums[i]); go(i + 1); path.pop();\n    let j = i + 1;\n    while (j < nums.length && nums[j] === nums[i]) j++;\n    go(j);\n  }\n  go(0);\n  return out;\n}",
             "O(n 2^n)", "O(n)"),
        ])


def dp_gym() -> str:
    return practice_gym("gym-dp", "Practice this topic — Dynamic programming",
        "Write the meaning of dp[i] in a sentence first. Then the transition. Then the loop order.",
        [
            ("tp-dp-1", 1, "House robber II (circle)", "medium", "dp", "two linear passes",
             "Houses in a circle: first and last are adjacent. Max money, no two adjacent.",
             "Answer is max(rob linear [0..n-2], rob linear [1..n-1]). n=1 is a special case.",
             "function rob(nums) {\n  if (nums.length === 1) return nums[0];\n  const line = (lo, hi) => {\n    let prev = 0, cur = 0;\n    for (let i = lo; i <= hi; i++) { const n = Math.max(cur, prev + nums[i]); prev = cur; cur = n; }\n    return cur;\n  };\n  return Math.max(line(0, nums.length - 2), line(1, nums.length - 1));\n}",
             "O(n)", "O(1)"),
            ("tp-dp-2", 2, "Decode ways", "medium", "dp", "1-digit and 2-digit",
             "s is digits. A mapping 1→A … 26→Z. Number of ways to decode. Leading zeros are invalid.",
             "dp[i] = ways for the prefix of length i. Add a single digit if s[i-1]≠0. Add a pair if 10–26.",
             "function numDecodings(s) {\n  if (!s.length || s[0] === \"0\") return 0;\n  let a = 1, b = 1;\n  for (let i = 1; i < s.length; i++) {\n    let cur = 0;\n    if (s[i] !== \"0\") cur += b;\n    const two = Number(s.slice(i - 1, i + 1));\n    if (two >= 10 && two <= 26) cur += a;\n    a = b; b = cur;\n  }\n  return b;\n}",
             "O(n)", "O(1)"),
            ("tp-dp-3", 3, "Minimum path sum", "medium", "dp", "grid from left/above",
             "m×n grid of positives. Min sum path from top-left to bottom-right, only right or down.",
             "dp[i][j] = grid + min(from above, from left). First row/col have only one incoming.",
             "function minPathSum(g) {\n  const m = g.length, n = g[0].length;\n  const dp = g.map((row) => row.slice());\n  for (let i = 1; i < m; i++) dp[i][0] += dp[i - 1][0];\n  for (let j = 1; j < n; j++) dp[0][j] += dp[0][j - 1];\n  for (let i = 1; i < m; i++)\n    for (let j = 1; j < n; j++) dp[i][j] += Math.min(dp[i - 1][j], dp[i][j - 1]);\n  return dp[m - 1][n - 1];\n}",
             "O(mn)", "O(mn)"),
            ("tp-dp-4", 4, "Partition equal subset sum", "medium", "dp", "0/1 knapsack",
             "True if you can split nums into two subsets with equal sum.",
             "If total is odd, false. Can you pick a subset that sums to total/2? Walk the boolean array backwards.",
             "function canPartition(nums) {\n  const sum = nums.reduce((s, x) => s + x, 0);\n  if (sum % 2) return false;\n  const t = sum / 2, dp = Array(t + 1).fill(false);\n  dp[0] = true;\n  for (const x of nums)\n    for (let s = t; s >= x; s--) dp[s] = dp[s] || dp[s - x];\n  return dp[t];\n}",
             "O(n · sum)", "O(sum)"),
            ("tp-dp-5", 5, "Longest palindromic substring", "medium", "dp", "expand around center",
             "Return one longest palindromic substring of s. Expand-around-center is enough; DP table is the other write-up.",
             "For each index, expand odd and even radii. Track the best start/len.",
             "function longestPalindrome(s) {\n  let start = 0, best = 1;\n  function exp(lo, hi) {\n    while (lo >= 0 && hi < s.length && s[lo] === s[hi]) { lo--; hi++; }\n    if (hi - lo - 1 > best) { start = lo + 1; best = hi - lo - 1; }\n  }\n  for (let i = 0; i < s.length; i++) { exp(i, i); exp(i, i + 1); }\n  return s.slice(start, start + best);\n}",
             "O(n²)", "O(1)"),
            ("tp-dp-6", 6, "Jump game", "medium", "dp", "farthest reach",
             "Each value is a max jump length. True if you can reach the last index.",
             "Greedy farthest: while i ≤ farthest, farthest = max(farthest, i+a[i]). True if farthest reaches the end.",
             "function canJump(a) {\n  let far = 0;\n  for (let i = 0; i < a.length && i <= far; i++) far = Math.max(far, i + a[i]);\n  return far >= a.length - 1;\n}",
             "O(n)", "O(1)"),
            ("tp-dp-7", 7, "Coin change II (count ways)", "medium", "dp", "unbounded combinations",
             "Number of combinations (order does not matter) that make amount.",
             "Outer loop coins, inner amount upward, so each coin is reused but combinations are not permuted.",
             "function change(amount, coins) {\n  const dp = Array(amount + 1).fill(0);\n  dp[0] = 1;\n  for (const c of coins)\n    for (let x = c; x <= amount; x++) dp[x] += dp[x - c];\n  return dp[amount];\n}",
             "O(amount × coins)", "O(amount)"),
            ("tp-dp-8", 8, "Unique paths with obstacles", "medium", "dp", "zero the walls",
             "Grid of 0 (open) and 1 (wall). Paths from top-left to bottom-right, right/down only.",
             "Same as unique paths, but a wall stays 0 and does not receive flow. First row/col stop after the first wall.",
             "function uniquePathsWithObstacles(g) {\n  const m = g.length, n = g[0].length;\n  if (g[0][0] === 1) return 0;\n  const dp = Array.from({length:m}, () => Array(n).fill(0));\n  dp[0][0] = 1;\n  for (let i = 0; i < m; i++)\n    for (let j = 0; j < n; j++) {\n      if (g[i][j] === 1) { dp[i][j] = 0; continue; }\n      if (i) dp[i][j] += dp[i - 1][j];\n      if (j) dp[i][j] += dp[i][j - 1];\n    }\n  return dp[m - 1][n - 1];\n}",
             "O(mn)", "O(mn)"),
        ])


def expert_gym() -> str:
    return practice_gym("gym-expert", "Practice this topic — Expert structures",
        "Trie for prefixes, union-find for components that grow, prefix arrays for range, monotonic stack for next-greater.",
        [
            ("tp-ex-1", 1, "Replace words", "medium", "design", "trie shortest root",
             "dictionary of roots. For each word in the sentence, replace with the shortest root that is a prefix.",
             "Insert roots. For each word, walk until a node with end, or fail and keep the word.",
             "function replaceWords(dictionary, sentence) {\n  const root = { next: new Map(), end: false };\n  for (const w of dictionary) {\n    let n = root;\n    for (const ch of w) {\n      if (!n.next.has(ch)) n.next.set(ch, { next: new Map(), end: false });\n      n = n.next.get(ch);\n    }\n    n.end = true;\n  }\n  const rootOf = (w) => {\n    let n = root, pref = \"\";\n    for (const ch of w) {\n      if (!n.next.has(ch)) return w;\n      n = n.next.get(ch); pref += ch;\n      if (n.end) return pref;\n    }\n    return w;\n  };\n  return sentence.split(\" \").map(rootOf).join(\" \");\n}",
             "O(total chars)", "O(dictionary)"),
            ("tp-ex-2", 2, "Accounts merge", "medium", "design", "union-find emails",
             "accounts[i] = [name, email, …]. Merge accounts that share any email. Return [name, emails sorted].",
             "Map email→id. Union ids that share an email. Then group emails by find(id).",
             "function accountsMerge(accounts) {\n  const p = [...Array(accounts.length).keys()];\n  const find = (x) => (p[x] === x ? x : (p[x] = find(p[x])));\n  const emailTo = new Map();\n  accounts.forEach((a, i) => {\n    for (let k = 1; k < a.length; k++) {\n      if (emailTo.has(a[k])) p[find(i)] = find(emailTo.get(a[k]));\n      else emailTo.set(a[k], i);\n    }\n  });\n  const groups = new Map();\n  for (const [email, i] of emailTo) {\n    const r = find(i);\n    if (!groups.has(r)) groups.set(r, []);\n    groups.get(r).push(email);\n  }\n  return [...groups.entries()].map(([r, emails]) => [accounts[r][0], ...emails.sort()]);\n}",
             "O(n α(n) + sort)", "O(n)"),
            ("tp-ex-3", 3, "Redundant connection", "medium", "design", "union reject",
             "Undirected graph with n edges on n nodes (1-based) — exactly one extra edge. Return that edge.",
             "Union edges. The first edge whose ends are already in the same component is the extra.",
             "function findRedundantConnection(edges) {\n  const n = edges.length, p = [...Array(n + 1).keys()];\n  const find = (x) => (p[x] === x ? x : (p[x] = find(p[x])));\n  for (const [a, b] of edges) {\n    const ra = find(a), rb = find(b);\n    if (ra === rb) return [a, b];\n    p[rb] = ra;\n  }\n}",
             "O(n α(n))", "O(n)"),
            ("tp-ex-4", 4, "Range sum query (immutable)", "easy", "prefix", "pref[r]-pref[l]",
             "Class(nums) then sumRange(l, r) inclusive, many queries, O(1) each.",
             "pref[0]=0, pref[i+1] = pref[i]+nums[i]. Query pref[r+1]-pref[l].",
             "class NumArray {\n  constructor(nums) {\n    this.pref = [0];\n    for (const x of nums) this.pref.push(this.pref[this.pref.length - 1] + x);\n  }\n  sumRange(l, r) { return this.pref[r + 1] - this.pref[l]; }\n}",
             "O(n) build, O(1) query", "O(n)"),
            ("tp-ex-5", 5, "Next greater circular", "medium", "stack", "walk 2n",
             "Next greater element to the right, wrapping around. -1 if none.",
             "Monotonic decreasing stack of indexes. Iterate i from 0 to 2n-1, look at a[i%n]. Only push when i < n.",
             "function nextGreaterElements(a) {\n  const n = a.length, ans = Array(n).fill(-1), st = [];\n  for (let i = 0; i < 2 * n; i++) {\n    const x = a[i % n];\n    while (st.length && a[st[st.length - 1]] < x) ans[st.pop()] = x;\n    if (i < n) st.push(i);\n  }\n  return ans;\n}",
             "O(n)", "O(n)"),
            ("tp-ex-6", 6, "Suggested products", "medium", "design", "trie or sort+bound",
             "products and a searchWord. After each typed character, up to 3 products that have that prefix, lexicographically.",
             "Sort products. For each prefix, lower-bound and take the next 3 that still match. Trie also works.",
             "function suggestedProducts(products, searchWord) {\n  products.sort();\n  const out = [];\n  let pref = \"\";\n  for (const ch of searchWord) {\n    pref += ch;\n    let lo = 0, hi = products.length;\n    while (lo < hi) {\n      const m = (lo + hi) >> 1;\n      if (products[m] < pref) lo = m + 1; else hi = m;\n    }\n    const row = [];\n    for (let i = lo; i < products.length && row.length < 3; i++) {\n      if (!products[i].startsWith(pref)) break;\n      row.push(products[i]);\n    }\n    out.push(row);\n  }\n  return out;\n}",
             "O(n log n + L · n)", "O(n)"),
            ("tp-ex-7", 7, "XOR queries of a subarray", "medium", "prefix", "xor cancel",
             "pref xor. queries [l,r] → xor of nums[l..r].",
             "xorPref[0]=0. Range = xorPref[r+1] ^ xorPref[l] because x^x=0.",
             "function xorQueries(arr, queries) {\n  const p = [0];\n  for (const x of arr) p.push(p[p.length - 1] ^ x);\n  return queries.map(([l, r]) => p[r + 1] ^ p[l]);\n}",
             "O(n+q)", "O(n)"),
            ("tp-ex-8", 8, "Car fleet", "medium", "stack", "arrive time",
             "Cars go to target. Position and speed. A faster car stuck behind a slower one becomes one fleet. How many fleets arrive?",
             "Sort by position descending (closest to target first). Track the slowest arrival time so far. A car with a larger time is a new fleet.",
             "function carFleet(target, position, speed) {\n  const cars = position.map((p, i) => [p, (target - p) / speed[i]]).sort((a, b) => b[0] - a[0]);\n  let fleets = 0, slow = 0;\n  for (const [, t] of cars) {\n    if (t > slow) { fleets++; slow = t; }\n  }\n  return fleets;\n}",
             "O(n log n)", "O(n)"),
        ])
