DAYS = [
  {"n": 1, "title": "How to learn DSA in JS",
   "learn": "How to learn section. Paper first, then type, then debugger.",
   "do": "Set up a single file playground (Node or browser console). Log a 10-element array and mutate it.",
   "verbal": "What does ‘from scratch’ mean if JS already has Array and Map?",
   "rev": "None — day 1."},
  {"n": 2, "title": "JS as a machine",
   "learn": "Values vs references, stack vs heap (mental), primitive vs object.",
   "do": "Predict 6 mutation snippets before running them.",
   "verbal": "Why does changing obj.x inside a function change the caller’s object?",
   "rev": "How you will practice this week."},
  {"n": 3, "title": "Big O",
   "learn": "Growth classes. Count loops. Extra arrays count as space.",
   "do": "Assign Big O to 8 snippets in the Big O section before revealing.",
   "verbal": "If n doubles, what happens in O(n) vs O(n²)?",
   "rev": "Reference vs copy."},
  {"n": 4, "title": "Arrays from scratch",
   "learn": "Index, push/pop, splice cost, two-array techniques.",
   "do": "Implement indexOf, reverse, and rotate in-place without built-in reverse.",
   "verbal": "Why is unshift O(n) in a JS array?",
   "rev": "O(1) vs O(n) array ops table."},
  {"n": 5, "title": "Strings",
   "learn": "Immutability, code units vs code points, two pointers on strings.",
   "do": "Implement isPalindrome and reverseWords.",
   "verbal": "Why is s += ch in a loop a trap?",
   "rev": "Array push vs unshift."},
  {"n": 6, "title": "Hash maps and sets",
   "learn": "Object vs Map vs Set. Average O(1). Frequency maps.",
   "do": "Implement twoSum and firstUniqueChar with Map.",
   "verbal": "When is an object a bad map?",
   "rev": "String immutability."},
  {"n": 7, "title": "Week 1 review + 30-min mock",
   "learn": "Arrays + maps mixed.",
   "do": "Timed mock: easy/medium array+hash. Save debrief.",
   "verbal": "twoSum in 90 seconds, complexity included.",
   "rev": "Weak snippet from days 3–6."},
  {"n": 8, "title": "Linked lists",
   "learn": "Nodes, head, dummy, reverse, cycle.",
   "do": "Implement LinkedList from scratch: push, get, reverse, detectCycle.",
   "verbal": "Why use a dummy node?",
   "rev": "Map twoSum."},
  {"n": 9, "title": "Stacks",
   "learn": "LIFO. Array as stack. Monotonic stack idea.",
   "do": "Implement validParentheses and minStack.",
   "verbal": "Name three product features that are a stack.",
   "rev": "Reverse a list on paper."},
  {"n": 10, "title": "Queues and deques",
   "learn": "FIFO. Why shift is O(n). Circular buffer or head index.",
   "do": "Implement Queue without using shift on every dequeue. Then BFS-on-array warmup.",
   "verbal": "When is a queue the right structure?",
   "rev": "Valid parentheses."},
  {"n": 11, "title": "Recursion",
   "learn": "Call stack, base case, tree of calls, tail vs not.",
   "do": "factorial, fib (naive + memo), flatten nested arrays.",
   "verbal": "What is a stack overflow in JS?",
   "rev": "Queue implementation."},
  {"n": 12, "title": "Binary trees",
   "learn": "Nodes, walks: pre/in/post, BFS levels.",
   "do": "Implement TreeNode + four traversals (recursive and iterative where taught).",
   "verbal": "BFS vs DFS — when?",
   "rev": "Recursion base case."},
  {"n": 13, "title": "BST + heap intro",
   "learn": "BST invariant. Heap as array. JS has no built-in heap.",
   "do": "Implement BST insert/search and a min-heap push/pop.",
   "verbal": "Why is heapify useful for top-k?",
   "rev": "Level-order traversal."},
  {"n": 14, "title": "Week 2 review + 45-min mock",
   "learn": "Lists + trees.",
   "do": "Mock: reverse list + max-depth tree. Save debrief.",
   "verbal": "Draw a 7-node tree and walk in-order.",
   "rev": "Heap array indexing."},
  {"n": 15, "title": "Graphs",
   "learn": "Adj list, directed vs not, BFS, DFS, cycle.",
   "do": "Implement Graph class + BFS + DFS. Detect cycle in directed graph.",
   "verbal": "How do you represent a grid as a graph?",
   "rev": "BST insert."},
  {"n": 16, "title": "Topological sort + shortest path",
   "learn": "Kahn / DFS finish times. BFS unweighted shortest.",
   "do": "Course-schedule style topo. Shortest path in a grid of 0/1.",
   "verbal": "When does Dijkstra become the next tool?",
   "rev": "Adj list vs matrix."},
  {"n": 17, "title": "Sorting and binary search",
   "learn": "How sort works in V8 (enough). Binary search templates.",
   "do": "Implement merge sort and two binary-search templates (index and boundary).",
   "verbal": "When is n log n the best comparison sort you can hope for?",
   "rev": "Topo sort."},
  {"n": 18, "title": "Two pointers",
   "learn": "Opposite ends, same direction, sorted arrays.",
   "do": "twoSum sorted, container-with-most-water, remove-duplicates in-place.",
   "verbal": "Why does sorted + two pointers beat nested loops?",
   "rev": "Binary search boundary."},
  {"n": 19, "title": "Sliding window",
   "learn": "Fixed vs variable. Map of counts.",
   "do": "maxSum k-window, longest substring without repeat.",
   "verbal": "What is the invariant of a variable window?",
   "rev": "Two pointers opposite ends."},
  {"n": 20, "title": "Backtracking",
   "learn": "Choose / explore / unchoose. Subsets, permutations.",
   "do": "subsets, permutations, combination-sum (small n).",
   "verbal": "How is backtracking different from ‘just recursion’?",
   "rev": "Window shrink condition."},
  {"n": 21, "title": "Week 3 review + 45-min mock",
   "learn": "Graphs + window + backtrack.",
   "do": "Mock: number of islands + longest unique substring.",
   "verbal": "Draw BFS on a 4×4 grid.",
   "rev": "Unchoose step."},
  {"n": 22, "title": "DP — from recursion",
   "learn": "Overlapping subproblems, memo, then table.",
   "do": "fib table, climb stairs, coin change (unbounded).",
   "verbal": "What two questions make a problem DP?",
   "rev": "Subsets tree size 2^n."},
  {"n": 23, "title": "DP — 1D and 2D",
   "learn": "LIS idea, knapsack 0/1, grid unique paths.",
   "do": "uniquePaths, 0/1 knapsack, house robber.",
   "verbal": "How do you know the state is two indices?",
   "rev": "Coin change recurrence."},
  {"n": 24, "title": "Tries and union-find",
   "learn": "Prefix tree. Disjoint sets + path compression.",
   "do": "Implement Trie (insert/search/startsWith) and UnionFind.",
   "verbal": "When is a trie better than a Set of words?",
   "rev": "DP grid paths."},
  {"n": 25, "title": "Expert patterns",
   "learn": "Monotonic stack, prefix sums, difference array, binary lifting idea (talk only).",
   "do": "dailyTemperatures, subarray sum equals k (prefix+map).",
   "verbal": "What does a monotonic stack remember?",
   "rev": "Union-find find()."},
  {"n": 26, "title": "Practical studies 1",
   "learn": "LRU, undo/redo, autocomplete.",
   "do": "Complete those three practical studies. Type the code.",
   "verbal": "Map LRU to a product feature you have shipped.",
   "rev": "Trie walk."},
  {"n": 27, "title": "Practical studies 2",
   "learn": "Dependency graph, rate limit window, virtual list window.",
   "do": "Complete those three studies.",
   "verbal": "How is a module import graph a cycle-detect problem?",
   "rev": "LRU map + list."},
  {"n": 28, "title": "Week 4 review + 60-min mock",
   "learn": "DP + expert + practical.",
   "do": "60-min: one DP + one graph. Save debrief.",
   "verbal": "Explain coin change without looking.",
   "rev": "Prefix+map."},
  {"n": 29, "title": "Problem bank — easy",
   "learn": "Warm problems.",
   "do": "Solve 8 easy problems standing up. Mark status.",
   "verbal": "Pick the weakest and redo in 10 minutes.",
   "rev": "Due-today revision."},
  {"n": 30, "title": "Problem bank — medium",
   "learn": "Core interview band.",
   "do": "Solve 8 mediums. Speak complexity each time.",
   "verbal": "What pattern did you use for each?",
   "rev": "Failed mediums."},
  {"n": 31, "title": "Problem bank — hard / stretch",
   "learn": "Expert stretch. Honest timeboxes.",
   "do": "Attempt 4 hards. Solved or Attempted is fine. Write the idea.",
   "verbal": "What made the hard problem hard?",
   "rev": "One medium you almost had."},
  {"n": 32, "title": "Q&A bank",
   "learn": "Interview questions section.",
   "do": "Answer 20 Qs standing up.",
   "verbal": "Array vs Map vs object — 90 seconds.",
   "rev": "Weak Qs."},
  {"n": 33, "title": "Mixed timed set",
   "learn": "Random mock × 2.",
   "do": "Two 45-min mocks. Different categories.",
   "verbal": "Debrief out loud: what leaked time?",
   "rev": "Checklist first pass."},
  {"n": 34, "title": "Teach-back",
   "learn": "Pick three structures and teach them to a rubber duck.",
   "do": "Write one page: list, heap, graph — ops + complexity + one use.",
   "verbal": "Implement heap push/pop from memory.",
   "rev": "Readiness gaps."},
  {"n": 35, "title": "Gate",
   "learn": "Readiness checklist. Honest.",
   "do": "60-min mock. Then light revision only.",
   "verbal": "16-minute tour: array → map → list → tree → graph → DP.",
   "rev": "Due today only."},
]


def plan() -> str:
    cards = []
    for d in DAYS:
        n = d["n"]
        body = [
            f'<label class="task"><input type="checkbox" data-id="d{n}-rev" data-group="checks" /><span><b>Revision</b> {d["rev"]}</span></label>',
            f'<label class="task"><input type="checkbox" data-id="d{n}-learn" data-group="checks" /><span><b>Concept</b> {d["learn"]}</span></label>',
            f'<label class="task"><input type="checkbox" data-id="d{n}-do" data-group="checks" /><span><b>Exercise</b> {d["do"]}</span></label>',
            f'<label class="task"><input type="checkbox" data-id="d{n}-verbal" data-group="checks" /><span><b>Verbal</b> {d["verbal"]}</span></label>',
        ]
        cards.append(f'''<article class="day" id="dsajs-day-{n}">
  <button type="button" class="day-head">
    <div>
      <h3>Day {n} — {d["title"]}</h3>
      <div class="day-meta">~2 hours · type code, do not only read</div>
    </div>
    <span class="badge badge-pattern">Day {n}</span>
  </button>
  <div class="day-body">{''.join(body)}</div>
</article>''')
    return f'''
<section class="block" id="plan" data-search="35-Day DSA JavaScript plan" data-stype="Section">
  <p class="kicker">Schedule</p>
  <h2 class="section-title">35-Day from-scratch plan</h2>
  <p class="lede">Six days a week is enough. If you miss a day, finish the implementation + one problem — do not binge three chapters.</p>
  <div class="card" style="margin-bottom:16px">
    <h3>Daily cadence</h3>
    <table>
      <tr><th>Time</th><th>Block</th><th>Rule</th></tr>
      <tr><td>10 min</td><td>Revision</td><td>Yesterday’s function from memory.</td></tr>
      <tr><td>45 min</td><td>Lesson</td><td>Read and type the implementation.</td></tr>
      <tr><td>45 min</td><td>Problem / study</td><td>Solve before reveal.</td></tr>
      <tr><td>20 min</td><td>Verbal</td><td>Complexity + when you would use it at work.</td></tr>
    </table>
  </div>
  {''.join(cards)}
</section>
'''
